GamR: GamR::Spect::PeakFitGuesses Class Reference
GamR::Spect::PeakFitGuesses Class Reference
#include <FitGuesses.hh>
Public Member Functions
PeakFitGuesses ()
int Load (std::string filename)
void Print ()
void Save (std::string filename)
void Save ()
void Set (int i, double val, double low, double high)
void Set ()
Public Attributes
Parameter fWidth
Parameter fStepAmp
Parameter fSkewAmp
Parameter fSkewWidth
Parameter fSkewAmp2
Parameter fSkewWidth2
Parameter fScale
Detailed Description
Definition at line 23 of file FitGuesses.hh.
Constructor & Destructor Documentation
PeakFitGuesses()
GamR::Spect::PeakFitGuesses::PeakFitGuesses () inline
Definition at line 35 of file FitGuesses.hh.
References fScale, fSkewAmp, fSkewAmp2, fSkewWidth, fSkewWidth2, and fStepAmp.
Member Function Documentation
Load()
int GamR::Spect::PeakFitGuesses::Load (std::string filename)
Print()
void GamR::Spect::PeakFitGuesses::Print ()
Referenced by pfprint().
Save() [1/2]
void GamR::Spect::PeakFitGuesses::Save ()
Save() [2/2]
void GamR::Spect::PeakFitGuesses::Save (std::string filename)
Referenced by pfsave(), and pfsave().
Set() [1/2]
void GamR::Spect::PeakFitGuesses::Set ()
Set() [2/2]
void GamR::Spect::PeakFitGuesses::Set (int i, double val, double low, double high)
Referenced by pfconf().
Member Data Documentation
fScale
Parameter GamR::Spect::PeakFitGuesses::fScale
Definition at line 31 of file FitGuesses.hh.
Referenced by PeakFitGuesses().
fSkewAmp
Parameter GamR::Spect::PeakFitGuesses::fSkewAmp
Definition at line 27 of file FitGuesses.hh.
Referenced by PeakFitGuesses().
fSkewAmp2
Parameter GamR::Spect::PeakFitGuesses::fSkewAmp2
Definition at line 29 of file FitGuesses.hh.
Referenced by PeakFitGuesses().
fSkewWidth
Parameter GamR::Spect::PeakFitGuesses::fSkewWidth
Definition at line 28 of file FitGuesses.hh.
Referenced by PeakFitGuesses().
fSkewWidth2
Parameter GamR::Spect::PeakFitGuesses::fSkewWidth2
Definition at line 30 of file FitGuesses.hh.
Referenced by PeakFitGuesses().
fStepAmp
Parameter GamR::Spect::PeakFitGuesses::fStepAmp
Definition at line 26 of file FitGuesses.hh.
Referenced by PeakFitGuesses().
fWidth
Parameter GamR::Spect::PeakFitGuesses::fWidth
Definition at line 25 of file FitGuesses.hh.
The documentation for this class was generated from the following file:
src/lib/spect/FitGuesses.hh