GamR: GamR::Sort::Type::GatedTimeDifference< DetGate, S, DetTime, E, T > Class Template Reference
GamR::Sort::Type::GatedTimeDifference< DetGate, S, DetTime, E, T > Class Template Reference
#include <GatedTimeDifference.hh>
Public Member Functions
GatedTimeDifference (Sorter *parent, std::vector< std::string > opts)
void operator() (TTreeReader &R)
Detailed Description
template<class DetGate, size_t S, class DetTime, size_t E, size_t T>
class GamR::Sort::Type::GatedTimeDifference< DetGate, S, DetTime, E, T >
Definition at line 22 of file GatedTimeDifference.hh.
Constructor & Destructor Documentation
GatedTimeDifference()
template<class DetGate , size_t S, class DetTime , size_t E, size_t T> GamR::Sort::Type::GatedTimeDifference< DetGate, S, DetTime, E, T >::GatedTimeDifference (Sorter * parent, std::vector< std::string > opts) inline
Definition at line 33 of file GatedTimeDifference.hh.
References GamR::Sort::Sorter::GetMatrix(), ss(), and GamR::Sort::Sorter::WriteObject().
Member Function Documentation
operator()()
template<class DetGate , size_t S, class DetTime , size_t E, size_t T> void GamR::Sort::Type::GatedTimeDifference< DetGate, S, DetTime, E, T >::operator() (TTreeReader & R) inline
Definition at line 108 of file GatedTimeDifference.hh.
References GamR::Sort::Sorter::Done(), and GamR::Sort::Sorter::Tick().
The documentation for this class was generated from the following file:
src/lib/sort/GatedTimeDifference.hh