GamR: GamR::AngDist::DoubleGaussianDistr::GlobalChiSquare Class Reference
GamR::AngDist::DoubleGaussianDistr::GlobalChiSquare Class Reference
Public Member Functions
GlobalChiSquare (DoubleGaussianDistr *parent)
Static Public Member Functions
static void minuit (int &npar, double *gin, double &f, double *par, int iflag)
Detailed Description
Definition at line 218 of file GaussianDistr.cc.
Constructor & Destructor Documentation
GlobalChiSquare()
GamR::AngDist::DoubleGaussianDistr::GlobalChiSquare::GlobalChiSquare (DoubleGaussianDistr * parent) inline
Definition at line 223 of file GaussianDistr.cc.
Member Function Documentation
minuit()
static void GamR::AngDist::DoubleGaussianDistr::GlobalChiSquare::minuit (int & npar, double * gin, double & f, double * par, int iflag) inline static
Definition at line 225 of file GaussianDistr.cc.
References GamR::AngDist::DoubleGaussianDistr::FitFunc, GamR::AngDist::DoubleGaussianDistr::FixedField, GamR::AngDist::DoubleGaussianDistr::GetFunc(), GamR::AngDist::DoubleGaussianDistr::Hist, GamR::AngDist::DoubleGaussianDistr::SetAmp1(), GamR::AngDist::DoubleGaussianDistr::SetAmp2(), GamR::AngDist::DoubleGaussianDistr::SetField(), GamR::AngDist::DoubleGaussianDistr::SetFWHM(), GamR::AngDist::DoubleGaussianDistr::SetG1(), GamR::AngDist::DoubleGaussianDistr::SetG2(), GamR::AngDist::DoubleGaussianDistr::SetMean(), GamR::AngDist::DoubleGaussianDistr::SetN1N2(), GamR::AngDist::DoubleGaussianDistr::SetOffset(), GamR::AngDist::DoubleGaussianDistr::SetTau1(), and GamR::AngDist::DoubleGaussianDistr::SetTau2().
Referenced by GamR::AngDist::DoubleGaussianDistr::Fit().
The documentation for this class was generated from the following file:
src/lib/angdist/GaussianDistr.cc