#+TITLE: GamROOT -- CERN ROOT Libraries for Gamma
#+DATE: Tue Sep 26 19:56:19 AEST 2017

* About this repository

This code base is an attempt to create a functional, modern, complete,
flexible, readable, self documenting, and well documented library for
CERN's ROOT Data Analysis Framework for application to low-energy
Nuclear Physics.

* Quick start

Ensure you have =ROOT6= compiled with =C++14= extensions enabled!

We are now using =CMake= so that standalone applications / tools can be
made. This should make libraries that can be loaded in =ROOT=.

#+BEGIN_SRC shell
git clone <wherever this is>/gamma-root
cd gamma-root
mkdir build
cmake -DCMAKE_BUILD_TYPE=RELEASE ../src
make
#+END_SRC

If you want to keep using the =ACLiC= method of using =.L file.cc+=,
add =gamma-root/src/gamroot= to your =ROOT= include path.

It is recommended to use =CMake= and the compiled libraries as it has
more defined / structured behaviour.

* Contributing

Excited to contribute yourself? I don't blame you!

This project is going through a lean development process, so we don't
have style and design guidelines/rules set in stone -- yet, but we're
getting there! Your best bet is to talk to one of the current
developers for a primer, we really could use your help!

* Current Developers

+ Timothy Gray <graytj@ornl.gov>

** Previous contributors

+ Aqeel Akber
+ Ben Coombes
+ Jackson Dowie
+ Brendan McCormick

