#+TITLE: GamROOT -- CERN ROOT Libraries for Gamma
#+DATE: Tue Sep 26 19:56:19 AEST 2017

* About this repository

This code base is an attempt to create a functional, modern, complete,
flexible, readable, self documenting, and well documented library for
CERN's ROOT Data Analysis Framework for application to low-energy
Nuclear Physics. Originally developed by PhD candidates at the
Australian National University. 

* Quick start

Ensure you have =ROOT6= compiled with =C++14= extensions enabled!

We are now using =CMake= so that standalone applications / tools can be
made. This should make libraries that can be loaded in =ROOT=.

#+BEGIN_SRC shell
git clone <wherever this is>/gamma-root
cd gamma-root
mkdir build
cmake -DCMAKE_BUILD_TYPE=RELEASE ../src
make
#+END_SRC

It is recommended to use =CMake= and the compiled libraries as it has
more defined / structured behaviour.

Docs can be viewed at [[https://belmakier.github.io/gamma-root/][https://belmakier.github.io/gamma-root/]]

* Contributing

Contributors are welcome, feel free to contact me.

* Current Developers

+ Timothy Gray <graytj@ornl.gov>

** Previous contributors

+ Aqeel Akber
+ Ben Coombes
+ Jackson Dowie
+ Brendan McCormick

