GamR: GamR::AngDist::DoubleGaussianDistr Class Reference
GamR::AngDist::DoubleGaussianDistr Class Reference
#include <GaussianDistr.hh>
Classes
class GlobalChiSquare
Public Member Functions
DoubleGaussianDistr (double L, double H, std::vector< double > pars)
void Normalise ()
std::vector< double > GetBhfs ()
std::vector< double > GetRelAmps ()
void SetSamples (int i)
void SetLimit (int i)
void SetAmp1 (double a)
void SetAmp2 (double a)
void SetG1 (double gfac)
void SetG2 (double gfac)
void SetTau1 (double tau)
void SetTau2 (double tau)
void SetN1N2 (double n)
void SetMean (double m)
void SetFWHM (double w)
void SetOffset (double o)
void SetHist (TH1 *hist)
void SetField ()
double GetG1 ()
double GetG1Err ()
double GetG2 ()
double GetG2Err ()
double GetAmp1 ()
double GetAmp1Err ()
double GetAmp2 ()
double GetAmp2Err ()
double GetTau1 ()
double GetTau1Err ()
double GetTau2 ()
double GetTau2Err ()
double GetN1N2 ()
double GetN1N2Err ()
double GetMean ()
double GetMeanErr ()
double GetFWHM ()
double GetFWHMErr ()
double GetOffset ()
double GetOffsetErr ()
void FixField ()
void UnFixField ()
void FixG1 ()
void UnFixG1 ()
void FixG2 ()
void UnFixG2 ()
void FixAmp1 ()
void UnFixAmp1 ()
void FixAmp2 ()
void UnFixAmp2 ()
void FixTau1 ()
void UnFixTau1 ()
void FixTau2 ()
void UnFixTau2 ()
void FixN1N2 ()
void UnFixN1N2 ()
void FixOffset ()
void UnFixOffset ()
std::vector< double > GetPars ()
void SetPars ()
void SetPars (std::vector< double > pars)
void SetParLimits (int i, double low, double high)
double RatioFunc (double x, double a1, double a2, double gfac1, double gfac2, double t1, double t2, double n, double off)
double operator() (double *x, double *p)
TF1 * GetFunc ()
void Fit (int quiet)
void Print ()
Public Attributes
double amp1
double amp2
double g1
double g2
double tau1
double tau2
double n1n2
double mean
double FWHM
double offset
double Low
double High
TH1 * Hist
TF1 * FitFunc
int FixedField
Detailed Description
Definition at line 116 of file GaussianDistr.hh.
Constructor & Destructor Documentation
DoubleGaussianDistr()
GamR::AngDist::DoubleGaussianDistr::DoubleGaussianDistr (double L, double H, std::vector< double > pars) inline
Definition at line 151 of file GaussianDistr.hh.
References FixedField, High, Low, and SetPars().
Referenced by GamR::AngDist::DoubleGaussianDistr::GlobalChiSquare::GlobalChiSquare().
Member Function Documentation
Fit()
void GamR::AngDist::DoubleGaussianDistr::Fit (int quiet)
Definition at line 266 of file GaussianDistr.cc.
References FitFunc, FixedField, GetPars(), High, Low, GamR::AngDist::DoubleGaussianDistr::GlobalChiSquare::minuit(), SetField(), and SetPars().
FixAmp1()
void GamR::AngDist::DoubleGaussianDistr::FixAmp1 () inline
Definition at line 205 of file GaussianDistr.hh.
FixAmp2()
void GamR::AngDist::DoubleGaussianDistr::FixAmp2 () inline
Definition at line 207 of file GaussianDistr.hh.
FixField()
void GamR::AngDist::DoubleGaussianDistr::FixField () inline
Definition at line 199 of file GaussianDistr.hh.
References FixedField.
FixG1()
void GamR::AngDist::DoubleGaussianDistr::FixG1 () inline
Definition at line 201 of file GaussianDistr.hh.
FixG2()
void GamR::AngDist::DoubleGaussianDistr::FixG2 () inline
Definition at line 203 of file GaussianDistr.hh.
FixN1N2()
void GamR::AngDist::DoubleGaussianDistr::FixN1N2 () inline
Definition at line 213 of file GaussianDistr.hh.
FixOffset()
void GamR::AngDist::DoubleGaussianDistr::FixOffset () inline
Definition at line 215 of file GaussianDistr.hh.
FixTau1()
void GamR::AngDist::DoubleGaussianDistr::FixTau1 () inline
Definition at line 209 of file GaussianDistr.hh.
FixTau2()
void GamR::AngDist::DoubleGaussianDistr::FixTau2 () inline
Definition at line 211 of file GaussianDistr.hh.
GetAmp1()
double GamR::AngDist::DoubleGaussianDistr::GetAmp1 () inline
Definition at line 182 of file GaussianDistr.hh.
References amp1.
Referenced by Print().
GetAmp1Err()
double GamR::AngDist::DoubleGaussianDistr::GetAmp1Err () inline
Definition at line 183 of file GaussianDistr.hh.
Referenced by Print().
GetAmp2()
double GamR::AngDist::DoubleGaussianDistr::GetAmp2 () inline
Definition at line 184 of file GaussianDistr.hh.
References amp2.
Referenced by Print().
GetAmp2Err()
double GamR::AngDist::DoubleGaussianDistr::GetAmp2Err () inline
Definition at line 185 of file GaussianDistr.hh.
Referenced by Print().
GetBhfs()
std::vector< double > GamR::AngDist::DoubleGaussianDistr::GetBhfs () inline
Definition at line 161 of file GaussianDistr.hh.
GetFunc()
TF1 * GamR::AngDist::DoubleGaussianDistr::GetFunc ()
Definition at line 205 of file GaussianDistr.cc.
References amp1, amp2, g1, g2, High, Low, n1n2, offset, tau1, and tau2.
GetFWHM()
double GamR::AngDist::DoubleGaussianDistr::GetFWHM () inline
Definition at line 194 of file GaussianDistr.hh.
References FWHM.
Referenced by Print().
GetFWHMErr()
double GamR::AngDist::DoubleGaussianDistr::GetFWHMErr () inline
Definition at line 195 of file GaussianDistr.hh.
Referenced by Print().
GetG1()
double GamR::AngDist::DoubleGaussianDistr::GetG1 () inline
Definition at line 178 of file GaussianDistr.hh.
References g1.
Referenced by Print().
GetG1Err()
double GamR::AngDist::DoubleGaussianDistr::GetG1Err () inline
Definition at line 179 of file GaussianDistr.hh.
Referenced by Print().
GetG2()
double GamR::AngDist::DoubleGaussianDistr::GetG2 () inline
Definition at line 180 of file GaussianDistr.hh.
References g2.
Referenced by Print().
GetG2Err()
double GamR::AngDist::DoubleGaussianDistr::GetG2Err () inline
Definition at line 181 of file GaussianDistr.hh.
Referenced by Print().
GetMean()
double GamR::AngDist::DoubleGaussianDistr::GetMean () inline
Definition at line 192 of file GaussianDistr.hh.
References mean.
Referenced by Print().
GetMeanErr()
double GamR::AngDist::DoubleGaussianDistr::GetMeanErr () inline
Definition at line 193 of file GaussianDistr.hh.
Referenced by Print().
GetN1N2()
double GamR::AngDist::DoubleGaussianDistr::GetN1N2 () inline
Definition at line 190 of file GaussianDistr.hh.
References n1n2.
Referenced by Print().
GetN1N2Err()
double GamR::AngDist::DoubleGaussianDistr::GetN1N2Err () inline
Definition at line 191 of file GaussianDistr.hh.
Referenced by Print().
GetOffset()
double GamR::AngDist::DoubleGaussianDistr::GetOffset () inline
Definition at line 196 of file GaussianDistr.hh.
References offset.
Referenced by Print().
GetOffsetErr()
double GamR::AngDist::DoubleGaussianDistr::GetOffsetErr () inline
Definition at line 197 of file GaussianDistr.hh.
Referenced by Print().
GetPars()
std::vector< double > GamR::AngDist::DoubleGaussianDistr::GetPars () inline
Definition at line 217 of file GaussianDistr.hh.
References amp1, amp2, FWHM, g1, g2, mean, n1n2, offset, tau1, and tau2.
Referenced by Fit().
GetRelAmps()
std::vector< double > GamR::AngDist::DoubleGaussianDistr::GetRelAmps () inline
Definition at line 162 of file GaussianDistr.hh.
GetTau1()
double GamR::AngDist::DoubleGaussianDistr::GetTau1 () inline
Definition at line 186 of file GaussianDistr.hh.
References tau1.
Referenced by Print().
GetTau1Err()
double GamR::AngDist::DoubleGaussianDistr::GetTau1Err () inline
Definition at line 187 of file GaussianDistr.hh.
Referenced by Print().
GetTau2()
double GamR::AngDist::DoubleGaussianDistr::GetTau2 () inline
Definition at line 188 of file GaussianDistr.hh.
References tau2.
Referenced by Print().
GetTau2Err()
double GamR::AngDist::DoubleGaussianDistr::GetTau2Err () inline
Definition at line 189 of file GaussianDistr.hh.
Referenced by Print().
Normalise()
void GamR::AngDist::DoubleGaussianDistr::Normalise ()
Definition at line 171 of file GaussianDistr.cc.
Referenced by SetField().
operator()()
double GamR::AngDist::DoubleGaussianDistr::operator() (double * x, double * p)
Definition at line 201 of file GaussianDistr.cc.
References RatioFunc().
Print()
void GamR::AngDist::DoubleGaussianDistr::Print () inline
Definition at line 230 of file GaussianDistr.hh.
References GetAmp1(), GetAmp1Err(), GetAmp2(), GetAmp2Err(), GetFWHM(), GetFWHMErr(), GetG1(), GetG1Err(), GetG2(), GetG2Err(), GetMean(), GetMeanErr(), GetN1N2(), GetN1N2Err(), GetOffset(), GetOffsetErr(), GetTau1(), GetTau1Err(), GetTau2(), GetTau2Err(), and GamR::Utils::wrresult().
RatioFunc()
double GamR::AngDist::DoubleGaussianDistr::RatioFunc (double x, double a1, double a2, double gfac1, double gfac2, double t1, double t2, double n, double off)
Definition at line 181 of file GaussianDistr.cc.
Referenced by operator()().
SetAmp1()
void GamR::AngDist::DoubleGaussianDistr::SetAmp1 (double a) inline
Definition at line 165 of file GaussianDistr.hh.
References amp1.
SetAmp2()
void GamR::AngDist::DoubleGaussianDistr::SetAmp2 (double a) inline
Definition at line 166 of file GaussianDistr.hh.
References amp2.
SetField()
void GamR::AngDist::DoubleGaussianDistr::SetField ()
Definition at line 157 of file GaussianDistr.cc.
References FWHM, mean, and Normalise().
Referenced by Fit().
SetFWHM()
void GamR::AngDist::DoubleGaussianDistr::SetFWHM (double w) inline
Definition at line 173 of file GaussianDistr.hh.
References FWHM.
SetG1()
void GamR::AngDist::DoubleGaussianDistr::SetG1 (double gfac) inline
Definition at line 167 of file GaussianDistr.hh.
References g1.
SetG2()
void GamR::AngDist::DoubleGaussianDistr::SetG2 (double gfac) inline
Definition at line 168 of file GaussianDistr.hh.
References g2.
SetHist()
void GamR::AngDist::DoubleGaussianDistr::SetHist (TH1 * hist) inline
Definition at line 175 of file GaussianDistr.hh.
References Hist.
SetLimit()
void GamR::AngDist::DoubleGaussianDistr::SetLimit (int i) inline
Definition at line 164 of file GaussianDistr.hh.
SetMean()
void GamR::AngDist::DoubleGaussianDistr::SetMean (double m) inline
Definition at line 172 of file GaussianDistr.hh.
References mean.
SetN1N2()
void GamR::AngDist::DoubleGaussianDistr::SetN1N2 (double n) inline
Definition at line 171 of file GaussianDistr.hh.
References n1n2.
SetOffset()
void GamR::AngDist::DoubleGaussianDistr::SetOffset (double o) inline
Definition at line 174 of file GaussianDistr.hh.
References offset.
SetParLimits()
void GamR::AngDist::DoubleGaussianDistr::SetParLimits (int i, double low, double high) inline
Definition at line 222 of file GaussianDistr.hh.
SetPars() [1/2]
void GamR::AngDist::DoubleGaussianDistr::SetPars () inline
Definition at line 219 of file GaussianDistr.hh.
References SetPars().
Referenced by DoubleGaussianDistr(), Fit(), and SetPars().
SetPars() [2/2]
void GamR::AngDist::DoubleGaussianDistr::SetPars (std::vector< double > pars) inline
Definition at line 220 of file GaussianDistr.hh.
References amp1, amp2, FWHM, g1, g2, mean, n1n2, offset, tau1, and tau2.
SetSamples()
void GamR::AngDist::DoubleGaussianDistr::SetSamples (int i) inline
Definition at line 163 of file GaussianDistr.hh.
SetTau1()
void GamR::AngDist::DoubleGaussianDistr::SetTau1 (double tau) inline
Definition at line 169 of file GaussianDistr.hh.
References tau1.
SetTau2()
void GamR::AngDist::DoubleGaussianDistr::SetTau2 (double tau) inline
Definition at line 170 of file GaussianDistr.hh.
References tau2.
UnFixAmp1()
void GamR::AngDist::DoubleGaussianDistr::UnFixAmp1 () inline
Definition at line 206 of file GaussianDistr.hh.
UnFixAmp2()
void GamR::AngDist::DoubleGaussianDistr::UnFixAmp2 () inline
Definition at line 208 of file GaussianDistr.hh.
UnFixField()
void GamR::AngDist::DoubleGaussianDistr::UnFixField () inline
Definition at line 200 of file GaussianDistr.hh.
References FixedField.
UnFixG1()
void GamR::AngDist::DoubleGaussianDistr::UnFixG1 () inline
Definition at line 202 of file GaussianDistr.hh.
UnFixG2()
void GamR::AngDist::DoubleGaussianDistr::UnFixG2 () inline
Definition at line 204 of file GaussianDistr.hh.
UnFixN1N2()
void GamR::AngDist::DoubleGaussianDistr::UnFixN1N2 () inline
Definition at line 214 of file GaussianDistr.hh.
UnFixOffset()
void GamR::AngDist::DoubleGaussianDistr::UnFixOffset () inline
Definition at line 216 of file GaussianDistr.hh.
UnFixTau1()
void GamR::AngDist::DoubleGaussianDistr::UnFixTau1 () inline
Definition at line 210 of file GaussianDistr.hh.
UnFixTau2()
void GamR::AngDist::DoubleGaussianDistr::UnFixTau2 () inline
Definition at line 212 of file GaussianDistr.hh.
Member Data Documentation
amp1
double GamR::AngDist::DoubleGaussianDistr::amp1
Definition at line 132 of file GaussianDistr.hh.
Referenced by GetAmp1(), GetFunc(), GetPars(), SetAmp1(), and SetPars().
amp2
double GamR::AngDist::DoubleGaussianDistr::amp2
Definition at line 133 of file GaussianDistr.hh.
Referenced by GetAmp2(), GetFunc(), GetPars(), SetAmp2(), and SetPars().
FitFunc
TF1* GamR::AngDist::DoubleGaussianDistr::FitFunc
Definition at line 147 of file GaussianDistr.hh.
Referenced by Fit().
FixedField
int GamR::AngDist::DoubleGaussianDistr::FixedField
Definition at line 149 of file GaussianDistr.hh.
Referenced by DoubleGaussianDistr(), Fit(), FixField(), and UnFixField().
FWHM
double GamR::AngDist::DoubleGaussianDistr::FWHM
Definition at line 140 of file GaussianDistr.hh.
Referenced by GetFWHM(), GetPars(), SetField(), SetFWHM(), and SetPars().
g1
double GamR::AngDist::DoubleGaussianDistr::g1
Definition at line 134 of file GaussianDistr.hh.
Referenced by GetFunc(), GetG1(), GetPars(), SetG1(), and SetPars().
g2
double GamR::AngDist::DoubleGaussianDistr::g2
Definition at line 135 of file GaussianDistr.hh.
Referenced by GetFunc(), GetG2(), GetPars(), SetG2(), and SetPars().
High
double GamR::AngDist::DoubleGaussianDistr::High
Definition at line 144 of file GaussianDistr.hh.
Referenced by DoubleGaussianDistr(), Fit(), and GetFunc().
Hist
TH1* GamR::AngDist::DoubleGaussianDistr::Hist
Definition at line 146 of file GaussianDistr.hh.
Referenced by SetHist().
Low
double GamR::AngDist::DoubleGaussianDistr::Low
Definition at line 143 of file GaussianDistr.hh.
Referenced by DoubleGaussianDistr(), Fit(), and GetFunc().
mean
double GamR::AngDist::DoubleGaussianDistr::mean
Definition at line 139 of file GaussianDistr.hh.
Referenced by GetMean(), GetPars(), SetField(), SetMean(), and SetPars().
n1n2
double GamR::AngDist::DoubleGaussianDistr::n1n2
Definition at line 138 of file GaussianDistr.hh.
Referenced by GetFunc(), GetN1N2(), GetPars(), SetN1N2(), and SetPars().
offset
double GamR::AngDist::DoubleGaussianDistr::offset
Definition at line 141 of file GaussianDistr.hh.
Referenced by GetFunc(), GetOffset(), GetPars(), SetOffset(), and SetPars().
tau1
double GamR::AngDist::DoubleGaussianDistr::tau1
Definition at line 136 of file GaussianDistr.hh.
Referenced by GetFunc(), GetPars(), GetTau1(), SetPars(), and SetTau1().
tau2
double GamR::AngDist::DoubleGaussianDistr::tau2
Definition at line 137 of file GaussianDistr.hh.
Referenced by GetFunc(), GetPars(), GetTau2(), SetPars(), and SetTau2().
The documentation for this class was generated from the following files:
src/lib/angdist/GaussianDistr.hh
src/lib/angdist/GaussianDistr.cc