GamR: GamR::AngDist::SolidAttenuation Class Reference
GamR::AngDist::SolidAttenuation Class Reference
#include <SolidAttenuation.hh>
Public Member Functions
SolidAttenuation (std::vector< double > Qk)
SolidAttenuation (double distance, double radius, int kmax=4, double absorbCoeff=-1)
SolidAttenuation (double distance, double length, double outer_radius, double inner_radius, double energy, int kmax=4)
std::vector< double > Get ()
double Get (double k)
void Set (double k, double Qk_in)
void Print ()
Detailed Description
Definition at line 22 of file SolidAttenuation.hh.
Constructor & Destructor Documentation
SolidAttenuation() [1/3]
GamR::AngDist::SolidAttenuation::SolidAttenuation (std::vector< double > Qk)
SolidAttenuation constructor by explicit setting.
Parameters
Qk Vector containing desired Qk coefficients
Definition at line 30 of file SolidAttenuation.cc.
SolidAttenuation() [2/3]
GamR::AngDist::SolidAttenuation::SolidAttenuation (double distance, double radius, int kmax = 4, double absorbCoeff = -1)
SolidAttenuation constructor for simple geometry and absorption.
Calculates solid attenuation coefficients assuming a cylindrical geometry and optionally a simple 1-exp(-mu*x) absorption. See Appendix 9 of Alpha- Beta- Gamma-Ray Spectroscopy, Kai Siegbahn for details.
Parameters
distance Distance of the face of the crystal from the source
radius Radius of the circular face of the detector
kmax Maximum k to calculate
absorbCoeff Absorption coefficient
Definition at line 48 of file SolidAttenuation.cc.
SolidAttenuation() [3/3]
GamR::AngDist::SolidAttenuation::SolidAttenuation (double distance, double length, double outer_radius, double inner_radius, double energy, int kmax = 4)
Definition at line 86 of file SolidAttenuation.cc.
References GamR::AngDist::GetTauG(), and GamR::Utils::Simps().
Member Function Documentation
Get() [1/2]
std::vector< double > GamR::AngDist::SolidAttenuation::Get () inline
Definition at line 33 of file SolidAttenuation.hh.
Referenced by GamR::AngDist::StatTensor::ObservedProp(), GamR::AngDist::StatTensor::UnobservedProp(), GamR::AngDist::StatTensor::W(), GamR::AngDist::W(), and GamR::AngDist::W().
Get() [2/2]
double GamR::AngDist::SolidAttenuation::Get (double k) inline
Definition at line 34 of file SolidAttenuation.hh.
Print()
void GamR::AngDist::SolidAttenuation::Print () inline
Definition at line 36 of file SolidAttenuation.hh.
Set()
void GamR::AngDist::SolidAttenuation::Set (double k, double Qk_in) inline
Definition at line 35 of file SolidAttenuation.hh.
The documentation for this class was generated from the following files:
src/lib/angdist/SolidAttenuation.hh
src/lib/angdist/SolidAttenuation.cc