GamR: GamR::Efficiency::EffFit Class Reference
GamR::Efficiency::EffFit Class Reference
#include <Efficiency.hh>
Classes
class GlobalChiSquare
Public Member Functions
EffFit ()
void AddData (DataSet dataset)
void EraseData (int iDataSet, std::string key)
void SetParams (FitParams params)
void PrintParams (const char *fileName)
void Fit (int quiet=0)
TMultiGraph * Draw (TCanvas *canvas, int detID=0, double xlow=-1, double xhigh=-1, bool log=false)
void WriteGraph (std::string outDir)
TMultiGraph * DrawRes (TCanvas *canvas, int detID=0, double xlow=-1, double xhigh=-1)
void Draw (const char *outFile, double xlow=-1, double xhigh=-1, bool log=false)
Public Attributes
std::vector< DataSet > fDataSets
double fAbsScale
bool EqualWeights = false
TF1 * EffFunc
Detailed Description
Definition at line 76 of file Efficiency.hh.
Constructor & Destructor Documentation
EffFit()
GamR::Efficiency::EffFit::EffFit ()
Definition at line 512 of file Efficiency.cc.
References GamR::Efficiency::EffCFunc(), EffFunc, and fAbsScale.
Referenced by GamR::Efficiency::EffFit::GlobalChiSquare::GlobalChiSquare().
Member Function Documentation
AddData()
void GamR::Efficiency::EffFit::AddData (DataSet dataset) inline
Definition at line 86 of file Efficiency.hh.
References fDataSets.
Draw() [1/2]
void GamR::Efficiency::EffFit::Draw (const char * outFile, double xlow = -1, double xhigh = -1, bool log = false)
Definition at line 965 of file Efficiency.cc.
References Draw(), DrawRes(), and log().
Draw() [2/2]
TMultiGraph * GamR::Efficiency::EffFit::Draw (TCanvas * canvas, int detID = 0, double xlow = -1, double xhigh = -1, bool log = false)
Definition at line 850 of file Efficiency.cc.
References EffFunc, fAbsScale, fDataSets, and log().
Referenced by Draw(), and Fit().
DrawRes()
TMultiGraph * GamR::Efficiency::EffFit::DrawRes (TCanvas * canvas, int detID = 0, double xlow = -1, double xhigh = -1)
Definition at line 922 of file Efficiency.cc.
References EffFunc, and fDataSets.
Referenced by Draw().
EraseData()
void GamR::Efficiency::EffFit::EraseData (int iDataSet, std::string key) inline
Definition at line 87 of file Efficiency.hh.
References fDataSets.
Fit()
void GamR::Efficiency::EffFit::Fit (int quiet = 0)
Definition at line 635 of file Efficiency.cc.
References Draw(), EffFunc, fAbsScale, and fDataSets.
PrintParams()
void GamR::Efficiency::EffFit::PrintParams (const char * fileName)
Definition at line 1181 of file Efficiency.cc.
References EffFunc.
SetParams()
void GamR::Efficiency::EffFit::SetParams (FitParams params)
Definition at line 816 of file Efficiency.cc.
References EffFunc, fAbsScale, fDataSets, GamR::Efficiency::FitParams::fixed, GamR::Efficiency::FitParams::limhigh, GamR::Efficiency::FitParams::limlow, and GamR::Efficiency::FitParams::params.
WriteGraph()
void GamR::Efficiency::EffFit::WriteGraph (std::string outDir)
Definition at line 894 of file Efficiency.cc.
References EffFunc, and fDataSets.
Member Data Documentation
EffFunc
TF1* GamR::Efficiency::EffFit::EffFunc
Definition at line 84 of file Efficiency.hh.
Referenced by EffFit(), Draw(), DrawRes(), Fit(), PrintParams(), SetParams(), and WriteGraph().
EqualWeights
bool GamR::Efficiency::EffFit::EqualWeights = false
Definition at line 83 of file Efficiency.hh.
fAbsScale
double GamR::Efficiency::EffFit::fAbsScale
Definition at line 82 of file Efficiency.hh.
Referenced by EffFit(), Draw(), Fit(), and SetParams().
fDataSets
std::vector<DataSet> GamR::Efficiency::EffFit::fDataSets
Definition at line 81 of file Efficiency.hh.
Referenced by AddData(), Draw(), DrawRes(), EraseData(), Fit(), SetParams(), and WriteGraph().
The documentation for this class was generated from the following files:
src/lib/efficiency/Efficiency.hh
src/lib/efficiency/Efficiency.cc