GamR: GamR::AngDist::StatTensor Class Reference
GamR::AngDist::StatTensor Class Reference
#include <StatTensor.hh>
Public Member Functions
StatTensor (double j)
StatTensor (std::vector< double > Pm, double j)
StatTensor (double j, double sigmaj)
void Clear ()
void Set (std::vector< double > Pm)
std::complex< double > Get (double k, double q)
std::complex< double > Set (double k, double q, std::complex< double > value)
std::complex< double > GetBk (double k)
StatTensor * ObservedProp (double ji, double lambda, double lambdaPrime, double jf, double delta, SolidAttenuation *Qk, double theta, double phi)
StatTensor * UnobservedProp (double ji, double lambda, double lambdaPrime, double jf, double delta, SolidAttenuation *Qk)
StatTensor * Perturbation (std::function< std::complex< double >(double, double, double, double, double) > &Gk, double t)
double W (double ji, double lambda, double lambdaPrime, double jf, double delta, SolidAttenuation *Qk, double theta, double phi)
void Print ()
Detailed Description
Definition at line 22 of file StatTensor.hh.
Constructor & Destructor Documentation
StatTensor() [1/3]
GamR::AngDist::StatTensor::StatTensor (double j)
Constructor that initialises the correct dimensions given the spin
Parameters
j Max spin
Definition at line 26 of file StatTensor.cc.
References Clear().
Referenced by StatTensor(), StatTensor(), ObservedProp(), Perturbation(), and UnobservedProp().
StatTensor() [2/3]
GamR::AngDist::StatTensor::StatTensor (std::vector< double > Pm, double j)
Statistical tensor constructor using the population parameter definition expanded from that included in Morinaga and Yamazaki - see AES NIM A 485(2002)753 Equation 2.36
Parameters
Pm Vector of m-projections weights, i.e. \(-j, -j+1,...,j-1,j\)
j Max spin
Definition at line 40 of file StatTensor.cc.
References StatTensor(), and Set().
StatTensor() [3/3]
GamR::AngDist::StatTensor::StatTensor (double j, double sigmaj) inline
Definition at line 33 of file StatTensor.hh.
References StatTensor(), GamR::AngDist::PopulationParameter::GetPm(), and Set().
Member Function Documentation
Clear()
void GamR::AngDist::StatTensor::Clear ()
Initialises correct dimensions of statistical tensor, with all zeroes
Definition at line 71 of file StatTensor.cc.
Referenced by StatTensor().
Get()
std::complex< double > GamR::AngDist::StatTensor::Get (double k, double q)
Definition at line 84 of file StatTensor.cc.
Referenced by ObservedProp(), Perturbation(), UnobservedProp(), and W().
GetBk()
std::complex< double > GamR::AngDist::StatTensor::GetBk (double k)
Get Bk value.
We are using the formalism in AES NIM A 485(2002)753, as opposed to Morinaga and Yamazaki here
Definition at line 105 of file StatTensor.cc.
Referenced by GamR::AngDist::W(), and GamR::AngDist::W().
ObservedProp()
StatTensor * GamR::AngDist::StatTensor::ObservedProp (double ji, double lambda, double lambdaPrime, double jf, double delta, SolidAttenuation * Qk, double theta, double phi)
Finds the statistical tensor for an observed transition
Equation 4 from AES NIM A 485(2002)753
Parameters
ji Initial spin
lambda Multipolarity 1 of the transition
lambdaPrime Multipolarity 2 of the transition
jf Final spin
delta Mixing ratio for multipolarities
Qk Solid attenuation coefficients for the detector
theta Polar angle of detector in radians
phi Azimuthal angle of detector in radians
Returns
Statistical tensor after the radiation has been osbserved
Definition at line 125 of file StatTensor.cc.
References StatTensor(), GamR::AngDist::Agen(), GamR::AngDist::BigD(), GamR::AngDist::SolidAttenuation::Get(), Get(), and Set().
Perturbation()
StatTensor * GamR::AngDist::StatTensor::Perturbation (std::function< std::complex< double >(double, double, double, double, double) > & Gk, double t)
Calculates the perturbation due to a time-dependent perturbation factor Gk
Equation 12 in AES NIM A 485(2002)753, pg 756
Parameters
Gk perturbation factor function, which takes argurments q, q', k, k', t
Returns
Statistical tensor after the perturbation for time t
Definition at line 206 of file StatTensor.cc.
References StatTensor(), Get(), and Set().
Print()
void GamR::AngDist::StatTensor::Print ()
Definition at line 281 of file StatTensor.cc.
Set() [1/2]
std::complex< double > GamR::AngDist::StatTensor::Set (double k, double q, std::complex< double > value)
Definition at line 91 of file StatTensor.cc.
Set() [2/2]
void GamR::AngDist::StatTensor::Set (std::vector< double > Pm)
Definition at line 45 of file StatTensor.cc.
Referenced by StatTensor(), StatTensor(), GamR::Coulex::CoulexCalculation::CalcTensor(), ObservedProp(), Perturbation(), and UnobservedProp().
UnobservedProp()
StatTensor * GamR::AngDist::StatTensor::UnobservedProp (double ji, double lambda, double lambdaPrime, double jf, double delta, SolidAttenuation * Qk)
Finds the statistical tensor for an unobserved transition
Like an observed propagation, but with only k = 0. See text in AES NIM A 485(2002)753, pg 756
Parameters
ji Initial spin
lambda Multipolarity 1 of the transition
lambdaPrime Multipolarity 2 of the transition
jf Final spin
delta Mixing ratio for multipolarities
Qk Solid attenuation coefficients for the detector
Returns
Statistical tensor after the radiation has been emitted but not observed
Definition at line 173 of file StatTensor.cc.
References StatTensor(), GamR::AngDist::Agen(), GamR::AngDist::SolidAttenuation::Get(), Get(), and Set().
W()
double GamR::AngDist::StatTensor::W (double ji, double lambda, double lambdaPrime, double jf, double delta, SolidAttenuation * Qk, double theta, double phi)
Calculates the angular distriubtion from a statistical tensor for any angle
Equation 10 in AES NIM A 485(2002)753
Parameters
ji Initial spin
lambda Multipolarity 1 of the transition
lambdaPrime Multipolarity 2 of the transition
jf Final spin
delta Mixing ratio for multipolarities
Qk Solid attenuation coefficients for the detector
theta Polar angle of detector in radians
phi Azimuthal angle of detector in radians
Returns
Angular distriubtion intensity at the detector position
Definition at line 254 of file StatTensor.cc.
References GamR::AngDist::Ak(), GamR::AngDist::BigD(), GamR::AngDist::SolidAttenuation::Get(), Get(), and W().
Referenced by W().
The documentation for this class was generated from the following files:
src/lib/angdist/StatTensor.hh
src/lib/angdist/StatTensor.cc