GamR: src/bin/gamrsort/gamrsort.cc File Reference
gamrsort.cc File Reference
#include <atomic>
#include <string>
#include <thread>
#include <vector>
#include <args/args.hxx>
#include <tree/Tree.hh>
#include <sort/CoincidenceCubeDiff.hh>
#include <sort/CoincidenceMatrix.hh>
#include <sort/CoincidenceMatrixPair.hh>
#include <sort/GatedTimeDifference.hh>
#include <sort/Matrix.hh>
#include <sort/Sorter.hh>
#include <sort/TimeDifference.hh>
#include <sort/TimeDifferencePairs.hh>
#include <sort/TimeWalkCal.hh>
#include <utils/REPL.hh>
Typedefs
using DCPDet1 = D3221_TDetector3
using DCPDet2 = D3221_TDetector2
using DCPDet3 = D3221_TDetector0
Functions
int main (const int argc, const char *argv[])
Typedef Documentation
DCPDet1
using DCPDet1 = D3221_TDetector3
Definition at line 23 of file gamrsort.cc.
DCPDet2
using DCPDet2 = D3221_TDetector2
Definition at line 24 of file gamrsort.cc.
DCPDet3
using DCPDet3 = D3221_TDetector0
Definition at line 25 of file gamrsort.cc.
Function Documentation
main()
int main (const int argc, const char * argv[])
Definition at line 27 of file gamrsort.cc.
References GamR::Sort::Sorter::Done(), GamR::Sort::Sorter::Halt(), GamR::Sort::Sorter::PrintStatus(), GamR::Sort::Sorter::Process(), GamR::Sort::Sorter::SetXsize(), GamR::Sort::Sorter::SetYsize(), GamR::Sort::Sorter::SetZsize(), and GamR::Sort::Sorter::Write().