GamR: GamR::AngDist::GaussianDistr Class Reference
GamR::AngDist::GaussianDistr Class Reference
#include <GaussianDistr.hh>
Classes
class GlobalChiSquare
Public Member Functions
GaussianDistr (double L, double H, std::vector< double > pars)
void Normalise ()
std::vector< double > GetBhfs ()
std::vector< double > GetRelAmps ()
void SetSamples (int i)
void SetLimit (int i)
void SetAmp (double a)
void SetG (double gfac)
void SetMean (double m)
void SetFWHM (double w)
void SetOffset (double o)
void SetHist (TH1 *hist)
void SetField ()
double GetG ()
double GetGErr ()
double GetAmp ()
double GetAmpErr ()
double GetMean ()
double GetMeanErr ()
double GetFWHM ()
double GetFWHMErr ()
double GetOffset ()
double GetOffsetErr ()
void FixField ()
void UnFixField ()
void FixG ()
void UnFixG ()
void FixAmp ()
void UnFixAmp ()
void FixOffset ()
void UnFixOffset ()
std::vector< double > GetPars ()
void SetPars ()
void SetPars (std::vector< double > pars)
double RatioFunc (double x, double a, double gfac, double off)
double operator() (double *x, double *p)
TF1 * GetFunc ()
void Fit (int quiet)
void Print ()
Public Attributes
double mean
double FWHM
double amp
double offset
double g
double Low
double High
TH1 * Hist
TF1 * FitFunc
int FixedField
Detailed Description
Definition at line 19 of file GaussianDistr.hh.
Constructor & Destructor Documentation
GaussianDistr()
GamR::AngDist::GaussianDistr::GaussianDistr (double L, double H, std::vector< double > pars) inline
Definition at line 49 of file GaussianDistr.hh.
References FixedField, and SetPars().
Member Function Documentation
Fit()
void GamR::AngDist::GaussianDistr::Fit (int quiet)
Definition at line 94 of file GaussianDistr.cc.
References FitFunc, FixedField, GetPars(), High, Low, GamR::AngDist::GaussianDistr::GlobalChiSquare::minuit(), SetField(), and SetPars().
FixAmp()
void GamR::AngDist::GaussianDistr::FixAmp () inline
Definition at line 90 of file GaussianDistr.hh.
FixField()
void GamR::AngDist::GaussianDistr::FixField () inline
Definition at line 86 of file GaussianDistr.hh.
References FixedField.
FixG()
void GamR::AngDist::GaussianDistr::FixG () inline
Definition at line 88 of file GaussianDistr.hh.
FixOffset()
void GamR::AngDist::GaussianDistr::FixOffset () inline
Definition at line 92 of file GaussianDistr.hh.
GetAmp()
double GamR::AngDist::GaussianDistr::GetAmp () inline
Definition at line 77 of file GaussianDistr.hh.
References amp.
Referenced by Print().
GetAmpErr()
double GamR::AngDist::GaussianDistr::GetAmpErr () inline
Definition at line 78 of file GaussianDistr.hh.
Referenced by Print().
GetBhfs()
std::vector< double > GamR::AngDist::GaussianDistr::GetBhfs () inline
Definition at line 61 of file GaussianDistr.hh.
GetFunc()
TF1 * GamR::AngDist::GaussianDistr::GetFunc ()
Definition at line 46 of file GaussianDistr.cc.
References amp, g, High, Low, and offset.
Referenced by GamR::AngDist::GaussianDistr::GlobalChiSquare::minuit().
GetFWHM()
double GamR::AngDist::GaussianDistr::GetFWHM () inline
Definition at line 81 of file GaussianDistr.hh.
References FWHM.
Referenced by Print().
GetFWHMErr()
double GamR::AngDist::GaussianDistr::GetFWHMErr () inline
Definition at line 82 of file GaussianDistr.hh.
Referenced by Print().
GetG()
double GamR::AngDist::GaussianDistr::GetG () inline
Definition at line 75 of file GaussianDistr.hh.
References g.
Referenced by Print().
GetGErr()
double GamR::AngDist::GaussianDistr::GetGErr () inline
Definition at line 76 of file GaussianDistr.hh.
Referenced by Print().
GetMean()
double GamR::AngDist::GaussianDistr::GetMean () inline
Definition at line 79 of file GaussianDistr.hh.
References mean.
Referenced by Print().
GetMeanErr()
double GamR::AngDist::GaussianDistr::GetMeanErr () inline
Definition at line 80 of file GaussianDistr.hh.
Referenced by Print().
GetOffset()
double GamR::AngDist::GaussianDistr::GetOffset () inline
Definition at line 83 of file GaussianDistr.hh.
References offset.
Referenced by Print().
GetOffsetErr()
double GamR::AngDist::GaussianDistr::GetOffsetErr () inline
Definition at line 84 of file GaussianDistr.hh.
Referenced by Print().
GetPars()
std::vector< double > GamR::AngDist::GaussianDistr::GetPars () inline
Definition at line 94 of file GaussianDistr.hh.
Referenced by Fit().
GetRelAmps()
std::vector< double > GamR::AngDist::GaussianDistr::GetRelAmps () inline
Definition at line 62 of file GaussianDistr.hh.
Normalise()
void GamR::AngDist::GaussianDistr::Normalise ()
Definition at line 23 of file GaussianDistr.cc.
Referenced by SetField().
operator()()
double GamR::AngDist::GaussianDistr::operator() (double * x, double * p)
Definition at line 42 of file GaussianDistr.cc.
References RatioFunc().
Print()
void GamR::AngDist::GaussianDistr::Print () inline
Definition at line 104 of file GaussianDistr.hh.
References GetAmp(), GetAmpErr(), GetFWHM(), GetFWHMErr(), GetG(), GetGErr(), GetMean(), GetMeanErr(), GetOffset(), GetOffsetErr(), and GamR::Utils::wrresult().
RatioFunc()
double GamR::AngDist::GaussianDistr::RatioFunc (double x, double a, double gfac, double off)
Definition at line 33 of file GaussianDistr.cc.
Referenced by operator()().
SetAmp()
void GamR::AngDist::GaussianDistr::SetAmp (double a) inline
Definition at line 66 of file GaussianDistr.hh.
References amp.
Referenced by GamR::AngDist::GaussianDistr::GlobalChiSquare::minuit().
SetField()
void GamR::AngDist::GaussianDistr::SetField ()
Definition at line 9 of file GaussianDistr.cc.
References FWHM, mean, and Normalise().
Referenced by Fit(), and GamR::AngDist::GaussianDistr::GlobalChiSquare::minuit().
SetFWHM()
void GamR::AngDist::GaussianDistr::SetFWHM (double w) inline
Definition at line 69 of file GaussianDistr.hh.
References FWHM.
Referenced by GamR::AngDist::GaussianDistr::GlobalChiSquare::minuit().
SetG()
void GamR::AngDist::GaussianDistr::SetG (double gfac) inline
Definition at line 67 of file GaussianDistr.hh.
References g.
Referenced by GamR::AngDist::GaussianDistr::GlobalChiSquare::minuit().
SetHist()
void GamR::AngDist::GaussianDistr::SetHist (TH1 * hist) inline
Definition at line 71 of file GaussianDistr.hh.
References Hist.
SetLimit()
void GamR::AngDist::GaussianDistr::SetLimit (int i) inline
Definition at line 64 of file GaussianDistr.hh.
SetMean()
void GamR::AngDist::GaussianDistr::SetMean (double m) inline
Definition at line 68 of file GaussianDistr.hh.
References mean.
Referenced by GamR::AngDist::GaussianDistr::GlobalChiSquare::minuit().
SetOffset()
void GamR::AngDist::GaussianDistr::SetOffset (double o) inline
Definition at line 70 of file GaussianDistr.hh.
References offset.
Referenced by GamR::AngDist::GaussianDistr::GlobalChiSquare::minuit().
SetPars() [1/2]
void GamR::AngDist::GaussianDistr::SetPars () inline
Definition at line 95 of file GaussianDistr.hh.
References SetPars().
Referenced by GaussianDistr(), Fit(), and SetPars().
SetPars() [2/2]
void GamR::AngDist::GaussianDistr::SetPars (std::vector< double > pars) inline
Definition at line 96 of file GaussianDistr.hh.
References amp, FWHM, g, mean, and offset.
SetSamples()
void GamR::AngDist::GaussianDistr::SetSamples (int i) inline
Definition at line 63 of file GaussianDistr.hh.
UnFixAmp()
void GamR::AngDist::GaussianDistr::UnFixAmp () inline
Definition at line 91 of file GaussianDistr.hh.
UnFixField()
void GamR::AngDist::GaussianDistr::UnFixField () inline
Definition at line 87 of file GaussianDistr.hh.
References FixedField.
UnFixG()
void GamR::AngDist::GaussianDistr::UnFixG () inline
Definition at line 89 of file GaussianDistr.hh.
UnFixOffset()
void GamR::AngDist::GaussianDistr::UnFixOffset () inline
Definition at line 93 of file GaussianDistr.hh.
Member Data Documentation
amp
double GamR::AngDist::GaussianDistr::amp
Definition at line 37 of file GaussianDistr.hh.
Referenced by GetAmp(), GetFunc(), SetAmp(), and SetPars().
FitFunc
TF1* GamR::AngDist::GaussianDistr::FitFunc
Definition at line 45 of file GaussianDistr.hh.
Referenced by Fit(), and GamR::AngDist::GaussianDistr::GlobalChiSquare::minuit().
FixedField
int GamR::AngDist::GaussianDistr::FixedField
Definition at line 47 of file GaussianDistr.hh.
Referenced by GaussianDistr(), Fit(), FixField(), GamR::AngDist::GaussianDistr::GlobalChiSquare::minuit(), and UnFixField().
FWHM
double GamR::AngDist::GaussianDistr::FWHM
Definition at line 36 of file GaussianDistr.hh.
Referenced by GetFWHM(), SetField(), SetFWHM(), and SetPars().
g
double GamR::AngDist::GaussianDistr::g
Definition at line 39 of file GaussianDistr.hh.
Referenced by GetFunc(), GetG(), SetG(), and SetPars().
High
double GamR::AngDist::GaussianDistr::High
Definition at line 42 of file GaussianDistr.hh.
Referenced by Fit(), and GetFunc().
Hist
TH1* GamR::AngDist::GaussianDistr::Hist
Definition at line 44 of file GaussianDistr.hh.
Referenced by GamR::AngDist::GaussianDistr::GlobalChiSquare::minuit(), and SetHist().
Low
double GamR::AngDist::GaussianDistr::Low
Definition at line 41 of file GaussianDistr.hh.
Referenced by Fit(), and GetFunc().
mean
double GamR::AngDist::GaussianDistr::mean
Definition at line 35 of file GaussianDistr.hh.
Referenced by GetMean(), SetField(), SetMean(), and SetPars().
offset
double GamR::AngDist::GaussianDistr::offset
Definition at line 38 of file GaussianDistr.hh.
Referenced by GetFunc(), GetOffset(), SetOffset(), and SetPars().
The documentation for this class was generated from the following files:
src/lib/angdist/GaussianDistr.hh
src/lib/angdist/GaussianDistr.cc