GamR: GamR::AngDist::AngCorr Class Reference
GamR::AngDist::AngCorr Class Reference
#include <AngCorr.hh>
Public Member Functions
AngCorr (double spin1, double spin2, double spin3)
AngCorr (double spin1, double spin2, double spin3, GamR::AngDist::SolidAttenuation *Q)
double Ak (double k, double delta1, double delta2)
double operator() (double *x, double *p)
int Mixed (double s1, double s2)
int Mixed (int i)
int Mixed1 ()
int Mixed2 ()
Public Attributes
double spin1
double spin2
double spin3
GamR::AngDist::SolidAttenuation * Qk
Detailed Description
Definition at line 30 of file AngCorr.hh.
Constructor & Destructor Documentation
AngCorr() [1/2]
GamR::AngDist::AngCorr::AngCorr (double spin1, double spin2, double spin3) inline
Constructor for AngCorr object
Parameters
spin1 Initial spin
spin2 Intermediate spin
spin3 Final spin
Definition at line 47 of file AngCorr.hh.
References spin1, spin2, and spin3.
AngCorr() [2/2]
GamR::AngDist::AngCorr::AngCorr (double spin1, double spin2, double spin3, GamR::AngDist::SolidAttenuation * Q) inline
Definition at line 55 of file AngCorr.hh.
References spin1, spin2, and spin3.
Member Function Documentation
Ak()
double GamR::AngDist::AngCorr::Ak (double k, double delta1, double delta2)
Calculates the appropriate Ak coefficient, using either Fk coefficients for pure transitions or Ak coefficients for mixed transitions (mixing the lowest two allowed multipolarities)
Parameters
k Order of coefficient
delta1 Mixing ratio of first transition, ignored if transition is pure
delta2 Mixing ratio of second transition, ignored if transition is pure
Returns
Ak coefficient
Definition at line 17 of file AngCorr.cc.
References GamR::AngDist::Ak(), GamR::AngDist::Fk(), spin1, spin2, and spin3.
Referenced by operator()().
Mixed() [1/2]
int GamR::AngDist::AngCorr::Mixed (double s1, double s2)
Definition at line 68 of file AngCorr.cc.
Referenced by GamR::AngDist::AngCorrFit::Fit(), Mixed1(), and Mixed2().
Mixed() [2/2]
int GamR::AngDist::AngCorr::Mixed (int i)
Definition at line 86 of file AngCorr.cc.
References Mixed1(), and Mixed2().
Mixed1()
int GamR::AngDist::AngCorr::Mixed1 () inline
Definition at line 72 of file AngCorr.hh.
References Mixed(), spin1, and spin2.
Referenced by GamR::AngDist::AngCorrFit::Fit(), and Mixed().
Mixed2()
int GamR::AngDist::AngCorr::Mixed2 () inline
Definition at line 73 of file AngCorr.hh.
References Mixed(), spin2, and spin3.
Referenced by GamR::AngDist::AngCorrFit::Fit(), and Mixed().
operator()()
double GamR::AngDist::AngCorr::operator() (double * x, double * p) inline
Definition at line 63 of file AngCorr.hh.
References Ak(), and Qk.
Member Data Documentation
Qk
GamR::AngDist::SolidAttenuation* GamR::AngDist::AngCorr::Qk
Definition at line 39 of file AngCorr.hh.
Referenced by operator()().
spin1
double GamR::AngDist::AngCorr::spin1
This is a wrapper for Fk and Ak coefficients for use in angular correlations for a cascade between 3 states. It's designed to be used to construct TF1 objects which can then be plotted, and fitted
Definition at line 35 of file AngCorr.hh.
Referenced by AngCorr(), AngCorr(), Ak(), and Mixed1().
spin2
double GamR::AngDist::AngCorr::spin2
Definition at line 36 of file AngCorr.hh.
Referenced by AngCorr(), AngCorr(), Ak(), Mixed1(), and Mixed2().
spin3
double GamR::AngDist::AngCorr::spin3
Definition at line 37 of file AngCorr.hh.
Referenced by AngCorr(), AngCorr(), Ak(), and Mixed2().
The documentation for this class was generated from the following files:
src/lib/angdist/AngCorr.hh
src/lib/angdist/AngCorr.cc