GamR: GamR::Sort::Type::TimeDifferencePairs< Det, E, T > Class Template Reference
GamR::Sort::Type::TimeDifferencePairs< Det, E, T > Class Template Reference
#include <TimeDifferencePairs.hh>
Public Member Functions
TimeDifferencePairs (Sorter *parent, std::vector< std::string > opts)
void operator() (TTreeReader &R)
Detailed Description
template<class Det, size_t E, size_t T>
class GamR::Sort::Type::TimeDifferencePairs< Det, E, T >
Definition at line 23 of file TimeDifferencePairs.hh.
Constructor & Destructor Documentation
TimeDifferencePairs()
template<class Det , size_t E, size_t T> GamR::Sort::Type::TimeDifferencePairs< Det, E, T >::TimeDifferencePairs (Sorter * parent, std::vector< std::string > opts) inline
Definition at line 35 of file TimeDifferencePairs.hh.
References GamR::Sort::Sorter::GetMatrix(), ss(), and GamR::Sort::Sorter::WriteObject().
Member Function Documentation
operator()()
template<class Det , size_t E, size_t T> void GamR::Sort::Type::TimeDifferencePairs< Det, E, T >::operator() (TTreeReader & R) inline
Definition at line 103 of file TimeDifferencePairs.hh.
References GamR::Sort::Sorter::Done(), and GamR::Sort::Sorter::Tick().
The documentation for this class was generated from the following file:
src/lib/sort/TimeDifferencePairs.hh