GamR: GamR::Tree::TDetDefn< Ts > Class Template Reference
GamR::Tree::TDetDefn< Ts > Class Template Reference
#include <DetDefn.hh>
Classes
struct CalFunctor
struct DereferencePointers
struct InterpretPointers
struct UpdateGoodness
Public Member Functions
TDetDefn (std::string t="", int id=-1, std::string n="", int I=50000)
~TDetDefn ()
template<int N>
auto GetDatum (ULong64_t eventNum) -> decltype(std::get< N >(fDatum)) &
auto GetAllDatums (ULong64_t eventNum) -> decltype(fDatum) &
size_t GetNumMeasurements () const
Int_t GetID ()
Double_t GetEfficiency ()
Bool_t IsGood ()
void SetPtrs (std::map< std::string, void * > &branchmap, std::string branches)
void SetRequired (Int_t n)
void SetCalFuncs (std::string funcstrs)
void SetPollGates (std::string pollstrs)
void SetEffFunc (std::string function)
void Calibrate (ULong64_t eventNum=0)
ClassDef (TDetDefn, 1)
Detailed Description
template<class... Ts>
class GamR::Tree::TDetDefn< Ts >
Definition at line 24 of file DetDefn.hh.
Constructor & Destructor Documentation
TDetDefn()
template<class... Ts> GamR::Tree::TDetDefn< Ts >::TDetDefn (std::string t = "", int id = -1, std::string n = "", int I = 50000) inline
Definition at line 56 of file DetDefn.hh.
~TDetDefn()
template<class... Ts> GamR::Tree::TDetDefn< Ts >::~TDetDefn () inline
Definition at line 65 of file DetDefn.hh.
Member Function Documentation
Calibrate()
template<class... Ts> void GamR::Tree::TDetDefn< Ts >::Calibrate (ULong64_t eventNum = 0)
Definition at line 277 of file DetDefn.tt.
References GamR::Utils::for_both_in_tuple().
Referenced by GamR::Tree::TDetDefn< Ts >::GetAllDatums(), and GamR::Tree::TDetDefn< Ts >::GetDatum().
ClassDef()
template<class... Ts> GamR::Tree::TDetDefn< Ts >::ClassDef (TDetDefn< Ts > , 1)
GetAllDatums()
template<class... Ts> auto GamR::Tree::TDetDefn< Ts >::GetAllDatums (ULong64_t eventNum) -> decltype(fDatum) & inline
Definition at line 77 of file DetDefn.hh.
References GamR::Tree::TDetDefn< Ts >::Calibrate().
Referenced by GamR::Tree::TDetector< Ts >::TDetector().
GetDatum()
template<class... Ts> template<int N> auto GamR::Tree::TDetDefn< Ts >::GetDatum (ULong64_t eventNum) -> decltype(std::get<N>(fDatum)) & inline
Definition at line 72 of file DetDefn.hh.
References GamR::Tree::TDetDefn< Ts >::Calibrate().
GetEfficiency()
template<class... Ts> Double_t GamR::Tree::TDetDefn< Ts >::GetEfficiency () inline
Definition at line 85 of file DetDefn.hh.
Referenced by GamR::Tree::TDetector< Ts >::TDetector().
GetID()
template<class... Ts> Int_t GamR::Tree::TDetDefn< Ts >::GetID () inline
Definition at line 84 of file DetDefn.hh.
Referenced by GamR::Tree::TDetector< Ts >::TDetector().
GetNumMeasurements()
template<class... Ts> size_t GamR::Tree::TDetDefn< Ts >::GetNumMeasurements () const inline
Definition at line 82 of file DetDefn.hh.
IsGood()
template<class... Ts> Bool_t GamR::Tree::TDetDefn< Ts >::IsGood
Definition at line 171 of file DetDefn.tt.
References GamR::Utils::for_both_in_tuple().
SetCalFuncs()
template<class... Ts> void GamR::Tree::TDetDefn< Ts >::SetCalFuncs (std::string funcstrs)
Definition at line 210 of file DetDefn.tt.
References ss().
SetEffFunc()
template<class... Ts> void GamR::Tree::TDetDefn< Ts >::SetEffFunc (std::string function)
Definition at line 268 of file DetDefn.tt.
References ss().
SetPollGates()
template<class... Ts> void GamR::Tree::TDetDefn< Ts >::SetPollGates (std::string pollstrs)
Definition at line 237 of file DetDefn.tt.
References ss().
SetPtrs()
template<class... Ts> void GamR::Tree::TDetDefn< Ts >::SetPtrs (std::map< std::string, void * > & branchmap, std::string branches)
Definition at line 180 of file DetDefn.tt.
References GamR::Utils::for_each_in_tuple(), and ss().
SetRequired()
template<class... Ts> void GamR::Tree::TDetDefn< Ts >::SetRequired (Int_t n) inline
Definition at line 89 of file DetDefn.hh.
The documentation for this class was generated from the following files:
src/lib/tree/DetDefn.hh
src/lib/tree/DetDefn.tt