GamR: src/lib/abbrevs/Abbreviations.hh File Reference
Abbreviations.hh File Reference
#include <TH1.h>
#include <TCanvas.h>
#include <spect/Integral.hh>
#include <spect/Cut.hh>
#include <spect/Fit.hh>
#include <spect/Display.hh>
#include <spect/Transform.hh>
#include <spect/Calibrate.hh>
#include <toolkit/Gate.hh>
#include <toolkit/Peak.hh>
Functions
void help (std::string topic="")
TH1D * gx (TCanvas *canvas=gPad->GetCanvas())
TH1D * gy (TCanvas *canvas=gPad->GetCanvas())
TH1D * bsx (TCanvas *canvas=gPad->GetCanvas())
TH1D * bsy (TCanvas *canvas=gPad->GetCanvas())
TH1D * bsx (TCanvas *canvas, const char *name)
TH1D * bsy (TCanvas *canvas, const char *name)
void pfprint ()
void pfconf ()
void pfsave ()
void pfsave (std::string filename)
GamR::Spect::PeakFit * pf (TCanvas *canvas=gPad->GetCanvas(), Option_t *foption="", Option_t *option="")
GamR::TK::BPeak * bp (TCanvas *canvas=gPad->GetCanvas(), Option_t *foption="", Option_t *option="sl")
GamR::TK::BPeak * cbp (TCanvas *canvas=gPad->GetCanvas())
std::pair< double, double > ig (TCanvas *canvas=gPad->GetCanvas())
std::pair< double, double > igbs (TCanvas *canvas=gPad->GetCanvas())
std::pair< double, double > ct (TCanvas *canvas=gPad->GetCanvas())
std::pair< double, double > ctbs (TCanvas *canvas=gPad->GetCanvas())
TSpectrum * fp (TCanvas *canvas=gPad->GetCanvas(), double sigma=2, Option_t *option="", double threshold=0.05)
void ls ()
void sp (int i, Option_t *option="hist")
void px (TVirtualPad *canvas=gPad->GetCanvas())
void py (TVirtualPad *canvas=gPad->GetCanvas())
void os (std::vector< int > indexes, TCanvas *canvas=NULL, Option_t *option="hist")
void os (std::vector< TH1 * > hists, TCanvas *canvas=NULL, Option_t *option="hist")
void os (int iStart, int iStop, TCanvas *canvas=NULL, Option_t *option="hist")
void os (TH2 *hist, int iStart, int iStop)
void os (TH2 *hist, std::vector< int > indices)
void os (int i2D, int iStart, int iStop)
void os (std::vector< std::string > files, std::string name, int iX, Option_t *option="hist")
void os (std::vector< std::string > files, std::string name, Option_t *option="hist")
void ss (std::vector< int > indexes, TCanvas *canvas=NULL, Option_t *option="hist")
void ss (std::vector< TH1 * > hists, TCanvas *canvas=NULL, Option_t *option="hist")
void ss (int iStart, int iStop, TCanvas *canvas=NULL, Option_t *option="hist")
void ss (TH2 *hist, int iStart, int iStop)
void ss (int i2D, int iStart, int iStop)
void ss (std::vector< std::string > files, std::string name, int iX, Option_t *option="hist")
void ss (std::vector< std::string > files, std::string name, Option_t *option="hist")
void lin (TVirtualPad *canvas=NULL)
void log (TVirtualPad *canvas=NULL)
void zx (double low, double high, TVirtualPad *canvas=NULL)
void zy (double low, double high, TVirtualPad *canvas=NULL)
void uzx (TVirtualPad *canvas=NULL)
void uzy (TVirtualPad *canvas=NULL)
void uz (TVirtualPad *canvas=NULL)
std::pair< double, double > ca (TVirtualPad *canvas=NULL, double sigma=2)
std::pair< double, double > ca (TH1 *hist, double lowEst, double highEst, double lowEn, double highEn, double sigma)
TH1 * add (std::vector< TH1 * > hists, const char *name="sum")
TH1 * add (std::vector< int > hists, const char *name="sum")
TH1 * add (int iStart, int iStop, const char *name="sum")
TH1 * rb (TH1 *hist, int rebin)
void rb (TVirtualPad *canvas=NULL, int rebin=2)
void ns (TVirtualPad *canvas=NULL, Option_t *option="")
void nsbs (TVirtualPad *canvas=NULL)
void rn (TVirtualPad *canvas=NULL)
void ls2 ()
void sp2 (int i, Option_t *option="colz2")
TH2 * add2 (std::vector< TH2 * > hists, const char *name="sum")
TH2 * add2 (std::vector< int > hists, const char *name="sum")
TH2 * add2 (int iStart, int iStop, const char *name="sum")
Function Documentation
add() [1/3]
TH1 * add (int iStart, int iStop, const char * name = "sum")
Definition at line 162 of file Abbreviations.cc.
References GamR::Spect::Add().
add() [2/3]
TH1 * add (std::vector< int > hists, const char * name = "sum")
Definition at line 161 of file Abbreviations.cc.
References GamR::Spect::Add().
add() [3/3]
TH1 * add (std::vector< TH1 * > hists, const char * name = "sum")
Definition at line 160 of file Abbreviations.cc.
References GamR::Spect::Add().
add2() [1/3]
TH2 * add2 (int iStart, int iStop, const char * name = "sum")
Definition at line 174 of file Abbreviations.cc.
References GamR::Spect::Add2().
add2() [2/3]
TH2 * add2 (std::vector< int > hists, const char * name = "sum")
Definition at line 173 of file Abbreviations.cc.
References GamR::Spect::Add2().
add2() [3/3]
TH2 * add2 (std::vector< TH2 * > hists, const char * name = "sum")
Definition at line 172 of file Abbreviations.cc.
References GamR::Spect::Add().
bp()
GamR::TK::BPeak * bp (TCanvas * canvas = gPad->GetCanvas(), Option_t * foption = "", Option_t * option = "sl")
Definition at line 116 of file Abbreviations.cc.
References GamR::TK::FitBPeak().
Referenced by GamR::Processor::TimeWalk::MakeGraphs().
bsx() [1/2]
TH1D * bsx (TCanvas * canvas, const char * name)
Definition at line 105 of file Abbreviations.cc.
References GamR::Spect::BackgroundSubtractX().
bsx() [2/2]
TH1D * bsx (TCanvas * canvas = gPad->GetCanvas())
Definition at line 103 of file Abbreviations.cc.
References GamR::Spect::BackgroundSubtractX().
bsy() [1/2]
TH1D * bsy (TCanvas * canvas, const char * name)
Definition at line 106 of file Abbreviations.cc.
References GamR::Spect::BackgroundSubtractY().
bsy() [2/2]
TH1D * bsy (TCanvas * canvas = gPad->GetCanvas())
Definition at line 104 of file Abbreviations.cc.
References GamR::Spect::BackgroundSubtractY().
ca() [1/2]
std::pair< double, double > ca (TH1 * hist, double lowEst, double highEst, double lowEn, double highEn, double sigma)
Definition at line 159 of file Abbreviations.cc.
References GamR::Spect::TwoPointCalibrate().
ca() [2/2]
std::pair< double, double > ca (TVirtualPad * canvas = NULL, double sigma = 2)
Definition at line 158 of file Abbreviations.cc.
References GamR::Spect::TwoPointCalibrate().
cbp()
GamR::TK::BPeak * cbp (TCanvas * canvas = gPad->GetCanvas())
Definition at line 117 of file Abbreviations.cc.
References GamR::TK::ClickBPeak().
ct()
std::pair< double, double > ct (TCanvas * canvas = gPad->GetCanvas())
Definition at line 122 of file Abbreviations.cc.
References GamR::Spect::Counts().
ctbs()
std::pair< double, double > ctbs (TCanvas * canvas = gPad->GetCanvas())
Definition at line 123 of file Abbreviations.cc.
References GamR::Spect::CountsBS().
fp()
TSpectrum * fp (TCanvas * canvas = gPad->GetCanvas(), double sigma = 2, Option_t * option = "", double threshold = 0.05)
Definition at line 125 of file Abbreviations.cc.
References GamR::Spect::FindPeaks().
Referenced by GamR::Spect::FromBin(), GamR::Spect::FromBin(), and main().
gx()
TH1D * gx (TCanvas * canvas = gPad->GetCanvas())
Definition at line 101 of file Abbreviations.cc.
References GamR::Spect::GateX().
gy()
TH1D * gy (TCanvas * canvas = gPad->GetCanvas())
Definition at line 102 of file Abbreviations.cc.
References GamR::Spect::GateY().
help()
void help (std::string topic = "")
Definition at line 6 of file Abbreviations.cc.
Referenced by main(), and main().
ig()
std::pair< double, double > ig (TCanvas * canvas = gPad->GetCanvas())
Definition at line 119 of file Abbreviations.cc.
References GamR::Spect::Integral().
Referenced by GamR::AngDist::AngCorrFit::Fit().
igbs()
std::pair< double, double > igbs (TCanvas * canvas = gPad->GetCanvas())
Definition at line 120 of file Abbreviations.cc.
References GamR::Spect::IntegralBS().
lin()
void lin (TVirtualPad * canvas = NULL)
Definition at line 151 of file Abbreviations.cc.
References GamR::Spect::LinAll().
log()
void log (TVirtualPad * canvas = NULL)
Definition at line 152 of file Abbreviations.cc.
References GamR::Spect::LogAll().
Referenced by GamR::Efficiency::EffCFunc().
ls()
void ls ()
Definition at line 132 of file Abbreviations.cc.
References GamR::Spect::List1DSpectra().
Referenced by GamR::TK::Gate::Browse(), and GamR::TK::GateMap::Browse().
ls2()
void ls2 ()
Definition at line 170 of file Abbreviations.cc.
References GamR::Spect::List2DSpectra().
ns()
void ns (TVirtualPad * canvas = NULL, Option_t * option = "")
Definition at line 165 of file Abbreviations.cc.
References GamR::Spect::NormSpectra().
nsbs()
void nsbs (TVirtualPad * canvas = NULL)
Definition at line 166 of file Abbreviations.cc.
References GamR::Spect::NormSpectraBackSub().
os() [1/8]
void os (int i2D, int iStart, int iStop)
Definition at line 141 of file Abbreviations.cc.
References GamR::Spect::OverlaySpectra().
os() [2/8]
void os (int iStart, int iStop, TCanvas * canvas = NULL, Option_t * option = "hist")
Definition at line 138 of file Abbreviations.cc.
References GamR::Spect::OverlaySpectra().
os() [3/8]
void os (std::vector< int > indexes, TCanvas * canvas = NULL, Option_t * option = "hist")
Definition at line 136 of file Abbreviations.cc.
References GamR::Spect::OverlaySpectra().
Referenced by GamR::TK::operator<<().
os() [4/8]
void os (std::vector< std::string > files, std::string name, int iX, Option_t * option = "hist")
Definition at line 142 of file Abbreviations.cc.
References GamR::Spect::OverlaySpectra().
os() [5/8]
void os (std::vector< std::string > files, std::string name, Option_t * option = "hist")
Definition at line 143 of file Abbreviations.cc.
References GamR::Spect::OverlaySpectra().
os() [6/8]
void os (std::vector< TH1 * > hists, TCanvas * canvas = NULL, Option_t * option = "hist")
Definition at line 137 of file Abbreviations.cc.
References GamR::Spect::OverlaySpectra().
os() [7/8]
void os (TH2 * hist, int iStart, int iStop)
Definition at line 139 of file Abbreviations.cc.
References GamR::Spect::OverlaySpectra().
os() [8/8]
void os (TH2 * hist, std::vector< int > indices)
Definition at line 140 of file Abbreviations.cc.
References GamR::Spect::OverlaySpectra().
pf()
GamR::Spect::PeakFit * pf (TCanvas * canvas = gPad->GetCanvas(), Option_t * foption = "", Option_t * option = "")
Definition at line 115 of file Abbreviations.cc.
References GamR::Spect::FitPeaks().
pfconf()
void pfconf ()
Definition at line 112 of file Abbreviations.cc.
References GamR::Spect::gFitGuesses, and GamR::Spect::PeakFitGuesses::Set().
pfprint()
void pfprint ()
Definition at line 111 of file Abbreviations.cc.
References GamR::Spect::gFitGuesses, and GamR::Spect::PeakFitGuesses::Print().
pfsave() [1/2]
void pfsave ()
Definition at line 113 of file Abbreviations.cc.
References GamR::Spect::gFitGuesses, and GamR::Spect::PeakFitGuesses::Save().
pfsave() [2/2]
void pfsave (std::string filename)
Definition at line 114 of file Abbreviations.cc.
References GamR::Spect::gFitGuesses, and GamR::Spect::PeakFitGuesses::Save().
px()
void px (TVirtualPad * canvas = gPad->GetCanvas())
Definition at line 134 of file Abbreviations.cc.
References GamR::Spect::ProjX().
Referenced by GamR::Nucleus::LevelSchemeDraw::State::DistancetoPrimitive(), GamR::Nucleus::LevelSchemeDraw::Transition::DistancetoPrimitive(), GamR::Nucleus::LevelSchemeFitter::State::DistancetoPrimitive(), GamR::Nucleus::LevelSchemeFitter::Transition::DistancetoPrimitive(), GamR::TK::Gate::DistancetoPrimitive(), GamR::Nucleus::LevelSchemeDraw::State::ExecuteEvent(), GamR::Nucleus::LevelSchemeDraw::Transition::ExecuteEvent(), GamR::Nucleus::LevelSchemeFitter::State::ExecuteEvent(), GamR::Nucleus::LevelSchemeFitter::Transition::ExecuteEvent(), and GamR::TK::Gate::ExecuteEvent().
py()
void py (TVirtualPad * canvas = gPad->GetCanvas())
Definition at line 135 of file Abbreviations.cc.
References GamR::Spect::ProjY().
Referenced by GamR::Nucleus::LevelSchemeDraw::State::DistancetoPrimitive(), GamR::Nucleus::LevelSchemeDraw::Transition::DistancetoPrimitive(), GamR::Nucleus::LevelSchemeFitter::State::DistancetoPrimitive(), GamR::Nucleus::LevelSchemeFitter::Transition::DistancetoPrimitive(), GamR::TK::Gate::DistancetoPrimitive(), GamR::Nucleus::LevelSchemeDraw::State::ExecuteEvent(), GamR::Nucleus::LevelSchemeDraw::Transition::ExecuteEvent(), GamR::Nucleus::LevelSchemeFitter::State::ExecuteEvent(), GamR::Nucleus::LevelSchemeFitter::Transition::ExecuteEvent(), and GamR::TK::Gate::ExecuteEvent().
rb() [1/2]
TH1 * rb (TH1 * hist, int rebin)
Definition at line 163 of file Abbreviations.cc.
References GamR::Spect::Rebin().
rb() [2/2]
void rb (TVirtualPad * canvas = NULL, int rebin = 2)
Definition at line 164 of file Abbreviations.cc.
References GamR::Spect::Rebin().
rn()
void rn (TVirtualPad * canvas = NULL)
Definition at line 167 of file Abbreviations.cc.
References GamR::Spect::Rename().
sp()
void sp (int i, Option_t * option = "hist")
Definition at line 133 of file Abbreviations.cc.
References GamR::Spect::Draw().
Referenced by GamR::Coulex::CoulexCalculation::SetLevelScheme().
sp2()
void sp2 (int i, Option_t * option = "colz2")
Definition at line 171 of file Abbreviations.cc.
References GamR::Spect::Draw2D().
ss() [1/7]
void ss (int i2D, int iStart, int iStop)
Definition at line 150 of file Abbreviations.cc.
References GamR::Spect::StackSpectra().
ss() [2/7]
void ss (int iStart, int iStop, TCanvas * canvas = NULL, Option_t * option = "hist")
Definition at line 146 of file Abbreviations.cc.
References GamR::Spect::StackSpectra().
ss() [3/7]
void ss (std::vector< int > indexes, TCanvas * canvas = NULL, Option_t * option = "hist")
Definition at line 144 of file Abbreviations.cc.
References GamR::Spect::StackSpectra().
Referenced by GamR::Sort::Type::GatedTimeDifference< DetGate, S, DetTime, E, T >::GatedTimeDifference(), GamR::Sort::Type::Matrix::Matrix(), GamR::Sort::Type::TimeDifference< Det, E, T >::TimeDifference(), GamR::Sort::Type::TimeDifferencePairs< Det, E, T >::TimeDifferencePairs(), GamR::Sort::Type::TimeWalkCal< Det, E, T >::TimeWalkCal(), GamR::Spect::CutFromText(), GamR::Processor::TimeWalk::Draw(), GamR::Processor::TimeWalk::Fit(), GamR::Spect::PeakFit::Fit(), GamR::Spect::FitPeaks(), GamR::Spect::FromText(), GamR::TK::GainMatchEnergy(), GamR::ORNL::his2root(), GamR::Tree::TExpDefn< ADefns >::Load(), GamR::Tree::TExpDefn< ADefns >::LoadRaw(), main(), GamR::Processor::TimeWalk::MakeGraphs(), GamR::Tree::TExpDefn< ADefns >::FillDetDefns::operator()(), GamR::ORNL::readAllBananas(), GamR::ORNL::readBanana(), GamR::Bateman::Scheme::ReadScheme(), GamR::Nucleus::LevelSchemeDraw::Scheme::ReadScheme(), GamR::Tree::TDetDefn< Ts >::SetCalFuncs(), GamR::Tree::TDetDefn< Ts >::SetEffFunc(), GamR::Tree::TDetDefn< Ts >::SetPollGates(), GamR::Tree::TDetDefn< Ts >::SetPtrs(), GamR::Spect::ToText(), GamR::Spect::ToText(), GamR::Spect::ToText(), GamR::Spect::ToText(), GamR::Spect::ToText(), and GamR::Spect::ToText().
ss() [4/7]
void ss (std::vector< std::string > files, std::string name, int iX, Option_t * option = "hist")
Definition at line 147 of file Abbreviations.cc.
References GamR::Spect::StackSpectra().
ss() [5/7]
void ss (std::vector< std::string > files, std::string name, Option_t * option = "hist")
Definition at line 148 of file Abbreviations.cc.
References GamR::Spect::StackSpectra().
ss() [6/7]
void ss (std::vector< TH1 * > hists, TCanvas * canvas = NULL, Option_t * option = "hist")
Definition at line 145 of file Abbreviations.cc.
References GamR::Spect::StackSpectra().
ss() [7/7]
void ss (TH2 * hist, int iStart, int iStop)
Definition at line 149 of file Abbreviations.cc.
References GamR::Spect::StackSpectra().
uz()
void uz (TVirtualPad * canvas = NULL)
Definition at line 157 of file Abbreviations.cc.
References GamR::Spect::UnZoomAllX(), and GamR::Spect::UnZoomAllY().
uzx()
void uzx (TVirtualPad * canvas = NULL)
Definition at line 155 of file Abbreviations.cc.
References GamR::Spect::UnZoomAllX().
uzy()
void uzy (TVirtualPad * canvas = NULL)
Definition at line 156 of file Abbreviations.cc.
References GamR::Spect::UnZoomAllY().
zx()
void zx (double low, double high, TVirtualPad * canvas = NULL)
Definition at line 153 of file Abbreviations.cc.
References GamR::Spect::ZoomAllX().
zy()
void zy (double low, double high, TVirtualPad * canvas = NULL)
Definition at line 154 of file Abbreviations.cc.
References GamR::Spect::ZoomAllY().