GamR: GamR::Efficiency::DataSet Class Reference
GamR::Efficiency::DataSet Class Reference
#include <Efficiency.hh>
Public Member Functions
DataSet ()
DataSet (const char *effFile)
DataSet (const char *histFile, const char *histName, const char *gateFile, const char *mapName, const char *intensityFile)
DataSet (TH1D *fHist, GamR::Nucleus::TransitionMap *fTransitionMap, std::map< std::string, std::pair< double, double > > fIntensityMap)
DataSet (std::string areaFile, const char *intensityFile)
void SetData (const char *effFile)
void SetData (TH1D *fHist, GamR::Nucleus::TransitionMap *fTransitionMap, std::map< std::string, std::pair< double, double > > fIntensityMap)
void SetData (std::string areaFile, std::map< std::string, std::pair< double, double > > fIntensityMap)
void SetNorm (double fNorm)
void SetAbsolute (bool fAbs)
void SetAbsScale (double fScale)
int GetIndex (std::string key)
bool GetAbsolute ()
std::string GetKey (int i)
double GetEnergy (int i)
double GetPeak (int i)
double GetIntensity (int i)
double GetNorm ()
double GetEfficiency (int i)
double GetNData ()
void EraseData (std::string key)
void Print (const char *fileName)
void Clear ()
TGraphErrors * GetGraph ()
TGraphErrors * GetGraphErrors ()
Detailed Description
Definition at line 25 of file Efficiency.hh.
Constructor & Destructor Documentation
DataSet() [1/5]
GamR::Efficiency::DataSet::DataSet () inline
Definition at line 38 of file Efficiency.hh.
DataSet() [2/5]
GamR::Efficiency::DataSet::DataSet (const char * effFile)
Definition at line 359 of file Efficiency.cc.
References SetData().
DataSet() [3/5]
GamR::Efficiency::DataSet::DataSet (const char * histFile, const char * histName, const char * gateFile, const char * mapName, const char * intensityFile)
Definition at line 364 of file Efficiency.cc.
References SetData().
DataSet() [4/5]
GamR::Efficiency::DataSet::DataSet (TH1D * fHist, GamR::Nucleus::TransitionMap * fTransitionMap, std::map< std::string, std::pair< double, double > > fIntensityMap)
Definition at line 239 of file Efficiency.cc.
References SetData().
DataSet() [5/5]
GamR::Efficiency::DataSet::DataSet (std::string areaFile, const char * intensityFile)
Definition at line 389 of file Efficiency.cc.
References SetData().
Member Function Documentation
Clear()
void GamR::Efficiency::DataSet::Clear ()
Definition at line 226 of file Efficiency.cc.
Referenced by SetData(), SetData(), and SetData().
EraseData()
void GamR::Efficiency::DataSet::EraseData (std::string key)
Definition at line 419 of file Efficiency.cc.
References GetIndex().
GetAbsolute()
bool GamR::Efficiency::DataSet::GetAbsolute () inline
Definition at line 50 of file Efficiency.hh.
GetEfficiency()
double GamR::Efficiency::DataSet::GetEfficiency (int i) inline
Definition at line 56 of file Efficiency.hh.
Referenced by GamR::Efficiency::MultiEffFit::AddData().
GetEnergy()
double GamR::Efficiency::DataSet::GetEnergy (int i) inline
Definition at line 52 of file Efficiency.hh.
Referenced by GamR::Efficiency::MultiEffFit::AddData().
GetGraph()
TGraphErrors * GamR::Efficiency::DataSet::GetGraph ()
Definition at line 447 of file Efficiency.cc.
GetGraphErrors()
TGraphErrors * GamR::Efficiency::DataSet::GetGraphErrors ()
Definition at line 466 of file Efficiency.cc.
GetIndex()
int GamR::Efficiency::DataSet::GetIndex (std::string key)
Definition at line 403 of file Efficiency.cc.
References GetNData().
Referenced by EraseData().
GetIntensity()
double GamR::Efficiency::DataSet::GetIntensity (int i) inline
Definition at line 54 of file Efficiency.hh.
GetKey()
std::string GamR::Efficiency::DataSet::GetKey (int i) inline
Definition at line 51 of file Efficiency.hh.
GetNData()
double GamR::Efficiency::DataSet::GetNData () inline
Definition at line 57 of file Efficiency.hh.
Referenced by GamR::Efficiency::MultiEffFit::AddData(), GetIndex(), and Print().
GetNorm()
double GamR::Efficiency::DataSet::GetNorm () inline
Definition at line 55 of file Efficiency.hh.
GetPeak()
double GamR::Efficiency::DataSet::GetPeak (int i) inline
Definition at line 53 of file Efficiency.hh.
Print()
void GamR::Efficiency::DataSet::Print (const char * fileName)
Definition at line 434 of file Efficiency.cc.
References GetNData().
SetAbsolute()
void GamR::Efficiency::DataSet::SetAbsolute (bool fAbs) inline
Definition at line 47 of file Efficiency.hh.
SetAbsScale()
void GamR::Efficiency::DataSet::SetAbsScale (double fScale) inline
Definition at line 48 of file Efficiency.hh.
SetData() [1/3]
void GamR::Efficiency::DataSet::SetData (const char * effFile)
Definition at line 322 of file Efficiency.cc.
References Clear().
Referenced by DataSet(), DataSet(), DataSet(), and DataSet().
SetData() [2/3]
void GamR::Efficiency::DataSet::SetData (std::string areaFile, std::map< std::string, std::pair< double, double > > fIntensityMap)
Definition at line 280 of file Efficiency.cc.
References Clear().
SetData() [3/3]
void GamR::Efficiency::DataSet::SetData (TH1D * fHist, GamR::Nucleus::TransitionMap * fTransitionMap, std::map< std::string, std::pair< double, double > > fIntensityMap)
Definition at line 244 of file Efficiency.cc.
References Clear(), and GamR::Nucleus::TransitionMap::GetMap().
SetNorm()
void GamR::Efficiency::DataSet::SetNorm (double fNorm) inline
Definition at line 46 of file Efficiency.hh.
The documentation for this class was generated from the following files:
src/lib/efficiency/Efficiency.hh
src/lib/efficiency/Efficiency.cc