GamR: GamR::Spect Namespace Reference
GamR::Spect Namespace Reference
Spect
Classes
class BackSub2D
struct Parameter
class PeakFit
class PeakFitGuesses
Enumerations
enum class FFTWindow { BOX , HANN , HAMMING }
Functions
std::pair< double, double > TwoPointCalibrate (TVirtualPad *canvas, double sigma)
std::pair< double, double > TwoPointCalibrate (TH1 *hist, double lowEst, double highEst, double lowEn, double highEn, double sigma)
TH1D * ProjX (TH2 *hist, const char *name)
TH1D * ProjX (TH2 *hist)
TH1D * ProjX (TVirtualPad *canvas, const char *name)
TH1D * ProjX (TVirtualPad *canvas)
TH1D * ProjY (TH2 *hist, const char *name)
TH1D * ProjY (TH2 *hist)
TH1D * ProjY (TVirtualPad *canvas, const char *name)
TH1D * ProjY (TVirtualPad *canvas)
TH1D * GateX (TH2 *hist, GamR::TK::Gate peak, const char *name)
TH1D * GateX (TH2 *hist, GamR::TK::Gate peak)
TH1D * GateX (TCanvas *canvas, const char *name)
TH1D * GateX (TCanvas *canvas)
TH1D * GateY (TH2 *hist, GamR::TK::Gate peak, const char *name)
TH1D * GateY (TH2 *hist, GamR::TK::Gate peak)
TH1D * GateY (TCanvas *canvas, const char *name)
TH1D * GateY (TCanvas *canvas)
TH1D * BackgroundSubtractX (TH2 *hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background, const char *name)
TH1D * BackgroundSubtractX (TH2 *hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background)
TH1D * BackgroundSubtractX (TH2 *hist, GamR::TK::Gate peak, GamR::TK::Gate background, const char *name)
TH1D * BackgroundSubtractX (TH2 *hist, GamR::TK::Gate peak, GamR::TK::Gate background)
TH1D * BackgroundSubtractX (TH2 *hist, GamR::Nucleus::Transition peak, const char *name)
TH1D * BackgroundSubtractX (TH2 *hist, GamR::Nucleus::Transition peak)
TH1D * BackgroundSubtractX (TCanvas *canvas, const char *name)
TH1D * BackgroundSubtractX (TCanvas *canvas)
TH1D * BackgroundSubtractY (TH2 *hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background, const char *name)
TH1D * BackgroundSubtractY (TH2 *hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background)
TH1D * BackgroundSubtractY (TH2 *hist, GamR::TK::Gate peak, GamR::TK::Gate background, const char *name)
TH1D * BackgroundSubtractY (TH2 *hist, GamR::TK::Gate peak, GamR::TK::Gate background)
TH1D * BackgroundSubtractY (TH2 *hist, GamR::Nucleus::Transition peak, const char *name)
TH1D * BackgroundSubtractY (TH2 *hist, GamR::Nucleus::Transition peak)
TH1D * BackgroundSubtractY (TCanvas *canvas, const char *name)
TH1D * BackgroundSubtractY (TCanvas *canvas)
std::shared_ptr< TH2D > BackgroundEstimate (const TH2 *hist, Int_t NiterX, Int_t NiterY, Int_t direction, Int_t filtertype)
TH2D * BackgroundSubtract2D (TH2 *peak, TH2 *background, double scale)
std::vector< TH1 * > List1DSpectra (bool quiet)
std::vector< TH2 * > List2DSpectra (bool quiet)
void Draw (int i, Option_t *option)
void Draw2D (int i, Option_t *option)
void OverlaySpectra (std::vector< int > display_indexes, TCanvas *canvas, Option_t *option)
void OverlaySpectra (int iStart, int iStop, TCanvas *canvas, Option_t *option)
void OverlaySpectra (std::vector< TH1 * > hists, TCanvas *canvas, Option_t *option)
void OverlaySpectra (TH2 *hist, int iStart, int iStop, Option_t *option)
void OverlaySpectra (TH2 *hist, std::vector< int > indices, Option_t *option)
void OverlaySpectra (int i2D, int iStart, int iStop, Option_t *option)
void OverlaySpectra (std::vector< std::string > files, std::string name, int iX, Option_t *option)
void OverlaySpectra (std::vector< std::string > files, std::string name, Option_t *option)
void StackSpectra (std::vector< int > display_indexes, TCanvas *canvas, Option_t *option)
void StackSpectra (int iStart, int iStop, TCanvas *canvas, Option_t *option)
void StackSpectra (std::vector< TH1 * > hists, TCanvas *canvas, Option_t *option)
void StackSpectra (TH2 *hist, int iStart, int iStop, Option_t *option)
void StackSpectra (int i2D, int iStart, int iStop, Option_t *option)
void StackSpectra (std::vector< std::string > files, std::string name, int iX, Option_t *option)
void StackSpectra (std::vector< std::string > files, std::string name, Option_t *option)
void LinAll (TVirtualPad *canvas)
void LogAll (TVirtualPad *canvas)
void ZoomAllX (double low, double high, TVirtualPad *canvas)
void ZoomAllY (double low, double high, TVirtualPad *canvas)
void UnZoomAllX (TVirtualPad *canvas)
void UnZoomAllY (TVirtualPad *canvas)
void NormSpectra (TVirtualPad *canvas, Option_t *option)
void NormSpectraBackSub (TVirtualPad *canvas)
void Rename (TVirtualPad *canvas)
TH1D * FFT (TH1 *hist, const char *name, double low, double high, FFTWindow wind)
GamR::Spect::PeakFit * FitPeaks (TH1 *hist, double Low, double High, std::vector< double > Peaks, Option_t *foption, Option_t *option, std::vector< std::string > FixPeaks)
GamR::Spect::PeakFit * FitPeaks (TH1 *hist, double Low, double High, std::map< std::string, double > Peaks, Option_t *foption, Option_t *option, std::vector< std::string > FixPeaks)
GamR::Spect::PeakFit * FitPeaks (TCanvas *canvas, Option_t *foption, Option_t *option)
TF1 * FitGaussians (TH1 *hist, double Low, double High, std::vector< double > Peaks, Option_t *foption, Option_t *option)
TF1 * FitGaussians (TCanvas *canvas, Option_t *foption, Option_t *option)
TSpectrum * FindPeaks (TCanvas *canvas, double sigma, Option_t *option, double threshold)
TF1 * FitGaussians (TH1 *hist, double Low, double High, std::map< std::string, double > Peaks, Option_t *foption="", Option_t *option="")
int LoadGuesses (std::string path)
void Init ()
std::pair< double, double > Integral (TH1 *hist, GamR::TK::Gate peak)
std::pair< double, double > Integral (TH1 *hist, double peakLow, double peakHigh)
std::pair< double, double > Integral (TCanvas *canvas)
std::pair< double, double > IntegralBS (TH1 *hist, GamR::Nucleus::Transition transition)
std::pair< double, double > IntegralBS (TH1 *hist, GamR::TK::Gate peak, GamR::TK::Gate background)
std::pair< double, double > IntegralBS (TH1 *hist, double peakLow, double peakHigh, double backLow, double backHigh)
std::pair< double, double > IntegralBS (TCanvas *canvas)
std::pair< double, double > Counts (TH1 *hist, GamR::TK::Gate peak)
std::pair< double, double > Counts (TH1 *hist, double peakLow, double peakHigh)
std::pair< double, double > Counts (TCanvas *canvas)
std::pair< double, double > CountsBS (TH1 *hist, GamR::Nucleus::Transition transition)
std::pair< double, double > CountsBS (TH1 *hist, GamR::TK::Gate peak, GamR::TK::Gate background)
std::pair< double, double > CountsBS (TH1 *hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > backgrounds)
std::pair< double, double > CountsBS (TH1 *hist, double peakLow, double peakHigh, double backLow, double backHigh)
std::pair< double, double > CountsBS (TCanvas *canvas)
std::string ToText (const TH1 *h, std::string outfile, std::string delimiter)
std::string ToText (const TH2 *h, std::string outfile, std::string delimiter, int binx, int biny)
std::string ToText (const TGraphErrors *g, std::string outfile, std::string delimiter)
std::string ToText (const TGraph *g, std::string outfile, std::string delimiter)
std::string ToText (const TGraph *g, int ID, std::string outfile, std::string delimiter)
std::string ToText (const TF1 *f, std::string outfile, std::string delimiter)
void ToBin (const TH2 *h, std::string outfile, int padx, int pady)
void ToBin (const TH1 *h, std::string outfile)
void ToSPE (const TH1 *h, std::string outfile)
TH1D FromText (std::string s, std::string name)
TH1D * FromBin (std::string s, std::string name, std::string title, int nx, double low, double high, int size)
TH2D * FromBin (std::string s, std::string name, std::string title, int nx, double xlow, double xhigh, int ny, double ylow, double yhigh, int size)
TCutG * CutFromText (std::string s, std::string name)
TH1D Scale (const TH1 *h, TFormula f)
Scales a histogram along the X axis and dithers to avoid quantization errors.
TH1D ScalePoly (const TH1 *h, std::vector< Double_t > pars)
Scales histogram by a polynomial.
void ScaleLabelsLinear (TH1 *h, Double_t m, Double_t c)
Scales the labels of a histogram. Preferable over GamR::Spect::Scale and GamR::Spect::ScalePoly as it avoids having to regenerate the histogram.
void Shift (TH1 &h, Int_t shift)
TH1D * Add (TH1 *hist1, TH1 *hist2, const char *name, double c1, double c2)
TH1D * Add (std::vector< TH1 * > hists, const char *name)
TH1D * Add (std::vector< int > hists, const char *name)
TH1D * Add (int iStart, int iStop, const char *name)
TH2D * Add (TH2 *hist1, TH2 *hist2, const char *name, double c1, double c2)
TH2D * Add (std::vector< TH2 * > hists, const char *name)
TH2D * Add2 (std::vector< int > hists, const char *name)
TH2D * Add2 (int iStart, int iStop, const char *name)
TH1D * Multiply (TH1 *hist1, const char *name, double c1)
void Reverse (TH1 *h)
TH2D * RotateTH2 (TH2 *hist, float angle, const char *name, TCutG *bananaGate)
TH1 * Rebin (TH1 *hist, int rebin)
void Rebin (TVirtualPad *canvas, int rebin)
void Norm (TH1 *hist, TH1 *ref, double low, double high)
void NormBackSub (TH1 *hist, TH1 *ref, double low, double high, double backlow, double backhigh)
Variables
PeakFitGuesses * gFitGuesses
Detailed Description
Library of tools spectroscopy tools - transforming histograms, fitting peaks, doing cuts and background subtractions etc.
Enumeration Type Documentation
FFTWindow
enum class GamR::Spect::FFTWindow strong
Enumerator
BOX
HANN
HAMMING
Definition at line 8 of file FFT.hh.
Function Documentation
Add() [1/6]
TH1D * GamR::Spect::Add (int iStart, int iStop, const char * name)
Definition at line 149 of file Transform.cc.
References Add(), and List1DSpectra().
Add() [2/6]
TH1D * GamR::Spect::Add (std::vector< int > hists, const char * name)
Definition at line 140 of file Transform.cc.
References Add(), and List1DSpectra().
Add() [3/6]
TH1D * GamR::Spect::Add (std::vector< TH1 * > hists, const char * name)
Definition at line 131 of file Transform.cc.
Add() [4/6]
TH2D * GamR::Spect::Add (std::vector< TH2 * > hists, const char * name)
Definition at line 183 of file Transform.cc.
Add() [5/6]
TH1D * GamR::Spect::Add (TH1 * hist1, TH1 * hist2, const char * name, double c1, double c2)
Function to add two histograms with correct error handling
Note that the histograms should be of the same dimension. Errors are added in quadrature
Parameters
hist1 First histogram
hist2 Second histogram
name Name of the output histogram
c1 Weight for hist1
c2 Weight for hist2
Returns
c1*hist1 + c2*hist2
Definition at line 121 of file Transform.cc.
Referenced by add(), Add(), add(), Add(), add(), Add2(), Add2(), and add2().
Add() [6/6]
TH2D * GamR::Spect::Add (TH2 * hist1, TH2 * hist2, const char * name, double c1, double c2)
Function to add two histograms with correct error handling
Note that the histograms should be of the same dimension. Errors are added in quadrature
Parameters
hist1 First histogram
hist2 Second histogram
name Name of the output histogram
c1 Weight for hist1
c2 Weight for hist2
Returns
c1*hist1 + c2*hist2
Definition at line 171 of file Transform.cc.
Add2() [1/2]
TH2D * GamR::Spect::Add2 (int iStart, int iStop, const char * name)
Definition at line 201 of file Transform.cc.
References Add(), and List2DSpectra().
Add2() [2/2]
TH2D * GamR::Spect::Add2 (std::vector< int > hists, const char * name)
Definition at line 192 of file Transform.cc.
References Add(), and List2DSpectra().
Referenced by add2(), and add2().
BackgroundEstimate()
std::shared_ptr< TH2D > GamR::Spect::BackgroundEstimate (const TH2 * hist, Int_t NiterX, Int_t NiterY, Int_t direction, Int_t filtertype)
Implementation of TSpectrum::Background to take a histogram as input. For details refer to the ROOT TSpectrum documentation.
Parameters
[in] hist 2D histogram
[in] NiterX Maximal X width of clipping window
[in] NiterY Maximal Y width of clipping window
[in] direction Direction of clipping window: TSpectrum2::kBackIncreasingwindow, TSpectrum2::kBackDecreasingWindow
[in] filtertype Filter algorithm: TSpectrum2::kBackSuccessiveFiltering, TSpectrum2::kBackOneStepFiltering
Returns
[out] Smart pointer to background estimate of input histogram
Definition at line 424 of file Cut.cc.
BackgroundSubtract2D()
TH2D * GamR::Spect::BackgroundSubtract2D (TH2 * peak, TH2 * background, double scale)
Definition at line 452 of file Cut.cc.
BackgroundSubtractX() [1/8]
TH1D * GamR::Spect::BackgroundSubtractX (TCanvas * canvas)
Definition at line 264 of file Cut.cc.
References BackgroundSubtractX(), GamR::Utils::GetHist2D(), and GamR::TK::Gate::SetGate().
BackgroundSubtractX() [2/8]
TH1D * GamR::Spect::BackgroundSubtractX (TCanvas * canvas, const char * name)
Definition at line 241 of file Cut.cc.
References BackgroundSubtractX(), GamR::Utils::GetHist2D(), and GamR::TK::Gate::SetGate().
BackgroundSubtractX() [3/8]
TH1D * GamR::Spect::BackgroundSubtractX (TH2 * hist, GamR::Nucleus::Transition peak)
Definition at line 236 of file Cut.cc.
References BackgroundSubtractX(), GamR::Nucleus::Transition::GetGate(), and GamR::Nucleus::Transition::GetGateBG().
BackgroundSubtractX() [4/8]
TH1D * GamR::Spect::BackgroundSubtractX (TH2 * hist, GamR::Nucleus::Transition peak, const char * name)
Definition at line 231 of file Cut.cc.
References BackgroundSubtractX(), GamR::Nucleus::Transition::GetGate(), and GamR::Nucleus::Transition::GetGateBG().
BackgroundSubtractX() [5/8]
TH1D * GamR::Spect::BackgroundSubtractX (TH2 * hist, GamR::TK::Gate peak, GamR::TK::Gate background)
Definition at line 226 of file Cut.cc.
References BackgroundSubtractX().
BackgroundSubtractX() [6/8]
TH1D * GamR::Spect::BackgroundSubtractX (TH2 * hist, GamR::TK::Gate peak, GamR::TK::Gate background, const char * name)
Definition at line 221 of file Cut.cc.
References BackgroundSubtractX().
BackgroundSubtractX() [7/8]
TH1D * GamR::Spect::BackgroundSubtractX (TH2 * hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background)
Definition at line 216 of file Cut.cc.
References BackgroundSubtractX().
BackgroundSubtractX() [8/8]
TH1D * GamR::Spect::BackgroundSubtractX (TH2 * hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background, const char * name)
Carries out a rudimentary background subtraction
Subtracts a projection of the background region from a projection of the peak region, with a scaling factor equal to the ratio of the regions' widths.
Gates are applied on the X-axis.
Parameters
hist 2D histogram to act on
peak Gate object for the peak bounds
background Gate object for the background bounds
name Name of the output histogram
Returns
1D histogram containing the background-subtracted projection
Definition at line 179 of file Cut.cc.
References GamR::TK::Gate::ApplyX(), and GamR::TK::Gate::GetBinWidth().
Referenced by BackgroundSubtractX(), BackgroundSubtractX(), BackgroundSubtractX(), BackgroundSubtractX(), BackgroundSubtractX(), BackgroundSubtractX(), BackgroundSubtractX(), bsx(), and bsx().
BackgroundSubtractY() [1/8]
TH1D * GamR::Spect::BackgroundSubtractY (TCanvas * canvas)
Definition at line 388 of file Cut.cc.
References BackgroundSubtractY(), GamR::Utils::GetHist2D(), and GamR::TK::Gate::SetGate().
BackgroundSubtractY() [2/8]
TH1D * GamR::Spect::BackgroundSubtractY (TCanvas * canvas, const char * name)
Definition at line 365 of file Cut.cc.
References BackgroundSubtractY(), GamR::Utils::GetHist2D(), and GamR::TK::Gate::SetGate().
BackgroundSubtractY() [3/8]
TH1D * GamR::Spect::BackgroundSubtractY (TH2 * hist, GamR::Nucleus::Transition peak)
Definition at line 360 of file Cut.cc.
References BackgroundSubtractY(), GamR::Nucleus::Transition::GetGate(), and GamR::Nucleus::Transition::GetGateBG().
BackgroundSubtractY() [4/8]
TH1D * GamR::Spect::BackgroundSubtractY (TH2 * hist, GamR::Nucleus::Transition peak, const char * name)
Definition at line 355 of file Cut.cc.
References BackgroundSubtractY(), GamR::Nucleus::Transition::GetGate(), and GamR::Nucleus::Transition::GetGateBG().
BackgroundSubtractY() [5/8]
TH1D * GamR::Spect::BackgroundSubtractY (TH2 * hist, GamR::TK::Gate peak, GamR::TK::Gate background)
Definition at line 349 of file Cut.cc.
References BackgroundSubtractY().
BackgroundSubtractY() [6/8]
TH1D * GamR::Spect::BackgroundSubtractY (TH2 * hist, GamR::TK::Gate peak, GamR::TK::Gate background, const char * name)
Definition at line 343 of file Cut.cc.
References BackgroundSubtractY().
BackgroundSubtractY() [7/8]
TH1D * GamR::Spect::BackgroundSubtractY (TH2 * hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background)
Definition at line 338 of file Cut.cc.
References BackgroundSubtractY().
BackgroundSubtractY() [8/8]
TH1D * GamR::Spect::BackgroundSubtractY (TH2 * hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background, const char * name)
Carries out a rudimentary background subtraction
Subtracts a projection of the background region from a projection of the peak region, with a scaling factor equal to the ratio of the regions' widths.
Gates are applied on the Y-axis.
Parameters
hist 2D histogram to act on
peak Gate object for the peak bounds
background Gate object for the background bounds
name Name of the output histogram
Returns
1D histogram containing the background-subtracted projection
Definition at line 301 of file Cut.cc.
References GamR::TK::Gate::ApplyY(), and GamR::TK::Gate::GetBinWidth().
Referenced by BackgroundSubtractY(), BackgroundSubtractY(), BackgroundSubtractY(), BackgroundSubtractY(), BackgroundSubtractY(), BackgroundSubtractY(), BackgroundSubtractY(), bsy(), bsy(), and GamR::AngDist::AngCorrFit::SetData().
Counts() [1/3]
std::pair< double, double > GamR::Spect::Counts (TCanvas * canvas)
Definition at line 83 of file Integral.cc.
References Counts(), GamR::Utils::GetHist1D(), and GamR::TK::Gate::SetGate().
Counts() [2/3]
std::pair< double, double > GamR::Spect::Counts (TH1 * hist, double peakLow, double peakHigh)
Definition at line 78 of file Integral.cc.
References Counts().
Counts() [3/3]
std::pair< double, double > GamR::Spect::Counts (TH1 * hist, GamR::TK::Gate peak)
Definition at line 69 of file Integral.cc.
References GamR::TK::Gate::GetCounts(), and GamR::TK::Gate::GetCountsError().
Referenced by Counts(), Counts(), and ct().
CountsBS() [1/5]
std::pair< double, double > GamR::Spect::CountsBS (TCanvas * canvas)
Definition at line 118 of file Integral.cc.
References CountsBS(), GamR::Utils::GetHist1D(), and GamR::Nucleus::Transition::SetTransition().
CountsBS() [2/5]
std::pair< double, double > GamR::Spect::CountsBS (TH1 * hist, double peakLow, double peakHigh, double backLow, double backHigh)
Definition at line 113 of file Integral.cc.
References CountsBS().
CountsBS() [3/5]
std::pair< double, double > GamR::Spect::CountsBS (TH1 * hist, GamR::Nucleus::Transition transition)
Definition at line 91 of file Integral.cc.
References GamR::Nucleus::Transition::ApplyCounts(), and GamR::Nucleus::Transition::ApplyCountsError().
Referenced by CountsBS(), CountsBS(), CountsBS(), CountsBS(), and ctbs().
CountsBS() [4/5]
std::pair< double, double > GamR::Spect::CountsBS (TH1 * hist, GamR::TK::Gate peak, GamR::TK::Gate background)
Definition at line 100 of file Integral.cc.
References CountsBS(), GamR::TK::Gate::GetHigh(), and GamR::TK::Gate::GetLow().
CountsBS() [5/5]
std::pair< double, double > GamR::Spect::CountsBS (TH1 * hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > backgrounds)
Definition at line 105 of file Integral.cc.
References GamR::Nucleus::Transition::AddBackground(), CountsBS(), GamR::TK::Gate::GetHigh(), and GamR::TK::Gate::GetLow().
CutFromText()
TCutG * GamR::Spect::CutFromText (std::string s, std::string name)
Definition at line 323 of file IO.cc.
References ss().
Draw()
void GamR::Spect::Draw (int i, Option_t * option)
Definition at line 81 of file Display.cc.
References List1DSpectra().
Referenced by sp().
Draw2D()
void GamR::Spect::Draw2D (int i, Option_t * option)
Definition at line 85 of file Display.cc.
References List2DSpectra().
Referenced by sp2().
FFT()
TH1D * GamR::Spect::FFT (TH1 * hist, const char * name, double low, double high, FFTWindow wind)
Definition at line 8 of file FFT.cc.
References HAMMING, HANN, and ScaleLabelsLinear().
FindPeaks()
TSpectrum * GamR::Spect::FindPeaks (TCanvas * canvas, double sigma, Option_t * option, double threshold)
Definition at line 1569 of file Fit.cc.
References GamR::Utils::GetHist1D().
Referenced by fp().
FitGaussians() [1/3]
TF1 * GamR::Spect::FitGaussians (TCanvas * canvas, Option_t * foption, Option_t * option)
Definition at line 1563 of file Fit.cc.
References FitPeaks().
FitGaussians() [2/3]
TF1 * GamR::Spect::FitGaussians (TH1 * hist, double Low, double High, std::map< std::string, double > Peaks, Option_t * foption = "", Option_t * option = "")
FitGaussians() [3/3]
TF1 * GamR::Spect::FitGaussians (TH1 * hist, double Low, double High, std::vector< double > Peaks, Option_t * foption, Option_t * option)
Definition at line 1556 of file Fit.cc.
References FitPeaks().
FitPeaks() [1/3]
PeakFit * GamR::Spect::FitPeaks (TCanvas * canvas, Option_t * foption, Option_t * option)
Fits an arbitrary number of peaks over a quadratic background, using mouse input.
Click left and right for fitting area, then once for every peak centroid. Any key will start fitting.
Parameters
canvas A pointer to a TCanvas object containing a single histogram. Note that this function has not been tested for canvases containing multiple histograms.
Definition at line 823 of file Fit.cc.
References FitPeaks(), GamR::TK::Gaussian, GamR::Spect::PeakFit::GetBackground(), GamR::Utils::GetHist1D(), GamR::Spect::PeakFit::GetPeakBG(), GamR::Spect::PeakFit::GetPeakGaussBG(), GamR::Spect::PeakFit::GetPeaks(), GamR::Spect::PeakFit::GetPeakStepBG(), GamR::Spect::PeakFit::GetPeakType(), GamR::Spect::PeakFit::GetTotal(), ss(), and GamR::TK::StepGaussian.
FitPeaks() [2/3]
PeakFit * GamR::Spect::FitPeaks (TH1 * hist, double Low, double High, std::map< std::string, double > Peaks, Option_t * foption, Option_t * option, std::vector< std::string > FixPeaks)
Definition at line 785 of file Fit.cc.
References GamR::Spect::PeakFit::Fit(), GamR::Spect::PeakFit::GetHigh(), GamR::Spect::PeakFit::GetLow(), GamR::Spect::PeakFit::GetTotal(), GamR::Spect::PeakFit::PrintResults(), GamR::Spect::PeakFit::SetResults(), and GamR::Spect::PeakFit::SetUp().
FitPeaks() [3/3]
PeakFit * GamR::Spect::FitPeaks (TH1 * hist, double Low, double High, std::vector< double > Peaks, Option_t * foption, Option_t * option, std::vector< std::string > FixPeaks)
Fits an arbitrary number of Gaussian peaks over a quadratic background.
Parameters
hist Histogram to be fitted to
Low Lower bound of fit
High Upper bound of fit
Peaks std::vector of doubles containing approximate locations of peak centroids (starting guesses)
Returns
A TF1* which is the fitted function
Definition at line 774 of file Fit.cc.
References FitPeaks().
Referenced by FitGaussians(), FitGaussians(), FitPeaks(), FitPeaks(), and pf().
FromBin() [1/2]
TH1D * GamR::Spect::FromBin (std::string s, std::string name, std::string title, int nx, double low, double high, int size)
Definition at line 262 of file IO.cc.
References fp().
FromBin() [2/2]
TH2D * GamR::Spect::FromBin (std::string s, std::string name, std::string title, int nx, double xlow, double xhigh, int ny, double ylow, double yhigh, int size)
Definition at line 282 of file IO.cc.
References fp().
FromText()
TH1D GamR::Spect::FromText (std::string s, std::string name)
Definition at line 216 of file IO.cc.
References ss().
GateX() [1/4]
TH1D * GamR::Spect::GateX (TCanvas * canvas)
Definition at line 93 of file Cut.cc.
References GateX(), and GamR::Utils::GetHist2D().
GateX() [2/4]
TH1D * GamR::Spect::GateX (TCanvas * canvas, const char * name)
Definition at line 78 of file Cut.cc.
References GateX(), and GamR::Utils::GetHist2D().
GateX() [3/4]
TH1D * GamR::Spect::GateX (TH2 * hist, GamR::TK::Gate peak)
Definition at line 71 of file Cut.cc.
References GamR::TK::Gate::ApplyX().
GateX() [4/4]
TH1D * GamR::Spect::GateX (TH2 * hist, GamR::TK::Gate peak, const char * name)
Carries out a gate and projection
Gates are applied on the X-axis.
Parameters
hist 2D histogram to act on
peak Gate object for the peak bounds
name Name of the output histogram
Returns
1D histogram containing the gated projection
Definition at line 64 of file Cut.cc.
References GamR::TK::Gate::ApplyX().
Referenced by GateX(), GateX(), and gx().
GateY() [1/4]
TH1D * GamR::Spect::GateY (TCanvas * canvas)
Definition at line 148 of file Cut.cc.
References GateY(), and GamR::Utils::GetHist2D().
GateY() [2/4]
TH1D * GamR::Spect::GateY (TCanvas * canvas, const char * name)
Definition at line 133 of file Cut.cc.
References GateY(), and GamR::Utils::GetHist2D().
GateY() [3/4]
TH1D * GamR::Spect::GateY (TH2 * hist, GamR::TK::Gate peak)
Definition at line 126 of file Cut.cc.
References GamR::TK::Gate::ApplyY().
GateY() [4/4]
TH1D * GamR::Spect::GateY (TH2 * hist, GamR::TK::Gate peak, const char * name)
Carries out a gate and projection
Gates are applied on the Y-axis.
Parameters
hist 2D histogram to act on
peak Gate object for the peak bounds
name Name of the output histogram
Returns
1D histogram containing the gated projection
Definition at line 119 of file Cut.cc.
References GamR::TK::Gate::ApplyY().
Referenced by GateY(), GateY(), and gy().
Init()
void GamR::Spect::Init ()
Integral() [1/3]
std::pair< double, double > GamR::Spect::Integral (TCanvas * canvas)
Definition at line 32 of file Integral.cc.
References GamR::Utils::GetHist1D(), Integral(), and GamR::TK::Gate::SetGate().
Integral() [2/3]
std::pair< double, double > GamR::Spect::Integral (TH1 * hist, double peakLow, double peakHigh)
Definition at line 27 of file Integral.cc.
References Integral().
Integral() [3/3]
std::pair< double, double > GamR::Spect::Integral (TH1 * hist, GamR::TK::Gate peak)
Definition at line 18 of file Integral.cc.
References GamR::TK::Gate::GetIntegral(), and GamR::TK::Gate::GetIntegralError().
Referenced by ig(), Integral(), and Integral().
IntegralBS() [1/4]
std::pair< double, double > GamR::Spect::IntegralBS (TCanvas * canvas)
Definition at line 59 of file Integral.cc.
References GamR::Utils::GetHist1D(), IntegralBS(), and GamR::Nucleus::Transition::SetTransition().
IntegralBS() [2/4]
std::pair< double, double > GamR::Spect::IntegralBS (TH1 * hist, double peakLow, double peakHigh, double backLow, double backHigh)
Definition at line 54 of file Integral.cc.
References IntegralBS().
IntegralBS() [3/4]
std::pair< double, double > GamR::Spect::IntegralBS (TH1 * hist, GamR::Nucleus::Transition transition)
Definition at line 40 of file Integral.cc.
References GamR::Nucleus::Transition::Apply(), and GamR::Nucleus::Transition::ApplyError().
Referenced by igbs(), IntegralBS(), IntegralBS(), and IntegralBS().
IntegralBS() [4/4]
std::pair< double, double > GamR::Spect::IntegralBS (TH1 * hist, GamR::TK::Gate peak, GamR::TK::Gate background)
Definition at line 49 of file Integral.cc.
References GamR::TK::Gate::GetHigh(), GamR::TK::Gate::GetLow(), and IntegralBS().
LinAll()
void GamR::Spect::LinAll (TVirtualPad * canvas)
Definition at line 266 of file Display.cc.
References GamR::Utils::GetNPads(), and LinAll().
Referenced by lin(), and LinAll().
List1DSpectra()
std::vector< TH1 * > GamR::Spect::List1DSpectra (bool quiet)
Definition at line 16 of file Display.cc.
Referenced by Add(), Add(), Draw(), ls(), OverlaySpectra(), OverlaySpectra(), StackSpectra(), and StackSpectra().
List2DSpectra()
std::vector< TH2 * > GamR::Spect::List2DSpectra (bool quiet)
Definition at line 53 of file Display.cc.
Referenced by Add2(), Add2(), Draw2D(), ls2(), OverlaySpectra(), and StackSpectra().
LoadGuesses()
int GamR::Spect::LoadGuesses (std::string path)
LogAll()
void GamR::Spect::LogAll (TVirtualPad * canvas)
Definition at line 282 of file Display.cc.
References GamR::Utils::GetNPads(), and LogAll().
Referenced by log(), and LogAll().
Multiply()
TH1D * GamR::Spect::Multiply (TH1 * hist1, const char * name, double c1)
Function to multiply a histogram with correct error handling
Errors are multiplied by the same constant
Parameters
hist1 Histogram input
name Name of the output histogram
c1 Factor to multiply
Returns
c1*hist1
Definition at line 220 of file Transform.cc.
Norm()
void GamR::Spect::Norm (TH1 * hist, TH1 * ref, double low, double high)
Definition at line 334 of file Transform.cc.
References GamR::TK::Gate::Norm().
NormBackSub()
void GamR::Spect::NormBackSub (TH1 * hist, TH1 * ref, double low, double high, double backlow, double backhigh)
Definition at line 339 of file Transform.cc.
References GamR::TK::Gate::NormBackSub().
NormSpectra()
void GamR::Spect::NormSpectra (TVirtualPad * canvas, Option_t * option)
Definition at line 407 of file Display.cc.
References GamR::Utils::GetHists1D(), GamR::TK::Gate::Norm(), and GamR::TK::Gate::SetGate().
Referenced by ns().
NormSpectraBackSub()
void GamR::Spect::NormSpectraBackSub (TVirtualPad * canvas)
Definition at line 441 of file Display.cc.
References GamR::Utils::GetHists1D(), GamR::TK::Gate::NormBackSub(), and GamR::TK::Gate::SetGate().
Referenced by nsbs().
OverlaySpectra() [1/8]
void GamR::Spect::OverlaySpectra (int i2D, int iStart, int iStop, Option_t * option)
Definition at line 160 of file Display.cc.
References List2DSpectra(), and OverlaySpectra().
OverlaySpectra() [2/8]
void GamR::Spect::OverlaySpectra (int iStart, int iStop, TCanvas * canvas, Option_t * option)
Definition at line 99 of file Display.cc.
References List1DSpectra(), and OverlaySpectra().
OverlaySpectra() [3/8]
void GamR::Spect::OverlaySpectra (std::vector< int > display_indexes, TCanvas * canvas, Option_t * option)
Definition at line 90 of file Display.cc.
References List1DSpectra(), and OverlaySpectra().
Referenced by os(), os(), os(), os(), os(), os(), os(), os(), OverlaySpectra(), OverlaySpectra(), OverlaySpectra(), OverlaySpectra(), OverlaySpectra(), OverlaySpectra(), and OverlaySpectra().
OverlaySpectra() [4/8]
void GamR::Spect::OverlaySpectra (std::vector< std::string > files, std::string name, int iX, Option_t * option)
Definition at line 165 of file Display.cc.
References OverlaySpectra().
OverlaySpectra() [5/8]
void GamR::Spect::OverlaySpectra (std::vector< std::string > files, std::string name, Option_t * option)
Definition at line 176 of file Display.cc.
References OverlaySpectra().
OverlaySpectra() [6/8]
void GamR::Spect::OverlaySpectra (std::vector< TH1 * > hists, TCanvas * canvas, Option_t * option)
Definition at line 108 of file Display.cc.
OverlaySpectra() [7/8]
void GamR::Spect::OverlaySpectra (TH2 * hist, int iStart, int iStop, Option_t * option)
Definition at line 141 of file Display.cc.
References OverlaySpectra().
OverlaySpectra() [8/8]
void GamR::Spect::OverlaySpectra (TH2 * hist, std::vector< int > indices, Option_t * option)
Definition at line 150 of file Display.cc.
References OverlaySpectra().
ProjX() [1/4]
TH1D * GamR::Spect::ProjX (TH2 * hist)
Definition at line 9 of file Cut.cc.
ProjX() [2/4]
TH1D * GamR::Spect::ProjX (TH2 * hist, const char * name)
Definition at line 5 of file Cut.cc.
Referenced by ProjX(), ProjX(), and px().
ProjX() [3/4]
TH1D * GamR::Spect::ProjX (TVirtualPad * canvas)
Definition at line 21 of file Cut.cc.
References GamR::Utils::GetHist2D(), and ProjX().
ProjX() [4/4]
TH1D * GamR::Spect::ProjX (TVirtualPad * canvas, const char * name)
Definition at line 13 of file Cut.cc.
References GamR::Utils::GetHist2D(), and ProjX().
ProjY() [1/4]
TH1D * GamR::Spect::ProjY (TH2 * hist)
Definition at line 33 of file Cut.cc.
ProjY() [2/4]
TH1D * GamR::Spect::ProjY (TH2 * hist, const char * name)
Definition at line 29 of file Cut.cc.
Referenced by ProjY(), ProjY(), and py().
ProjY() [3/4]
TH1D * GamR::Spect::ProjY (TVirtualPad * canvas)
Definition at line 45 of file Cut.cc.
References GamR::Utils::GetHist2D(), and ProjY().
ProjY() [4/4]
TH1D * GamR::Spect::ProjY (TVirtualPad * canvas, const char * name)
Definition at line 37 of file Cut.cc.
References GamR::Utils::GetHist2D(), and ProjY().
Rebin() [1/2]
TH1 * GamR::Spect::Rebin (TH1 * hist, int rebin)
Definition at line 306 of file Transform.cc.
Referenced by rb(), rb(), and Rebin().
Rebin() [2/2]
void GamR::Spect::Rebin (TVirtualPad * canvas, int rebin)
Definition at line 311 of file Transform.cc.
References GamR::Utils::GetHists1D(), GamR::Utils::GetNPads(), and Rebin().
Rename()
void GamR::Spect::Rename (TVirtualPad * canvas)
Definition at line 463 of file Display.cc.
References GamR::Utils::GetHists1D().
Referenced by rn().
Reverse()
void GamR::Spect::Reverse (TH1 * h)
Reverses histogram in place (flips X-axis). Since in ROOT axis cannot run backwards, the axis labels are not changed.
Parameters
h Histogram to be acted upon
Returns
Reversed histogram
Definition at line 236 of file Transform.cc.
RotateTH2()
TH2D * GamR::Spect::RotateTH2 (TH2 * hist, float angle, const char * name, TCutG * bananaGate)
rotates TH2 spectrum anticlocwise by angle (degrees) applying the optional cut of bananaGate if required.
Parameters
hist Histogram to be rotated
angle Angle to rotate by
name Name of output histogram
bananaGate Optional TCutG cut
Returns
Rotated histogram
Definition at line 255 of file Transform.cc.
Scale()
TH1D GamR::Spect::Scale (const TH1 * h, TFormula f)
Scales a histogram along the X axis and dithers to avoid quantization errors.
Parameters
h Input histogram
f Function
Returns
Scaled copy of histogram
Definition at line 21 of file Transform.cc.
Referenced by ScalePoly().
ScaleLabelsLinear()
void GamR::Spect::ScaleLabelsLinear (TH1 * h, Double_t m, Double_t c)
Scales the labels of a histogram. Preferable over GamR::Spect::Scale and GamR::Spect::ScalePoly as it avoids having to regenerate the histogram.
Parameters
h Histogram to be scaled.
m First derivative / Gain
c Shift / Offset
Definition at line 64 of file Transform.cc.
Referenced by FFT(), and TwoPointCalibrate().
ScalePoly()
TH1D GamR::Spect::ScalePoly (const TH1 * h, std::vector< Double_t > pars)
Scales histogram by a polynomial.
If first order, use GamR::Spect::ScaleLabelsLinear to avoid a significant amount overhead.
Parameters
h Input histogram
pars Polynomial coefficients (zeroth = constant)
Returns
Scaled copy of histogram
Definition at line 45 of file Transform.cc.
References Scale().
Shift()
void GamR::Spect::Shift (TH1 & h, Int_t shift)
Shifts the contents of a histogram (in place) by a specified number of bins
Parameters
h Histogram to be acted upon
shift Number of bins to shift contents (positive = right shift)
Definition at line 80 of file Transform.cc.
StackSpectra() [1/7]
void GamR::Spect::StackSpectra (int i2D, int iStart, int iStop, Option_t * option)
Definition at line 239 of file Display.cc.
References List2DSpectra(), and StackSpectra().
StackSpectra() [2/7]
void GamR::Spect::StackSpectra (int iStart, int iStop, TCanvas * canvas, Option_t * option)
Definition at line 196 of file Display.cc.
References List1DSpectra(), and StackSpectra().
StackSpectra() [3/7]
void GamR::Spect::StackSpectra (std::vector< int > display_indexes, TCanvas * canvas, Option_t * option)
Definition at line 187 of file Display.cc.
References List1DSpectra(), and StackSpectra().
Referenced by ss(), ss(), ss(), ss(), ss(), ss(), ss(), StackSpectra(), StackSpectra(), StackSpectra(), StackSpectra(), StackSpectra(), and StackSpectra().
StackSpectra() [4/7]
void GamR::Spect::StackSpectra (std::vector< std::string > files, std::string name, int iX, Option_t * option)
Definition at line 244 of file Display.cc.
References StackSpectra().
StackSpectra() [5/7]
void GamR::Spect::StackSpectra (std::vector< std::string > files, std::string name, Option_t * option)
Definition at line 255 of file Display.cc.
References StackSpectra().
StackSpectra() [6/7]
void GamR::Spect::StackSpectra (std::vector< TH1 * > hists, TCanvas * canvas, Option_t * option)
Definition at line 205 of file Display.cc.
StackSpectra() [7/7]
void GamR::Spect::StackSpectra (TH2 * hist, int iStart, int iStop, Option_t * option)
Definition at line 230 of file Display.cc.
References StackSpectra().
ToBin() [1/2]
void GamR::Spect::ToBin (const TH1 * h, std::string outfile)
Definition at line 173 of file IO.cc.
ToBin() [2/2]
void GamR::Spect::ToBin (const TH2 * h, std::string outfile, int padx, int pady)
Definition at line 158 of file IO.cc.
ToSPE()
void GamR::Spect::ToSPE (const TH1 * h, std::string outfile)
Definition at line 183 of file IO.cc.
References W.
ToText() [1/6]
std::string GamR::Spect::ToText (const TF1 * f, std::string outfile, std::string delimiter)
Definition at line 135 of file IO.cc.
References ss().
ToText() [2/6]
std::string GamR::Spect::ToText (const TGraph * g, int ID, std::string outfile, std::string delimiter)
Definition at line 111 of file IO.cc.
References ss().
ToText() [3/6]
std::string GamR::Spect::ToText (const TGraph * g, std::string outfile, std::string delimiter)
Definition at line 88 of file IO.cc.
References ss().
ToText() [4/6]
std::string GamR::Spect::ToText (const TGraphErrors * g, std::string outfile, std::string delimiter)
Definition at line 64 of file IO.cc.
References ss().
ToText() [5/6]
std::string GamR::Spect::ToText (const TH1 * h, std::string outfile, std::string delimiter)
Definition at line 12 of file IO.cc.
References ss().
ToText() [6/6]
std::string GamR::Spect::ToText (const TH2 * h, std::string outfile, std::string delimiter, int binx, int biny)
Definition at line 34 of file IO.cc.
References ss().
TwoPointCalibrate() [1/2]
std::pair< double, double > GamR::Spect::TwoPointCalibrate (TH1 * hist, double lowEst, double highEst, double lowEn, double highEn, double sigma)
Definition at line 159 of file Calibrate.cc.
TwoPointCalibrate() [2/2]
std::pair< double, double > GamR::Spect::TwoPointCalibrate (TVirtualPad * canvas, double sigma)
Definition at line 14 of file Calibrate.cc.
References GamR::Utils::GetHist1D(), and ScaleLabelsLinear().
Referenced by ca(), and ca().
UnZoomAllX()
void GamR::Spect::UnZoomAllX (TVirtualPad * canvas)
Definition at line 351 of file Display.cc.
References GamR::Utils::GetHist1D(), GamR::Utils::GetHist2D(), GamR::Utils::GetNPads(), and UnZoomAllX().
Referenced by UnZoomAllX(), uz(), and uzx().
UnZoomAllY()
void GamR::Spect::UnZoomAllY (TVirtualPad * canvas)
Definition at line 379 of file Display.cc.
References GamR::Utils::GetHist1D(), GamR::Utils::GetHist2D(), GamR::Utils::GetNPads(), and UnZoomAllY().
Referenced by UnZoomAllY(), uz(), and uzy().
ZoomAllX()
void GamR::Spect::ZoomAllX (double low, double high, TVirtualPad * canvas)
Definition at line 299 of file Display.cc.
References GamR::Utils::GetHist1D(), GamR::Utils::GetHist2D(), GamR::Utils::GetNPads(), and ZoomAllX().
Referenced by ZoomAllX(), and zx().
ZoomAllY()
void GamR::Spect::ZoomAllY (double low, double high, TVirtualPad * canvas)
Definition at line 325 of file Display.cc.
References GamR::Utils::GetHist1D(), GamR::Utils::GetHist2D(), GamR::Utils::GetNPads(), and ZoomAllY().
Referenced by ZoomAllY(), and zy().
Variable Documentation
gFitGuesses
PeakFitGuesses* GamR::Spect::gFitGuesses extern
Referenced by GamR::Spect::PeakFit::PeakFit(), GamR::Spect::PeakFit::PeakFit(), pfconf(), pfprint(), pfsave(), and pfsave().