GamR: GamR::Utils::REPL Class Reference
GamR::Utils::REPL Class Reference
#include <REPL.hh>
Public Member Functions
REPL (std::string prompt)
~REPL ()
void Prompt ()
bool Loop ()
bool Halt ()
void ReadLine (std::string &input)
Detailed Description
Definition at line 13 of file REPL.hh.
Constructor & Destructor Documentation
REPL()
GamR::Utils::REPL::REPL (std::string prompt)
Definition at line 9 of file REPL.cc.
References Prompt().
~REPL()
GamR::Utils::REPL::~REPL ()
Definition at line 46 of file REPL.cc.
References Halt().
Member Function Documentation
Halt()
bool GamR::Utils::REPL::Halt ()
Definition at line 61 of file REPL.cc.
Referenced by ~REPL().
Loop()
bool GamR::Utils::REPL::Loop ()
Definition at line 56 of file REPL.cc.
Prompt()
void GamR::Utils::REPL::Prompt ()
Definition at line 51 of file REPL.cc.
Referenced by REPL().
ReadLine()
void GamR::Utils::REPL::ReadLine (std::string & input)
Definition at line 67 of file REPL.cc.
The documentation for this class was generated from the following files:
src/lib/utils/REPL.hh
src/lib/utils/REPL.cc