GamR: GamR::Tree::TEvent< ADets > Class Template Reference
GamR::Tree::TEvent< ADets > Class Template Reference
#include <Event.hh>
Classes
struct ClearVector
struct EventTupleFiller
struct IgnoreTObject
Public Types
template<size_t GroupN>
using detector_type = typename std::tuple_element<GroupN, std::tuple<ADets...>>::type
Public Member Functions
TEvent ()
~TEvent ()
void SetEventNum (ULong64_t n)
size_t GetNumGroups () const
template<int N>
auto GetGroup () -> decltype(std::get< N >(DetGroup)) &
auto GetGroups () -> decltype(DetGroup) &
template<typename T>
void FillEvent (T &detdefntup)
void Reset ()
ClassDef (TEvent, 1)
Public Attributes
std::tuple< std::vector< ADets >... > DetGroup
ULong64_t EventNum
Detailed Description
template<class... ADets>
class GamR::Tree::TEvent< ADets >
Definition at line 19 of file Event.hh.
Member Typedef Documentation
detector_type
template<class... ADets> template<size_t GroupN> using GamR::Tree::TEvent< ADets >::detector_type = typename std::tuple_element<GroupN, std::tuple<ADets...>>::type
Definition at line 22 of file Event.hh.
Constructor & Destructor Documentation
TEvent()
template<class... ADets> GamR::Tree::TEvent< ADets >::TEvent () inline
Definition at line 32 of file Event.hh.
References GamR::Utils::for_each_in_tuple().
Referenced by ClassDef().
~TEvent()
template<class... ADets> GamR::Tree::TEvent< ADets >::~TEvent () inline
Definition at line 37 of file Event.hh.
Member Function Documentation
ClassDef()
template<class... ADets> GamR::Tree::TEvent< ADets >::ClassDef (TEvent< ADets > , 1)
References TEvent().
FillEvent()
template<class... ADets> template<typename T> void GamR::Tree::TEvent< ADets >::FillEvent (T & detdefntup) inline
Definition at line 48 of file Event.hh.
References DetGroup, EventNum, and GamR::Utils::for_both_in_tuple().
GetGroup()
template<class... ADets> template<int N> auto GamR::Tree::TEvent< ADets >::GetGroup () -> decltype(std::get<N>(DetGroup)) & inline
Definition at line 42 of file Event.hh.
References DetGroup.
GetGroups()
template<class... ADets> auto GamR::Tree::TEvent< ADets >::GetGroups () -> decltype(DetGroup) & inline
Definition at line 46 of file Event.hh.
References DetGroup.
GetNumGroups()
template<class... ADets> size_t GamR::Tree::TEvent< ADets >::GetNumGroups () const inline
Definition at line 40 of file Event.hh.
Reset()
template<class... ADets> void GamR::Tree::TEvent< ADets >::Reset () inline
Definition at line 52 of file Event.hh.
References DetGroup, and GamR::Utils::for_each_in_tuple().
SetEventNum()
template<class... ADets> void GamR::Tree::TEvent< ADets >::SetEventNum (ULong64_t n) inline
Definition at line 39 of file Event.hh.
References EventNum.
Member Data Documentation
DetGroup
template<class... ADets> std::tuple<std::vector<ADets>...> GamR::Tree::TEvent< ADets >::DetGroup
Definition at line 23 of file Event.hh.
Referenced by FillEvent(), GetGroup(), GetGroups(), and Reset().
EventNum
template<class... ADets> ULong64_t GamR::Tree::TEvent< ADets >::EventNum
Definition at line 24 of file Event.hh.
Referenced by FillEvent(), and SetEventNum().
The documentation for this class was generated from the following file:
src/lib/tree/Event.hh