GamR: GamR::Spect::PeakFit Class Reference
GamR::Spect::PeakFit Class Reference
#include <Fit.hh>
Classes
struct Parameters
struct PeakParams
Public Member Functions
PeakFit ()
PeakFit (double Low, double High)
PeakFit (double Low, double High, PeakFitGuesses *FitGuesses)
GamR::TK::PeakType GetPeakType ()
TF1 * GetBackground ()
TF1 * GetTotal ()
double GetChi2 ()
double GetLow ()
double GetHigh ()
size_t GetNPeaks ()
int GetParamCount ()
int GetFixWidths ()
int GetQuadBack ()
int GetStep ()
int GetTails1 ()
int GetTails2 ()
void SetParamCount (int i)
void SetFixWidths (int i)
void SetQuadBack (int i)
void SetStep (int i)
void SetTails1 (int i)
void SetTails2 (int i)
void SetOpts (Option_t *option)
void SetBackground ()
void SetPeaks (std::vector< double > Peaks)
void SetPeaks (std::map< std::string, double > Peaks)
void SetGuesses ()
void SetGuesses (TH1 *hist, std::map< std::string, GamR::TK::FPeak * > Peaks, std::vector< std::string > FixPeaks={})
void SetGuesses (TH1 *hist, std::map< std::string, double > Peaks, std::vector< std::string > FixPeaks={})
void SetIndices (std::map< std::string, GamR::TK::FPeak * > Peaks)
void SetLimit (std::string peakKey, std::string parameterKey, double lowerLimit, double upperLimit)
void SetLow (double Low)
void SetHigh (double High)
void SetChi2 (double Chi2)
void SetUp (TH1 *hist, std::map< std::string, double > Peaks, Option_t *option, std::vector< std::string > FixPeaks={})
void Fit (TH1 *hist, Option_t *foption)
void SetResults (TH1 *hist)
void SetFunction ()
void PrintResults ()
double GetAmp (std::string peakKey)
double GetAmpError (std::string peakKey)
double GetCent (std::string peakKey)
double GetCentError (std::string peakKey)
double GetWidth (std::string peakKey)
double GetWidthError (std::string peakKey)
double GetArea (std::string peakKey)
double GetAreaError (std::string peakKey)
double GetAmp (int i)
double GetAmpError (int i)
double GetCent (int i)
double GetCentError (int i)
double GetWidth (int i)
double GetWidthError (int i)
double GetArea (int i)
double GetAreaError (int i)
void SetAmp (std::string peakKey, double amp)
void SetAmpError (std::string peakKey, double error)
void SetCent (std::string peakKey, double centroid)
void SetCentError (std::string peakKey, double error)
void SetWidth (std::string peakKey, double width)
void SetWidthError (std::string peakKey, double error)
void SetAmp (int i, double amp)
void SetAmpError (int i, double error)
void SetCent (int i, double centroid)
void SetCentError (int i, double error)
void SetWidth (int i, double width)
void SetWidthError (int i, double error)
void FixPeakEnergy (std::string peakKey)
void AddPeak (std::string peakKey, GamR::TK::FPeak *peak)
void AddPeak (std::string peakKey, GamR::TK::PeakType peaktype)
void AddPeak (std::string peakKey, GamR::TK::PeakType peaktype, double centroid)
void ToText (std::string filename, std::string delimiter=" ", int nPoints=1000)
TGraph * GetWidthGraph ()
TGraph * GetStepGraph ()
TGraph * GetSkewAmpGraph ()
TGraph * GetSkewGraph ()
TGraph * GetSkewAmp2Graph ()
TGraph * GetSkew2Graph ()
GamR::TK::FPeak * Get (std::string peakKey)
GamR::TK::FPeak * Get (int i)
std::map< std::string, GamR::TK::FPeak * > GetPeaks ()
TF1 * GetPeakBG (std::string peakKey)
TF1 * GetPeakBG (int i)
TF1 * GetPeakStepBG (std::string peakKey)
TF1 * GetPeakStepBG (int i)
TF1 * GetPeakGaussBG (std::string peakKey)
TF1 * GetPeakGaussBG (int i)
TF1 * GetFunc (std::string peakKey)
Public Attributes
PeakFitGuesses * fFitGuesses
Detailed Description
Definition at line 19 of file Fit.hh.
Constructor & Destructor Documentation
PeakFit() [1/3]
GamR::Spect::PeakFit::PeakFit ()
Definition at line 24 of file Fit.cc.
References GamR::Spect::gFitGuesses.
PeakFit() [2/3]
GamR::Spect::PeakFit::PeakFit (double Low, double High)
Definition at line 28 of file Fit.cc.
References fFitGuesses, and GamR::Spect::gFitGuesses.
PeakFit() [3/3]
GamR::Spect::PeakFit::PeakFit (double Low, double High, PeakFitGuesses * FitGuesses)
Definition at line 33 of file Fit.cc.
References fFitGuesses.
Member Function Documentation
AddPeak() [1/3]
void GamR::Spect::PeakFit::AddPeak (std::string peakKey, GamR::TK::FPeak * peak)
Definition at line 1071 of file Fit.cc.
Referenced by AddPeak(), and AddPeak().
AddPeak() [2/3]
void GamR::Spect::PeakFit::AddPeak (std::string peakKey, GamR::TK::PeakType peaktype)
Definition at line 1076 of file Fit.cc.
References AddPeak(), GamR::TK::Gaussian, GetNPeaks(), GamR::TK::OneTailGaussian, GamR::TK::OneTailStepGaussian, GamR::TK::StepGaussian, GamR::TK::TwoTailGaussian, and GamR::TK::TwoTailStepGaussian.
AddPeak() [3/3]
void GamR::Spect::PeakFit::AddPeak (std::string peakKey, GamR::TK::PeakType peaktype, double centroid)
Definition at line 1119 of file Fit.cc.
References AddPeak(), and SetCent().
Fit()
void GamR::Spect::PeakFit::Fit (TH1 * hist, Option_t * foption)
Definition at line 424 of file Fit.cc.
References GamR::TK::Gaussian, GamR::TK::OneTailGaussian, GamR::TK::OneTailStepGaussian, ss(), GamR::TK::StepGaussian, GamR::TK::TwoTailGaussian, and GamR::TK::TwoTailStepGaussian.
Referenced by GamR::Spect::FitPeaks().
FixPeakEnergy()
void GamR::Spect::PeakFit::FixPeakEnergy (std::string peakKey) inline
Definition at line 173 of file Fit.hh.
Get() [1/2]
GamR::TK::FPeak * GamR::Spect::PeakFit::Get (int i) inline
Definition at line 189 of file Fit.hh.
Get() [2/2]
GamR::TK::FPeak * GamR::Spect::PeakFit::Get (std::string peakKey) inline
Definition at line 188 of file Fit.hh.
GetAmp() [1/2]
double GamR::Spect::PeakFit::GetAmp (int i) inline
Definition at line 150 of file Fit.hh.
References GetAmp().
Referenced by GetAmp().
GetAmp() [2/2]
double GamR::Spect::PeakFit::GetAmp (std::string peakKey)
Definition at line 1125 of file Fit.cc.
GetAmpError() [1/2]
double GamR::Spect::PeakFit::GetAmpError (int i) inline
Definition at line 151 of file Fit.hh.
References GetAmpError().
Referenced by GetAmpError().
GetAmpError() [2/2]
double GamR::Spect::PeakFit::GetAmpError (std::string peakKey)
Definition at line 1129 of file Fit.cc.
GetArea() [1/2]
double GamR::Spect::PeakFit::GetArea (int i) inline
Definition at line 156 of file Fit.hh.
References GetArea().
Referenced by GetArea().
GetArea() [2/2]
double GamR::Spect::PeakFit::GetArea (std::string peakKey) inline
Definition at line 147 of file Fit.hh.
GetAreaError() [1/2]
double GamR::Spect::PeakFit::GetAreaError (int i) inline
Definition at line 157 of file Fit.hh.
References GetAreaError().
Referenced by GetAreaError().
GetAreaError() [2/2]
double GamR::Spect::PeakFit::GetAreaError (std::string peakKey) inline
Definition at line 148 of file Fit.hh.
GetBackground()
TF1 * GamR::Spect::PeakFit::GetBackground () inline
Definition at line 93 of file Fit.hh.
Referenced by GamR::Spect::FitPeaks().
GetCent() [1/2]
double GamR::Spect::PeakFit::GetCent (int i) inline
Definition at line 152 of file Fit.hh.
References GetCent().
Referenced by GetCent().
GetCent() [2/2]
double GamR::Spect::PeakFit::GetCent (std::string peakKey)
Definition at line 1133 of file Fit.cc.
GetCentError() [1/2]
double GamR::Spect::PeakFit::GetCentError (int i) inline
Definition at line 153 of file Fit.hh.
References GetCentError().
Referenced by GetCentError().
GetCentError() [2/2]
double GamR::Spect::PeakFit::GetCentError (std::string peakKey)
Definition at line 1137 of file Fit.cc.
GetChi2()
double GamR::Spect::PeakFit::GetChi2 () inline
Definition at line 95 of file Fit.hh.
GetFixWidths()
int GamR::Spect::PeakFit::GetFixWidths () inline
Definition at line 102 of file Fit.hh.
References GamR::Spect::PeakFit::Parameters::iFixWidths.
GetFunc()
TF1 * GamR::Spect::PeakFit::GetFunc (std::string peakKey) inline
Definition at line 201 of file Fit.hh.
Referenced by GetPeakBG().
GetHigh()
double GamR::Spect::PeakFit::GetHigh () inline
Definition at line 97 of file Fit.hh.
Referenced by GamR::Spect::FitPeaks().
GetLow()
double GamR::Spect::PeakFit::GetLow () inline
Definition at line 96 of file Fit.hh.
Referenced by GamR::Spect::FitPeaks().
GetNPeaks()
size_t GamR::Spect::PeakFit::GetNPeaks () inline
Definition at line 98 of file Fit.hh.
Referenced by AddPeak(), and ToText().
GetParamCount()
int GamR::Spect::PeakFit::GetParamCount () inline
Definition at line 100 of file Fit.hh.
GetPeakBG() [1/2]
TF1 * GamR::Spect::PeakFit::GetPeakBG (int i) inline
Definition at line 193 of file Fit.hh.
References GetPeakBG().
Referenced by GetPeakBG().
GetPeakBG() [2/2]
TF1 * GamR::Spect::PeakFit::GetPeakBG (std::string peakKey)
Definition at line 1490 of file Fit.cc.
References GetFunc().
Referenced by GamR::Spect::FitPeaks(), and ToText().
GetPeakGaussBG() [1/2]
TF1 * GamR::Spect::PeakFit::GetPeakGaussBG (int i) inline
Definition at line 199 of file Fit.hh.
References GetPeakGaussBG().
Referenced by GetPeakGaussBG().
GetPeakGaussBG() [2/2]
TF1 * GamR::Spect::PeakFit::GetPeakGaussBG (std::string peakKey)
Definition at line 1504 of file Fit.cc.
Referenced by GamR::Spect::FitPeaks().
GetPeaks()
std::map< std::string, GamR::TK::FPeak * > GamR::Spect::PeakFit::GetPeaks () inline
Definition at line 190 of file Fit.hh.
Referenced by GamR::Spect::FitPeaks().
GetPeakStepBG() [1/2]
TF1 * GamR::Spect::PeakFit::GetPeakStepBG (int i) inline
Definition at line 196 of file Fit.hh.
References GetPeakStepBG().
Referenced by GetPeakStepBG().
GetPeakStepBG() [2/2]
TF1 * GamR::Spect::PeakFit::GetPeakStepBG (std::string peakKey)
Definition at line 1519 of file Fit.cc.
Referenced by GamR::Spect::FitPeaks().
GetPeakType()
GamR::TK::PeakType GamR::Spect::PeakFit::GetPeakType () inline
Definition at line 92 of file Fit.hh.
Referenced by GamR::Spect::FitPeaks().
GetQuadBack()
int GamR::Spect::PeakFit::GetQuadBack () inline
Definition at line 103 of file Fit.hh.
References GamR::Spect::PeakFit::Parameters::iQuadBack.
GetSkew2Graph()
TGraph * GamR::Spect::PeakFit::GetSkew2Graph () inline
Definition at line 186 of file Fit.hh.
GetSkewAmp2Graph()
TGraph * GamR::Spect::PeakFit::GetSkewAmp2Graph () inline
Definition at line 185 of file Fit.hh.
GetSkewAmpGraph()
TGraph * GamR::Spect::PeakFit::GetSkewAmpGraph () inline
Definition at line 183 of file Fit.hh.
GetSkewGraph()
TGraph * GamR::Spect::PeakFit::GetSkewGraph () inline
Definition at line 184 of file Fit.hh.
GetStep()
int GamR::Spect::PeakFit::GetStep () inline
Definition at line 104 of file Fit.hh.
References GamR::Spect::PeakFit::Parameters::iStep.
GetStepGraph()
TGraph * GamR::Spect::PeakFit::GetStepGraph () inline
Definition at line 182 of file Fit.hh.
GetTails1()
int GamR::Spect::PeakFit::GetTails1 () inline
Definition at line 105 of file Fit.hh.
References GamR::Spect::PeakFit::Parameters::iTails1.
GetTails2()
int GamR::Spect::PeakFit::GetTails2 () inline
Definition at line 106 of file Fit.hh.
References GamR::Spect::PeakFit::Parameters::iTails2.
GetTotal()
TF1 * GamR::Spect::PeakFit::GetTotal () inline
Definition at line 94 of file Fit.hh.
Referenced by GamR::Spect::FitPeaks(), and GamR::Spect::FitPeaks().
GetWidth() [1/2]
double GamR::Spect::PeakFit::GetWidth (int i) inline
Definition at line 154 of file Fit.hh.
References GetWidth().
Referenced by GetWidth().
GetWidth() [2/2]
double GamR::Spect::PeakFit::GetWidth (std::string peakKey)
Definition at line 1141 of file Fit.cc.
GetWidthError() [1/2]
double GamR::Spect::PeakFit::GetWidthError (int i) inline
Definition at line 155 of file Fit.hh.
References GetWidthError().
Referenced by GetWidthError().
GetWidthError() [2/2]
double GamR::Spect::PeakFit::GetWidthError (std::string peakKey)
Definition at line 1145 of file Fit.cc.
GetWidthGraph()
TGraph * GamR::Spect::PeakFit::GetWidthGraph () inline
Definition at line 181 of file Fit.hh.
PrintResults()
void GamR::Spect::PeakFit::PrintResults ()
Definition at line 735 of file Fit.cc.
References GamR::Utils::wrresult().
Referenced by GamR::Spect::FitPeaks().
SetAmp() [1/2]
void GamR::Spect::PeakFit::SetAmp (int i, double amp) inline
Definition at line 166 of file Fit.hh.
References SetAmp().
Referenced by SetAmp().
SetAmp() [2/2]
void GamR::Spect::PeakFit::SetAmp (std::string peakKey, double amp)
Definition at line 1150 of file Fit.cc.
SetAmpError() [1/2]
void GamR::Spect::PeakFit::SetAmpError (int i, double error) inline
Definition at line 167 of file Fit.hh.
References SetAmpError().
Referenced by SetAmpError().
SetAmpError() [2/2]
void GamR::Spect::PeakFit::SetAmpError (std::string peakKey, double error)
Definition at line 1154 of file Fit.cc.
SetBackground()
void GamR::Spect::PeakFit::SetBackground ()
Definition at line 97 of file Fit.cc.
SetCent() [1/2]
void GamR::Spect::PeakFit::SetCent (int i, double centroid) inline
Definition at line 168 of file Fit.hh.
References SetCent().
Referenced by SetCent().
SetCent() [2/2]
void GamR::Spect::PeakFit::SetCent (std::string peakKey, double centroid)
Definition at line 1158 of file Fit.cc.
Referenced by AddPeak().
SetCentError() [1/2]
void GamR::Spect::PeakFit::SetCentError (int i, double error) inline
Definition at line 169 of file Fit.hh.
References SetCentError().
Referenced by SetCentError().
SetCentError() [2/2]
void GamR::Spect::PeakFit::SetCentError (std::string peakKey, double error)
Definition at line 1162 of file Fit.cc.
SetChi2()
void GamR::Spect::PeakFit::SetChi2 (double Chi2) inline
Definition at line 128 of file Fit.hh.
SetFixWidths()
void GamR::Spect::PeakFit::SetFixWidths (int i) inline
Definition at line 110 of file Fit.hh.
References GamR::Spect::PeakFit::Parameters::iFixWidths.
SetFunction()
void GamR::Spect::PeakFit::SetFunction ()
Definition at line 1174 of file Fit.cc.
References GamR::TK::Gaussian, GamR::Spect::PeakFit::Parameters::iConstantBack, GamR::Spect::PeakFit::Parameters::iFixWidthsFile, GamR::Spect::PeakFit::Parameters::iQuadBack, GamR::TK::OneTailGaussian, GamR::TK::OneTailStepGaussian, GamR::TK::StepGaussian, GamR::TK::TwoTailGaussian, and GamR::TK::TwoTailStepGaussian.
SetGuesses() [1/3]
void GamR::Spect::PeakFit::SetGuesses ()
Referenced by SetGuesses().
SetGuesses() [2/3]
void GamR::Spect::PeakFit::SetGuesses (TH1 * hist, std::map< std::string, double > Peaks, std::vector< std::string > FixPeaks = {})
Definition at line 325 of file Fit.cc.
References GamR::TK::OneTailGaussian, GamR::TK::OneTailStepGaussian, GamR::TK::StepGaussian, GamR::TK::TwoTailGaussian, and GamR::TK::TwoTailStepGaussian.
SetGuesses() [3/3]
void GamR::Spect::PeakFit::SetGuesses (TH1 * hist, std::map< std::string, GamR::TK::FPeak * > Peaks, std::vector< std::string > FixPeaks = {})
Definition at line 315 of file Fit.cc.
References SetGuesses().
SetHigh()
void GamR::Spect::PeakFit::SetHigh (double High) inline
Definition at line 127 of file Fit.hh.
SetIndices()
void GamR::Spect::PeakFit::SetIndices (std::map< std::string, GamR::TK::FPeak * > Peaks)
Definition at line 136 of file Fit.cc.
References GamR::TK::OneTailGaussian, GamR::TK::OneTailStepGaussian, GamR::TK::StepGaussian, GamR::TK::TwoTailGaussian, and GamR::TK::TwoTailStepGaussian.
SetLimit()
void GamR::Spect::PeakFit::SetLimit (std::string peakKey, std::string parameterKey, double lowerLimit, double upperLimit)
Definition at line 415 of file Fit.cc.
SetLow()
void GamR::Spect::PeakFit::SetLow (double Low) inline
Definition at line 126 of file Fit.hh.
SetOpts()
void GamR::Spect::PeakFit::SetOpts (Option_t * option)
Definition at line 38 of file Fit.cc.
References GamR::TK::Gaussian, GamR::TK::OneTailGaussian, GamR::TK::OneTailStepGaussian, GamR::TK::StepGaussian, GamR::TK::TwoTailGaussian, and GamR::TK::TwoTailStepGaussian.
SetParamCount()
void GamR::Spect::PeakFit::SetParamCount (int i) inline
Definition at line 108 of file Fit.hh.
SetPeaks() [1/2]
void GamR::Spect::PeakFit::SetPeaks (std::map< std::string, double > Peaks)
Definition at line 128 of file Fit.cc.
SetPeaks() [2/2]
void GamR::Spect::PeakFit::SetPeaks (std::vector< double > Peaks)
Definition at line 117 of file Fit.cc.
References SetPeaks().
Referenced by SetPeaks().
SetQuadBack()
void GamR::Spect::PeakFit::SetQuadBack (int i) inline
Definition at line 111 of file Fit.hh.
References GamR::Spect::PeakFit::Parameters::iQuadBack.
SetResults()
void GamR::Spect::PeakFit::SetResults (TH1 * hist)
Definition at line 540 of file Fit.cc.
References GamR::TK::Gaussian, GamR::TK::OneTailGaussian, GamR::TK::OneTailStepGaussian, GamR::TK::StepGaussian, GamR::TK::TwoTailGaussian, and GamR::TK::TwoTailStepGaussian.
Referenced by GamR::Spect::FitPeaks().
SetStep()
void GamR::Spect::PeakFit::SetStep (int i) inline
Definition at line 112 of file Fit.hh.
References GamR::Spect::PeakFit::Parameters::iStep.
SetTails1()
void GamR::Spect::PeakFit::SetTails1 (int i) inline
Definition at line 113 of file Fit.hh.
References GamR::Spect::PeakFit::Parameters::iTails1.
SetTails2()
void GamR::Spect::PeakFit::SetTails2 (int i) inline
Definition at line 114 of file Fit.hh.
References GamR::Spect::PeakFit::Parameters::iTails2.
SetUp()
void GamR::Spect::PeakFit::SetUp (TH1 * hist, std::map< std::string, double > Peaks, Option_t * option, std::vector< std::string > FixPeaks = {}) inline
Definition at line 129 of file Fit.hh.
Referenced by GamR::Spect::FitPeaks().
SetWidth() [1/2]
void GamR::Spect::PeakFit::SetWidth (int i, double width) inline
Definition at line 170 of file Fit.hh.
References SetWidth().
Referenced by SetWidth().
SetWidth() [2/2]
void GamR::Spect::PeakFit::SetWidth (std::string peakKey, double width)
Definition at line 1166 of file Fit.cc.
SetWidthError() [1/2]
void GamR::Spect::PeakFit::SetWidthError (int i, double error) inline
Definition at line 171 of file Fit.hh.
References SetWidthError().
Referenced by SetWidthError().
SetWidthError() [2/2]
void GamR::Spect::PeakFit::SetWidthError (std::string peakKey, double error)
Definition at line 1170 of file Fit.cc.
ToText()
void GamR::Spect::PeakFit::ToText (std::string filename, std::string delimiter = " ", int nPoints = 1000)
Definition at line 1534 of file Fit.cc.
References GetNPeaks(), and GetPeakBG().
Member Data Documentation
fFitGuesses
PeakFitGuesses* GamR::Spect::PeakFit::fFitGuesses
Definition at line 86 of file Fit.hh.
Referenced by PeakFit(), and PeakFit().
The documentation for this class was generated from the following files:
src/lib/spect/Fit.hh
src/lib/spect/Fit.cc