GamR: GamR::TK Namespace Reference
GamR::TK Namespace Reference
(Toolkit)
Classes
class BPeak
class FPeak
class Gate
class GateMap
class GaussianPeak
class OneTailGaussianPeak
class OneTailStepGaussianPeak
class Peak
class StepGaussianPeak
class TwoTailGaussianPeak
class TwoTailStepGaussianPeak
Enumerations
enum PeakType {
Gaussian , StepGaussian , OneTailGaussian , OneTailStepGaussian ,
TwoTailGaussian , TwoTailStepGaussian
}
Functions
Int_t GainMatchEnergy (TH1 *spec1, TH1 *spec2, std::vector< Double_t > &pars, bool draw, UInt_t target, std::string outfn, Double_t step, TCanvas *c1)
template<size_t Meas, class TDetector>
Bool_t PassDetector (TDetector det, Bool_t calibrated, Int_t id)
std::ostream & operator<< (std::ostream &os, Gate const &g)
int GetZA (std::string Nuclide, int &Z, double &A)
std::string GetElement (int Z, float A)
std::shared_ptr< TH2D > MonteCarlo (std::function< std::pair< double, double >(TH1 *, TRandom3 &)> func, TH1 *system, size_t ntoys, Bool_t draw, const Bool_t weight, TCanvas *c1)
BPeak * FitBPeak (TCanvas *canvas, Option_t *foption, Option_t *option)
BPeak * ClickBPeak (TCanvas *canvas)
Variables
const std::string Elements [93] { "n", "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K", "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr", "Rb", "Sr", "Y", "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te", "I", "Xe", "Cs", "Ba", "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu", "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra", "Ac", "Th", "Pa", "U" }
Detailed Description
Library for low-level but user-focused analysis. A toolbox for generally useful physics analysis tools.
Function Documentation
GainMatchEnergy()
Int_t GamR::TK::GainMatchEnergy (TH1 * spec1, TH1 * spec2, std::vector< Double_t > & pars, bool draw, UInt_t target, std::string outfn, Double_t step, TCanvas * c1)
Definition at line 22 of file Gain.cc.
References ss().
Referenced by main().
GetElement()
std::string GamR::TK::GetElement (int Z, float A)
Definition at line 54 of file Misc.cc.
References Elements.
Referenced by GamR::Coulex::CoulexCalculation::Print(), GamR::Coulex::CoulexCalculation::SaveToFile(), GamR::Coulex::CoulexCalculation::SetBeam(), and GamR::Coulex::CoulexCalculation::SetTarget().
GetZA()
int GamR::TK::GetZA (std::string Nuclide, int & Z, double & A)
Definition at line 9 of file Misc.cc.
References Elements.
Referenced by GamR::Coulex::CoulexCalculation::ReadFromFile(), GamR::Coulex::CoulexCalculation::SetBeam(), GamR::Coulex::CoulexCalculation::SetBeam(), GamR::Coulex::CoulexCalculation::SetTarget(), and GamR::Coulex::CoulexCalculation::SetTarget().
MonteCarlo()
std::shared_ptr< TH2D > GamR::TK::MonteCarlo (std::function< std::pair< double, double >(TH1 *, TRandom3 &)> func, TH1 * system, size_t ntoys, Bool_t draw, const Bool_t weight, TCanvas * c1)
Definition at line 9 of file MonteCarlo.cc.
Referenced by GamR::Processor::TimeWalk::MakeGraphs().
PassDetector()
template<size_t Meas, class TDetector> Bool_t GamR::TK::PassDetector (TDetector det, Bool_t calibrated, Int_t id)
Parameters
[in] Meas Templated argument, the measurement number of the TDetector object passed.
[in] det The TDetector in question, template type should be automatically deduced by this argument.
[in] calibrated Use detectors calibrated measurement.
[in] id If positive, match ID number.
Returns
Whether the detectors measurement sits within this gate.
Definition at line 179 of file Gate.cc.
Variable Documentation
Elements
const std::string GamR::TK::Elements[93] { "n", "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K", "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr", "Rb", "Sr", "Y", "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te", "I", "Xe", "Cs", "Ba", "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu", "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra", "Ac", "Th", "Pa", "U" }
Definition at line 6 of file Misc.hh.
Referenced by GetElement(), and GetZA().