GamR: GamR::Coulex Namespace Reference
GamR::Coulex Namespace Reference
Namespaces
namespace WDB
Classes
class CoulexCalculation
class Level
class LevelScheme
struct Nucleus
class ParticleDetector
struct Target
class Transition
struct WDB_nuclvl
struct WDB_nuctrans
Enumerations
enum Species { kNone = 0 , kProjectile = 1 , kTarget = 2 }
Functions
int Kinematics (double A1I, double A2I, double A3I, double A4I, double E1I, double QEFFI, double PSII, double &E3I, double &E3AI, double &E4I, double &E4AI, double &ZETAI, double &ZETAAI, double &thetaI, double &thetaaI, double &PHII, double &PHIAI)
double xcmlr (double anglab, double angCM, double Ap, double At, double Ep, double Q, bool Tgtex)
int MakeDatafile (int Zbeam, float Abeam, int Ztgt, float Atgt, int grouptype, std::vector< WDB_nuclvl > &nuclvls, std::vector< WDB_nuctrans > &nucEtrans, std::vector< WDB_nuctrans > &nucMtrans, std::string filename)
int ReadDatafile (std::string datafile)
int setupcoulex (int Zbeam, float Abeam, int Ztgt, float Atgt, int grouptype, std::vector< WDB_nuclvl > &nuclvls, std::vector< WDB_nuctrans > &nucEtrans, std::vector< WDB_nuctrans > &nucMtrans)
void GP_AC_Tensors (float Ebeam, float CMAng, int lvl, std::complex< double > **rho, float &xsect)
void DrawSetup ()
GamR::Coulex::CoulexCalculation ExperimentalSetup (std::string file_name)
GamR::AngDist::StatTensor * DoCoulex (std::string file_name)
void loadSCOEF ()
double S_e (double E, int Zb, int Zt)
double S_n (double E, int Zb, int Zt, double Mb=0, double Mt=0)
double dEdx (double E, int Zb, int Zt, double Mb=0, double Mt=0)
double ELoss (double E, int Zb, int Zt, double Tt, double Mb=0, double *ttime=nullptr, double *range=nullptr, double Mt=0, double denst=0, long acc=1000)
Variables
const double rad2deg = 360. / 2. / TMath::Pi()
bool SCOEFloaded
double Eldat [92][5]
Enumeration Type Documentation
Species
enum GamR::Coulex::Species
Enum for excited/detected species
Enumerator
kNone
kProjectile
kTarget
Definition at line 50 of file CoulexCalculation.hh.
Function Documentation
dEdx()
double GamR::Coulex::dEdx (double E, int Zb, int Zt, double Mb = 0, double Mt = 0)
DoCoulex()
GamR::AngDist::StatTensor * GamR::Coulex::DoCoulex (std::string file_name)
Definition at line 1154 of file CoulexCalculation.cc.
References GamR::Coulex::CoulexCalculation::CalcTensor(), GamR::Coulex::CoulexCalculation::ExperimentalSetup(), GamR::Coulex::CoulexCalculation::Print(), GamR::Coulex::CoulexCalculation::ReadFromFile(), and GamR::Coulex::CoulexCalculation::SaveToFile().
DrawSetup()
void GamR::Coulex::DrawSetup ()
Definition at line 336 of file Coulex.cc.
Referenced by GamR::Coulex::CoulexCalculation::SetParticleDet().
ELoss()
double GamR::Coulex::ELoss (double E, int Zb, int Zt, double Tt, double Mb = 0, double * ttime = nullptr, double * range = nullptr, double Mt = 0, double denst = 0, long acc = 1000)
Referenced by GamR::Coulex::CoulexCalculation::CalcTensor().
ExperimentalSetup()
GamR::Coulex::CoulexCalculation GamR::Coulex::ExperimentalSetup (std::string file_name)
Definition at line 1145 of file CoulexCalculation.cc.
References GamR::Coulex::CoulexCalculation::ExperimentalSetup(), GamR::Coulex::CoulexCalculation::Print(), GamR::Coulex::CoulexCalculation::ReadFromFile(), and GamR::Coulex::CoulexCalculation::SaveToFile().
GP_AC_Tensors()
void GamR::Coulex::GP_AC_Tensors (float Ebeam, float CMAng, int lvl, std::complex< double > ** rho, float & xsect)
Definition at line 317 of file Coulex.cc.
References GamR::Coulex::WDB::coulex_(), GamR::Coulex::WDB::coulparcm_(), and GamR::Coulex::WDB::getcoulex_().
Kinematics()
int GamR::Coulex::Kinematics (double A1I, double A2I, double A3I, double A4I, double E1I, double QEFFI, double PSII, double & E3I, double & E3AI, double & E4I, double & E4AI, double & ZETAI, double & ZETAAI, double & thetaI, double & thetaaI, double & PHII, double & PHIAI)
Routine to get reaction kinematics based on Marion and Young's solutions, writted in FORTRAN by A.E. Stuchbery.
Parameters
A1I projectile mass
A2I target mass
A3I light recoil mass
A4I heavy recoil mass
E1I projectile energy
QEFFI reaction energy
PSII light recoil angle
E3I light mass energy (output)
E3AI alternative solution (output)
E4I heavy mass energy (output)
E4AI alerternative solution (output)
ZETAI heavy recoil angle (output)
ZETAAI alternative solution (output)
thetaI light CM angle (output)
thetaI alternative solution (output)
PHII heavy CM angle (output)
PHIAI alternative solution (output)
Returns
1 = unique solution, 0 = two solutions, -1 = bad light recoil angle
Definition at line 50 of file Coulex.cc.
loadSCOEF()
void GamR::Coulex::loadSCOEF ()
Referenced by GamR::Coulex::CoulexCalculation::CalcTensor(), GamR::Coulex::CoulexCalculation::ReadFromFile(), GamR::Coulex::CoulexCalculation::SetBeam(), and GamR::Coulex::CoulexCalculation::SetTarget().
MakeDatafile()
int GamR::Coulex::MakeDatafile (int Zbeam, float Abeam, int Ztgt, float Atgt, int grouptype, std::vector< WDB_nuclvl > & nuclvls, std::vector< WDB_nuctrans > & nucEtrans, std::vector< WDB_nuctrans > & nucMtrans, std::string filename)
Definition at line 229 of file Coulex.cc.
Referenced by setupcoulex().
ReadDatafile()
int GamR::Coulex::ReadDatafile (std::string datafile)
Definition at line 287 of file Coulex.cc.
References GamR::Utils::c_to_f_str(), GamR::Coulex::WDB::freader_(), and GamR::Coulex::WDB::setup_coulex_().
Referenced by setupcoulex().
S_e()
double GamR::Coulex::S_e (double E, int Zb, int Zt)
S_n()
double GamR::Coulex::S_n (double E, int Zb, int Zt, double Mb = 0, double Mt = 0)
setupcoulex()
int GamR::Coulex::setupcoulex (int Zbeam, float Abeam, int Ztgt, float Atgt, int grouptype, std::vector< WDB_nuclvl > & nuclvls, std::vector< WDB_nuctrans > & nucEtrans, std::vector< WDB_nuctrans > & nucMtrans)
Definition at line 304 of file Coulex.cc.
References MakeDatafile(), and ReadDatafile().
Referenced by GamR::Coulex::CoulexCalculation::CalcTensor().
xcmlr()
double GamR::Coulex::xcmlr (double anglab, double angCM, double Ap, double At, double Ep, double Q, bool Tgtex)
Definition at line 182 of file Coulex.cc.
Variable Documentation
Eldat
double GamR::Coulex::Eldat[92][5] extern
Referenced by GamR::Coulex::CoulexCalculation::CalcTensor(), GamR::Coulex::CoulexCalculation::ReadFromFile(), GamR::Coulex::CoulexCalculation::SetBeam(), and GamR::Coulex::CoulexCalculation::SetTarget().
rad2deg
const double GamR::Coulex::rad2deg = 360. / 2. / TMath::Pi()
Definition at line 21 of file Coulex.hh.
SCOEFloaded
bool GamR::Coulex::SCOEFloaded extern
Referenced by GamR::Coulex::CoulexCalculation::CalcTensor(), GamR::Coulex::CoulexCalculation::ReadFromFile(), GamR::Coulex::CoulexCalculation::SetBeam(), and GamR::Coulex::CoulexCalculation::SetTarget().