GamR: GamR::Nucleus::LevelSchemeFitter::Scheme Class Reference
GamR::Nucleus::LevelSchemeFitter::Scheme Class Reference
#include <LevelSchemeFitter.hh>
Classes
class GlobalChiSquare
Public Member Functions
Scheme ()
Scheme (std::string name)
State * GetStateByIndex (int i)
void AddState (std::string name, double energy, EColor color=kBlack)
void SetIndices ()
void AddTransition (std::string initState, std::string finState, double energy, double uncertainty, EColor color=kBlack)
void SetDrawRange (double eLow, double eHigh)
double GetChiSquared ()
void Fit ()
void PrintStates ()
void PrintTransitions ()
void Print ()
void SaveTable (std::string filename)
void PrintState (std::string name)
void Paint (Option_t *option="")
ClassDef (Scheme, 1)
Public Attributes
std::map< std::string, State > fStates
std::vector< Transition > fTransitions
double drawLow = 0
double drawHigh = 1e9
TH2F * fDrawHist = NULL
TGaxis * fAxis = NULL
Detailed Description
Definition at line 56 of file LevelSchemeFitter.hh.
Constructor & Destructor Documentation
Scheme() [1/2]
GamR::Nucleus::LevelSchemeFitter::Scheme::Scheme () inline
Definition at line 64 of file LevelSchemeFitter.hh.
References drawHigh, drawLow, and fDrawHist.
Referenced by GamR::Nucleus::LevelSchemeFitter::Scheme::GlobalChiSquare::GlobalChiSquare(), and ClassDef().
Scheme() [2/2]
GamR::Nucleus::LevelSchemeFitter::Scheme::Scheme (std::string name) inline
Definition at line 65 of file LevelSchemeFitter.hh.
References drawHigh, drawLow, and fDrawHist.
Member Function Documentation
AddState()
void GamR::Nucleus::LevelSchemeFitter::Scheme::AddState (std::string name, double energy, EColor color = kBlack) inline
Definition at line 67 of file LevelSchemeFitter.hh.
References fStates.
AddTransition()
void GamR::Nucleus::LevelSchemeFitter::Scheme::AddTransition (std::string initState, std::string finState, double energy, double uncertainty, EColor color = kBlack) inline
Definition at line 69 of file LevelSchemeFitter.hh.
References fStates, and fTransitions.
ClassDef()
GamR::Nucleus::LevelSchemeFitter::Scheme::ClassDef (Scheme , 1)
References Scheme().
Fit()
void GamR::Nucleus::LevelSchemeFitter::Scheme::Fit ()
Definition at line 219 of file LevelSchemeFitter.cc.
References GamR::Nucleus::LevelSchemeFitter::State::fEnergy, fStates, GamR::Nucleus::LevelSchemeFitter::State::fUncertainty, GetStateByIndex(), and GamR::Nucleus::LevelSchemeFitter::Scheme::GlobalChiSquare::minuit().
GetChiSquared()
double GamR::Nucleus::LevelSchemeFitter::Scheme::GetChiSquared ()
Definition at line 186 of file LevelSchemeFitter.cc.
References fTransitions.
Referenced by Print().
GetStateByIndex()
State * GamR::Nucleus::LevelSchemeFitter::Scheme::GetStateByIndex (int i)
Definition at line 177 of file LevelSchemeFitter.cc.
References fStates.
Referenced by Fit(), Paint(), and SaveTable().
Paint()
void GamR::Nucleus::LevelSchemeFitter::Scheme::Paint (Option_t * option = "")
Definition at line 328 of file LevelSchemeFitter.cc.
References drawHigh, drawLow, fAxis, fDrawHist, GamR::Nucleus::LevelSchemeFitter::State::fDrawPos, GamR::Nucleus::LevelSchemeFitter::State::fEnergy, GamR::Nucleus::LevelSchemeFitter::State::fLabelPos, fStates, fTransitions, GetStateByIndex(), GamR::Nucleus::LevelSchemeFitter::State::index, and SetIndices().
Print()
void GamR::Nucleus::LevelSchemeFitter::Scheme::Print ()
Definition at line 295 of file LevelSchemeFitter.cc.
References fStates, fTransitions, GetChiSquared(), PrintStates(), and PrintTransitions().
PrintState()
void GamR::Nucleus::LevelSchemeFitter::Scheme::PrintState (std::string name)
Definition at line 309 of file LevelSchemeFitter.cc.
References fStates, and fTransitions.
PrintStates()
void GamR::Nucleus::LevelSchemeFitter::Scheme::PrintStates ()
Definition at line 269 of file LevelSchemeFitter.cc.
References fStates.
Referenced by Print().
PrintTransitions()
void GamR::Nucleus::LevelSchemeFitter::Scheme::PrintTransitions ()
Definition at line 288 of file LevelSchemeFitter.cc.
References fTransitions.
Referenced by Print().
SaveTable()
void GamR::Nucleus::LevelSchemeFitter::Scheme::SaveTable (std::string filename)
Definition at line 467 of file LevelSchemeFitter.cc.
References fStates, fTransitions, GetStateByIndex(), SetIndices(), and GamR::Utils::wrresult().
SetDrawRange()
void GamR::Nucleus::LevelSchemeFitter::Scheme::SetDrawRange (double eLow, double eHigh) inline
Definition at line 74 of file LevelSchemeFitter.hh.
References drawHigh, and drawLow.
SetIndices()
void GamR::Nucleus::LevelSchemeFitter::Scheme::SetIndices ()
Definition at line 160 of file LevelSchemeFitter.cc.
References fStates.
Referenced by Paint(), and SaveTable().
Member Data Documentation
drawHigh
double GamR::Nucleus::LevelSchemeFitter::Scheme::drawHigh = 1e9
Definition at line 61 of file LevelSchemeFitter.hh.
Referenced by Scheme(), Scheme(), Paint(), and SetDrawRange().
drawLow
double GamR::Nucleus::LevelSchemeFitter::Scheme::drawLow = 0
Definition at line 60 of file LevelSchemeFitter.hh.
Referenced by Scheme(), Scheme(), Paint(), and SetDrawRange().
fAxis
TGaxis* GamR::Nucleus::LevelSchemeFitter::Scheme::fAxis = NULL
Definition at line 63 of file LevelSchemeFitter.hh.
Referenced by Paint().
fDrawHist
TH2F* GamR::Nucleus::LevelSchemeFitter::Scheme::fDrawHist = NULL
Definition at line 62 of file LevelSchemeFitter.hh.
Referenced by Scheme(), Scheme(), and Paint().
fStates
std::map<std::string, State> GamR::Nucleus::LevelSchemeFitter::Scheme::fStates
Definition at line 58 of file LevelSchemeFitter.hh.
Referenced by AddState(), AddTransition(), Fit(), GetStateByIndex(), Paint(), Print(), PrintState(), PrintStates(), SaveTable(), and SetIndices().
fTransitions
std::vector<Transition> GamR::Nucleus::LevelSchemeFitter::Scheme::fTransitions
Definition at line 59 of file LevelSchemeFitter.hh.
Referenced by AddTransition(), GetChiSquared(), Paint(), Print(), PrintState(), PrintTransitions(), and SaveTable().
The documentation for this class was generated from the following files:
src/lib/nucleus/LevelSchemeFitter.hh
src/lib/nucleus/LevelSchemeFitter.cc