GamR: GamR::Nucleus::Transition Class Reference
GamR::Nucleus::Transition Class Reference
#include <Transition.hh>
Public Member Functions
Transition (double E=0, double PL=0, double PH=4096, double BL=0, double BH=4096)
void SetEnergy (double E)
void SetPeak ()
void SetPeak (double Low, double High)
void SetBackground ()
void SetBackground (double Low, double High)
void AddBackground ()
void AddBackground (double Low, double High)
void SetTransition ()
double Apply (TH1D *hist) const
double ApplyError (TH1D *hist) const
double ApplyCounts (TH1D *hist) const
double ApplyCountsError (TH1D *hist) const
double GetEnergy ()
const GamR::TK::Gate * GetGate () const
const GamR::TK::Gate * GetGateBG () const
const std::vector< GamR::TK::Gate > * GetGateBGs () const
ClassDef (Transition, 2)
Protected Attributes
GamR::TK::Gate fPeak
std::vector< GamR::TK::Gate > fBackground
double fEnergy = 0
Detailed Description
Definition at line 18 of file Transition.hh.
Constructor & Destructor Documentation
Transition()
GamR::Nucleus::Transition::Transition (double E = 0, double PL = 0, double PH = 4096, double BL = 0, double BH = 4096) inline
Definition at line 24 of file Transition.hh.
References fBackground.
Member Function Documentation
AddBackground() [1/2]
void GamR::Nucleus::Transition::AddBackground ()
Definition at line 5 of file Transition.cc.
References fBackground, and GamR::TK::Gate::SetGate().
Referenced by GamR::Spect::CountsBS().
AddBackground() [2/2]
void GamR::Nucleus::Transition::AddBackground (double Low, double High)
Definition at line 11 of file Transition.cc.
References GamR::TK::Gate::SetGate().
Apply()
double GamR::Nucleus::Transition::Apply (TH1D * hist) const
Definition at line 53 of file Transition.cc.
Referenced by GamR::Spect::IntegralBS(), and GamR::AngDist::AngCorrFit::SetData().
ApplyCounts()
double GamR::Nucleus::Transition::ApplyCounts (TH1D * hist) const
Definition at line 59 of file Transition.cc.
Referenced by GamR::Spect::CountsBS().
ApplyCountsError()
double GamR::Nucleus::Transition::ApplyCountsError (TH1D * hist) const
Definition at line 62 of file Transition.cc.
Referenced by GamR::Spect::CountsBS().
ApplyError()
double GamR::Nucleus::Transition::ApplyError (TH1D * hist) const
Definition at line 56 of file Transition.cc.
Referenced by GamR::Spect::IntegralBS(), and GamR::AngDist::AngCorrFit::SetData().
ClassDef()
GamR::Nucleus::Transition::ClassDef (Transition , 2)
GetEnergy()
double GamR::Nucleus::Transition::GetEnergy () inline
Definition at line 38 of file Transition.hh.
References fEnergy.
GetGate()
const GamR::TK::Gate * GamR::Nucleus::Transition::GetGate () const inline
Definition at line 39 of file Transition.hh.
References fPeak.
Referenced by GamR::Spect::BackgroundSubtractX(), GamR::Spect::BackgroundSubtractX(), GamR::Spect::BackgroundSubtractY(), GamR::Spect::BackgroundSubtractY(), GamR::AngDist::RatioFunction(), and GamR::AngDist::RatioFunction().
GetGateBG()
const GamR::TK::Gate * GamR::Nucleus::Transition::GetGateBG () const inline
Definition at line 40 of file Transition.hh.
References fBackground.
Referenced by GamR::Spect::BackgroundSubtractX(), GamR::Spect::BackgroundSubtractX(), GamR::Spect::BackgroundSubtractY(), GamR::Spect::BackgroundSubtractY(), GamR::AngDist::RatioFunction(), and GamR::AngDist::RatioFunction().
GetGateBGs()
const std::vector< GamR::TK::Gate > * GamR::Nucleus::Transition::GetGateBGs () const inline
Definition at line 41 of file Transition.hh.
References fBackground.
SetBackground() [1/2]
void GamR::Nucleus::Transition::SetBackground () inline
Definition at line 29 of file Transition.hh.
References fBackground, and GamR::TK::Gate::SetGate().
Referenced by SetTransition().
SetBackground() [2/2]
void GamR::Nucleus::Transition::SetBackground (double Low, double High) inline
Definition at line 30 of file Transition.hh.
References fBackground, and GamR::TK::Gate::SetGate().
SetEnergy()
void GamR::Nucleus::Transition::SetEnergy (double E) inline
Definition at line 26 of file Transition.hh.
References fEnergy.
SetPeak() [1/2]
void GamR::Nucleus::Transition::SetPeak () inline
Definition at line 27 of file Transition.hh.
References fPeak, and GamR::TK::Gate::SetGate().
Referenced by SetTransition().
SetPeak() [2/2]
void GamR::Nucleus::Transition::SetPeak (double Low, double High) inline
Definition at line 28 of file Transition.hh.
References fPeak, and GamR::TK::Gate::SetGate().
SetTransition()
void GamR::Nucleus::Transition::SetTransition () inline
Definition at line 33 of file Transition.hh.
References SetBackground(), and SetPeak().
Referenced by GamR::Spect::CountsBS(), and GamR::Spect::IntegralBS().
Member Data Documentation
fBackground
std::vector<GamR::TK::Gate> GamR::Nucleus::Transition::fBackground protected
Definition at line 21 of file Transition.hh.
Referenced by Transition(), AddBackground(), GetGateBG(), GetGateBGs(), SetBackground(), and SetBackground().
fEnergy
double GamR::Nucleus::Transition::fEnergy = 0 protected
Definition at line 22 of file Transition.hh.
Referenced by GetEnergy(), GamR::Nucleus::Photon::operator<(), GamR::Nucleus::Photon::operator==(), and SetEnergy().
fPeak
GamR::TK::Gate GamR::Nucleus::Transition::fPeak protected
Definition at line 20 of file Transition.hh.
Referenced by GetGate(), SetPeak(), and SetPeak().
The documentation for this class was generated from the following files:
src/lib/nucleus/Transition.hh
src/lib/nucleus/Transition.cc