GamR: GamR::Bateman::Scheme Class Reference
GamR::Bateman::Scheme Class Reference
#include <Scheme.hh>
Public Member Functions
void AddNucleus (std::string n, double lt, double eff, double lt_err, double eff_err, double N0)
void ReadScheme (std::string f)
void NormBranches ()
void NormN0 ()
void operator() (const std::vector< double > &x, std::vector< double > &dxdt, const double)
void PrintSummary (std::ostream &stream)
void PrintPops (std::ostream &stream, Solver &solver)
void PrintDecays (std::ostream &stream, Solver &solver)
double GetTotal (double t, Solver &solver)
double Get (int indx, double t, Solver &solver)
Public Attributes
std::vector< Nucleus * > nuclei
Detailed Description
Definition at line 13 of file Scheme.hh.
Member Function Documentation
AddNucleus()
void GamR::Bateman::Scheme::AddNucleus (std::string n, double lt, double eff, double lt_err, double eff_err, double N0) inline
Definition at line 17 of file Scheme.hh.
References nuclei.
Referenced by ReadScheme().
Get()
double GamR::Bateman::Scheme::Get (int indx, double t, Solver & solver)
Definition at line 192 of file Scheme.cc.
References GamR::Bateman::Solver::max_time, nuclei, and GamR::Bateman::Solver::stepsize.
GetTotal()
double GamR::Bateman::Scheme::GetTotal (double t, Solver & solver)
Definition at line 170 of file Scheme.cc.
References GamR::Bateman::Solver::max_time, nuclei, and GamR::Bateman::Solver::stepsize.
NormBranches()
void GamR::Bateman::Scheme::NormBranches ()
Definition at line 77 of file Scheme.cc.
References nuclei.
Referenced by ReadScheme().
NormN0()
void GamR::Bateman::Scheme::NormN0 ()
Definition at line 67 of file Scheme.cc.
References nuclei.
Referenced by ReadScheme().
operator()()
void GamR::Bateman::Scheme::operator() (const std::vector< double > & x, std::vector< double > & dxdt, const double)
Definition at line 127 of file Scheme.cc.
References nuclei.
PrintDecays()
void GamR::Bateman::Scheme::PrintDecays (std::ostream & stream, Solver & solver)
Definition at line 156 of file Scheme.cc.
References GamR::Bateman::Solver::max_time, nuclei, and GamR::Bateman::Solver::stepsize.
PrintPops()
void GamR::Bateman::Scheme::PrintPops (std::ostream & stream, Solver & solver)
Definition at line 142 of file Scheme.cc.
References GamR::Bateman::Solver::max_time, nuclei, and GamR::Bateman::Solver::stepsize.
PrintSummary()
void GamR::Bateman::Scheme::PrintSummary (std::ostream & stream)
Definition at line 136 of file Scheme.cc.
References nuclei.
ReadScheme()
void GamR::Bateman::Scheme::ReadScheme (std::string f)
Definition at line 6 of file Scheme.cc.
References AddNucleus(), NormBranches(), NormN0(), nuclei, and ss().
Member Data Documentation
nuclei
std::vector<Nucleus*> GamR::Bateman::Scheme::nuclei
Definition at line 15 of file Scheme.hh.
Referenced by AddNucleus(), Get(), GetTotal(), NormBranches(), NormN0(), operator()(), PrintDecays(), PrintPops(), PrintSummary(), ReadScheme(), and GamR::Bateman::Solver::solve().
The documentation for this class was generated from the following files:
src/lib/bateman/Scheme.hh
src/lib/bateman/Scheme.cc