GamR: (Toolkit)
(Toolkit)
Namespaces
namespace GamR::TK
Classes
class GamR::TK::Gate
class GamR::TK::GateMap
class GamR::TK::Peak
class GamR::TK::BPeak
class GamR::TK::FPeak
class GamR::TK::GaussianPeak
class GamR::TK::StepGaussianPeak
class GamR::TK::OneTailGaussianPeak
class GamR::TK::OneTailStepGaussianPeak
class GamR::TK::TwoTailGaussianPeak
class GamR::TK::TwoTailStepGaussianPeak
Enumerations
enum GamR::TK::PeakType {
GamR::TK::Gaussian , GamR::TK::StepGaussian , GamR::TK::OneTailGaussian , GamR::TK::OneTailStepGaussian ,
GamR::TK::TwoTailGaussian , GamR::TK::TwoTailStepGaussian
}
Functions
GamR::TK::Gate::Gate ()
GamR::TK::Gate::Gate (const char *name)
GamR::TK::Gate::Gate (const char *name, const char *title)
GamR::TK::Gate::Gate (const char *name, TVirtualPad *canvas, Option_t *opt="")
GamR::TK::Gate::Gate (const char *name, const char *title, TVirtualPad *canvas, Option_t *opt="")
GamR::TK::Gate::Gate (TVirtualPad *canvas, Option_t *opt="")
GamR::TK::Gate::Gate (double l, double h)
GamR::TK::Gate::~Gate ()
void GamR::TK::Gate::GetClick (Int_t, Int_t, Int_t, TObject *selected)
int GamR::TK::Gate::SetGate ()
int GamR::TK::Gate::SetGate (TVirtualPad *canvas, Option_t *opt="")
void GamR::TK::Gate::SetGate (double l, double h)
void GamR::TK::Gate::SetLow (double l)
void GamR::TK::Gate::SetLow (std::string l)
void GamR::TK::Gate::SetHigh (double h)
void GamR::TK::Gate::SetHigh (std::string h)
void GamR::TK::Gate::SetScale (double s)
double GamR::TK::Gate::GetLow () const
double GamR::TK::Gate::GetHigh () const
double GamR::TK::Gate::GetWidth () const
int GamR::TK::Gate::GetBinLow (TH1 *hist) const
int GamR::TK::Gate::GetBinHigh (TH1 *hist) const
int GamR::TK::Gate::GetBinWidth (TH1 *hist) const
double GamR::TK::Gate::GetTrueWidth (TH1 *hist) const
double GamR::TK::Gate::GetIntegral (TH1 *hist) const
double GamR::TK::Gate::GetIntegral (TH1 *hist, Gate background) const
double GamR::TK::Gate::GetIntegral (TH1 *hist, Gate backLow, Gate backHigh) const
double GamR::TK::Gate::GetIntegral (TH1 *hist, std::vector< Gate > background) const
double GamR::TK::Gate::GetIntegralError (TH1 *hist) const
double GamR::TK::Gate::GetIntegralError (TH1 *hist, Gate background) const
double GamR::TK::Gate::GetIntegralError (TH1 *hist, std::vector< Gate > background) const
double GamR::TK::Gate::GetCounts (TH1 *hist) const
double GamR::TK::Gate::GetCounts (TH1 *hist, Gate background) const
double GamR::TK::Gate::GetCounts (TH1 *hist, std::vector< Gate > background) const
double GamR::TK::Gate::GetCountsError (TH1 *hist) const
double GamR::TK::Gate::GetCountsError (TH1 *hist, Gate background) const
double GamR::TK::Gate::GetCountsError (TH1 *hist, std::vector< Gate > background) const
void GamR::TK::Gate::Browse (TBrowser *b)
Bool_t GamR::TK::Gate::Pass (double x)
Bool_t GamR::TK::Gate::Pass (double x) const
template<size_t Meas, class TDetector>
Bool_t GamR::TK::Gate::PassDetector (TDetector det, Bool_t calibrated=kTRUE, Int_t id=-1)
TH1D * GamR::TK::Gate::ApplyX (TH2 *hist) const
TH1D * GamR::TK::Gate::ApplyX (TH2 *hist, const char *name) const
TH1D * GamR::TK::Gate::ApplyY (TH2 *hist) const
TH1D * GamR::TK::Gate::ApplyY (TH2 *hist, const char *name) const
void GamR::TK::Gate::Norm (TH1 *hist, TH1 *ref)
void GamR::TK::Gate::NormBackSub (TH1 *hist, TH1 *ref, Gate background)
void GamR::TK::Gate::Paint (Option_t *option="same")
Int_t GamR::TK::Gate::DistancetoPrimitive (Int_t px, Int_t py)
void GamR::TK::Gate::ExecuteEvent (Int_t event, Int_t px, Int_t py)
Bool_t GamR::TK::Gate::IsFolder () const
void GamR::TK::Gate::ls (Option_t *option="") const
Bool_t GamR::TK::Gate::Valid ()
std::ostream & GamR::TK::operator<< (std::ostream &os, Gate const &g)
GamR::TK::GateMap::GateMap ()
GamR::TK::GateMap::GateMap (const char *name)
GamR::TK::GateMap::GateMap (const char *name, const char *title)
Gate & GamR::TK::GateMap::operator[] (std::string key)
Bool_t GamR::TK::GateMap::IsFolder () const
void GamR::TK::GateMap::Browse (TBrowser *b)
void GamR::TK::GateMap::ls (Option_t *option="") const
Bool_t GamR::TK::GateMap::PassAny (double x) const
virtual double GamR::TK::Peak::GetArea ()
virtual double GamR::TK::Peak::GetAreaError ()
virtual double GamR::TK::Peak::GetAmp ()
virtual double GamR::TK::Peak::GetAmpError ()
virtual double GamR::TK::Peak::GetCent ()
virtual double GamR::TK::Peak::GetCentError ()
virtual double GamR::TK::Peak::GetWidth ()
virtual double GamR::TK::Peak::GetWidthError ()
virtual void GamR::TK::Peak::SetAmp (double amp)
virtual void GamR::TK::Peak::SetAmpError (double error)
virtual void GamR::TK::Peak::SetCent (double cent)
virtual void GamR::TK::Peak::SetCentError (double error)
virtual void GamR::TK::Peak::SetWidth (double width)
virtual void GamR::TK::Peak::SetWidthError (double error)
GamR::TK::BPeak::LFit::LFit (TH1D *background)
double GamR::TK::BPeak::LFit::operator() (double *x, double *p)
GamR::TK::BPeak::BPeak ()
GamR::TK::BPeak::~BPeak ()
double GamR::TK::BPeak::GetArea ()
double GamR::TK::BPeak::GetAreaError ()
double GamR::TK::BPeak::GetCounts ()
double GamR::TK::BPeak::GetCountsError ()
double GamR::TK::BPeak::GetAmp ()
double GamR::TK::BPeak::GetAmpError ()
double GamR::TK::BPeak::GetCent ()
double GamR::TK::BPeak::GetCentError ()
double GamR::TK::BPeak::GetWidth ()
double GamR::TK::BPeak::GetWidthError ()
void GamR::TK::BPeak::Set (TH1 *hist, double x1, double y1, double x2, double y2)
void GamR::TK::BPeak::Set (TH1 *hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background, Option_t *foption="", Option_t *option="sl")
void GamR::TK::BPeak::Set (TH1 *hist, GamR::TK::Gate peak, GamR::TK::Gate background, Option_t *foption="", Option_t *option="sl")
void GamR::TK::BPeak::SetCont (TH1 *hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background, Option_t *foption="", Option_t *option="")
void GamR::TK::BPeak::SetPoint (TH1 *hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background, Option_t *foption="", Option_t *option="")
void GamR::TK::BPeak::SetStep (TH1 *hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background, Option_t *foption="", Option_t *option="")
void GamR::TK::BPeak::Set (TH1 *hist, Option_t *foption="", Option_t *option="sl")
void GamR::TK::BPeak::Set (TH2 *hist, Option_t *foption="", Option_t *option="sl")
void GamR::TK::BPeak::Print ()
void GamR::TK::BPeak::Delete (Option_t *option)
GamR::TK::BPeak::ClassDef (BPeak, 1)
GamR::TK::FPeak::FPeak ()
GamR::TK::FPeak::FPeak (double Low, double High, PeakType Type)
virtual GamR::TK::FPeak::~FPeak ()
TF1 * GamR::TK::FPeak::GetFunc ()
PeakType GamR::TK::FPeak::GetPeakType ()
virtual TF1 * GamR::TK::FPeak::GetStepFunc ()
virtual TF1 * GamR::TK::FPeak::GetGaussFunc ()
virtual void GamR::TK::FPeak::SetParameters (std::vector< double > params)
virtual void GamR::TK::FPeak::SetParErrors (std::vector< double > errors)
GamR::TK::GaussianPeak::GaussianPeak ()
GamR::TK::GaussianPeak::GaussianPeak (double Low, double High)
GamR::TK::GaussianPeak::~GaussianPeak ()
double GamR::TK::GaussianPeak::GetArea ()
double GamR::TK::GaussianPeak::GetAreaError ()
double GamR::TK::GaussianPeak::GetAmp ()
double GamR::TK::GaussianPeak::GetAmpError ()
double GamR::TK::GaussianPeak::GetCent ()
double GamR::TK::GaussianPeak::GetCentError ()
double GamR::TK::GaussianPeak::GetWidth ()
double GamR::TK::GaussianPeak::GetWidthError ()
void GamR::TK::GaussianPeak::SetParameters (std::vector< double > params)
void GamR::TK::GaussianPeak::SetParErrors (std::vector< double > errors)
void GamR::TK::GaussianPeak::SetAmp (double amp)
void GamR::TK::GaussianPeak::SetAmpError (double error)
void GamR::TK::GaussianPeak::SetCent (double cent)
void GamR::TK::GaussianPeak::SetCentError (double error)
void GamR::TK::GaussianPeak::SetWidth (double width)
void GamR::TK::GaussianPeak::SetWidthError (double error)
TF1 * GamR::TK::GaussianPeak::GetStepFunc ()
TF1 * GamR::TK::GaussianPeak::GetGaussFunc ()
GamR::TK::StepGaussianPeak::StepGaussianPeak ()
GamR::TK::StepGaussianPeak::StepGaussianPeak (double Low, double High)
GamR::TK::StepGaussianPeak::~StepGaussianPeak ()
double GamR::TK::StepGaussianPeak::GetArea ()
double GamR::TK::StepGaussianPeak::GetAreaError ()
double GamR::TK::StepGaussianPeak::GetAmp ()
double GamR::TK::StepGaussianPeak::GetAmpError ()
double GamR::TK::StepGaussianPeak::GetCent ()
double GamR::TK::StepGaussianPeak::GetCentError ()
double GamR::TK::StepGaussianPeak::GetWidth ()
double GamR::TK::StepGaussianPeak::GetWidthError ()
void GamR::TK::StepGaussianPeak::SetParameters (std::vector< double > params)
void GamR::TK::StepGaussianPeak::SetParErrors (std::vector< double > errors)
void GamR::TK::StepGaussianPeak::SetAmp (double amp)
void GamR::TK::StepGaussianPeak::SetAmpError (double error)
void GamR::TK::StepGaussianPeak::SetCent (double cent)
void GamR::TK::StepGaussianPeak::SetCentError (double error)
void GamR::TK::StepGaussianPeak::SetWidth (double width)
void GamR::TK::StepGaussianPeak::SetWidthError (double error)
TF1 * GamR::TK::StepGaussianPeak::GetStepFunc ()
TF1 * GamR::TK::StepGaussianPeak::GetGaussFunc ()
GamR::TK::OneTailGaussianPeak::OneTailGaussianPeak ()
GamR::TK::OneTailGaussianPeak::OneTailGaussianPeak (double Low, double High)
GamR::TK::OneTailGaussianPeak::~OneTailGaussianPeak ()
double GamR::TK::OneTailGaussianPeak::GetArea ()
double GamR::TK::OneTailGaussianPeak::GetAreaError ()
double GamR::TK::OneTailGaussianPeak::GetAmp ()
double GamR::TK::OneTailGaussianPeak::GetAmpError ()
double GamR::TK::OneTailGaussianPeak::GetCent ()
double GamR::TK::OneTailGaussianPeak::GetCentError ()
double GamR::TK::OneTailGaussianPeak::GetWidth ()
double GamR::TK::OneTailGaussianPeak::GetWidthError ()
void GamR::TK::OneTailGaussianPeak::SetParameters (std::vector< double > params)
void GamR::TK::OneTailGaussianPeak::SetParErrors (std::vector< double > errors)
void GamR::TK::OneTailGaussianPeak::SetAmp (double amp)
void GamR::TK::OneTailGaussianPeak::SetAmpError (double error)
void GamR::TK::OneTailGaussianPeak::SetCent (double cent)
void GamR::TK::OneTailGaussianPeak::SetCentError (double error)
void GamR::TK::OneTailGaussianPeak::SetWidth (double width)
void GamR::TK::OneTailGaussianPeak::SetWidthError (double error)
TF1 * GamR::TK::OneTailGaussianPeak::GetStepFunc ()
TF1 * GamR::TK::OneTailGaussianPeak::GetGaussFunc ()
GamR::TK::OneTailStepGaussianPeak::OneTailStepGaussianPeak ()
GamR::TK::OneTailStepGaussianPeak::OneTailStepGaussianPeak (double Low, double High)
GamR::TK::OneTailStepGaussianPeak::~OneTailStepGaussianPeak ()
double GamR::TK::OneTailStepGaussianPeak::GetArea ()
double GamR::TK::OneTailStepGaussianPeak::GetAreaError ()
double GamR::TK::OneTailStepGaussianPeak::GetAmp ()
double GamR::TK::OneTailStepGaussianPeak::GetAmpError ()
double GamR::TK::OneTailStepGaussianPeak::GetCent ()
double GamR::TK::OneTailStepGaussianPeak::GetCentError ()
double GamR::TK::OneTailStepGaussianPeak::GetWidth ()
double GamR::TK::OneTailStepGaussianPeak::GetWidthError ()
void GamR::TK::OneTailStepGaussianPeak::SetParameters (std::vector< double > params)
void GamR::TK::OneTailStepGaussianPeak::SetParErrors (std::vector< double > errors)
void GamR::TK::OneTailStepGaussianPeak::SetAmp (double amp)
void GamR::TK::OneTailStepGaussianPeak::SetAmpError (double error)
void GamR::TK::OneTailStepGaussianPeak::SetCent (double cent)
void GamR::TK::OneTailStepGaussianPeak::SetCentError (double error)
void GamR::TK::OneTailStepGaussianPeak::SetWidth (double width)
void GamR::TK::OneTailStepGaussianPeak::SetWidthError (double error)
TF1 * GamR::TK::OneTailStepGaussianPeak::GetStepFunc ()
TF1 * GamR::TK::OneTailStepGaussianPeak::GetGaussFunc ()
GamR::TK::TwoTailGaussianPeak::TwoTailGaussianPeak ()
GamR::TK::TwoTailGaussianPeak::TwoTailGaussianPeak (double Low, double High)
GamR::TK::TwoTailGaussianPeak::~TwoTailGaussianPeak ()
double GamR::TK::TwoTailGaussianPeak::GetArea ()
double GamR::TK::TwoTailGaussianPeak::GetAreaError ()
double GamR::TK::TwoTailGaussianPeak::GetAmp ()
double GamR::TK::TwoTailGaussianPeak::GetAmpError ()
double GamR::TK::TwoTailGaussianPeak::GetCent ()
double GamR::TK::TwoTailGaussianPeak::GetCentError ()
double GamR::TK::TwoTailGaussianPeak::GetWidth ()
double GamR::TK::TwoTailGaussianPeak::GetWidthError ()
void GamR::TK::TwoTailGaussianPeak::SetParameters (std::vector< double > params)
void GamR::TK::TwoTailGaussianPeak::SetParErrors (std::vector< double > errors)
void GamR::TK::TwoTailGaussianPeak::SetAmp (double amp)
void GamR::TK::TwoTailGaussianPeak::SetAmpError (double error)
void GamR::TK::TwoTailGaussianPeak::SetCent (double cent)
void GamR::TK::TwoTailGaussianPeak::SetCentError (double error)
void GamR::TK::TwoTailGaussianPeak::SetWidth (double width)
void GamR::TK::TwoTailGaussianPeak::SetWidthError (double error)
TF1 * GamR::TK::TwoTailGaussianPeak::GetStepFunc ()
TF1 * GamR::TK::TwoTailGaussianPeak::GetGaussFunc ()
GamR::TK::TwoTailStepGaussianPeak::TwoTailStepGaussianPeak ()
GamR::TK::TwoTailStepGaussianPeak::TwoTailStepGaussianPeak (double Low, double High)
GamR::TK::TwoTailStepGaussianPeak::~TwoTailStepGaussianPeak ()
double GamR::TK::TwoTailStepGaussianPeak::GetArea ()
double GamR::TK::TwoTailStepGaussianPeak::GetAreaError ()
double GamR::TK::TwoTailStepGaussianPeak::GetAmp ()
double GamR::TK::TwoTailStepGaussianPeak::GetAmpError ()
double GamR::TK::TwoTailStepGaussianPeak::GetCent ()
double GamR::TK::TwoTailStepGaussianPeak::GetCentError ()
double GamR::TK::TwoTailStepGaussianPeak::GetWidth ()
double GamR::TK::TwoTailStepGaussianPeak::GetWidthError ()
void GamR::TK::TwoTailStepGaussianPeak::SetParameters (std::vector< double > params)
void GamR::TK::TwoTailStepGaussianPeak::SetParErrors (std::vector< double > errors)
void GamR::TK::TwoTailStepGaussianPeak::SetAmp (double amp)
void GamR::TK::TwoTailStepGaussianPeak::SetAmpError (double error)
void GamR::TK::TwoTailStepGaussianPeak::SetCent (double cent)
void GamR::TK::TwoTailStepGaussianPeak::SetCentError (double error)
void GamR::TK::TwoTailStepGaussianPeak::SetWidth (double width)
void GamR::TK::TwoTailStepGaussianPeak::SetWidthError (double error)
TF1 * GamR::TK::TwoTailStepGaussianPeak::GetStepFunc ()
TF1 * GamR::TK::TwoTailStepGaussianPeak::GetGaussFunc ()
BPeak * GamR::TK::FitBPeak (TCanvas *canvas, Option_t *foption, Option_t *option)
BPeak * GamR::TK::ClickBPeak (TCanvas *canvas)
Variables
TF1 * GamR::TK::FPeak::fPeakFunc
double GamR::TK::FPeak::fLow
double GamR::TK::FPeak::fHigh
PeakType GamR::TK::FPeak::fPeakType
Detailed Description
Enumeration Type Documentation
PeakType
enum GamR::TK::PeakType
#include <src/lib/toolkit/Peak.hh>
Enumerator
Gaussian
StepGaussian
OneTailGaussian
OneTailStepGaussian
TwoTailGaussian
TwoTailStepGaussian
Definition at line 33 of file Peak.hh.
Function Documentation
BPeak()
GamR::TK::BPeak::BPeak ()
#include <src/lib/toolkit/Peak.hh>
Definition at line 14 of file Peak.cc.
Referenced by ClassDef().
FPeak() [1/2]
GamR::TK::FPeak::FPeak () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 139 of file Peak.hh.
Referenced by GamR::TK::GaussianPeak::GaussianPeak(), GamR::TK::OneTailGaussianPeak::OneTailGaussianPeak(), GamR::TK::OneTailStepGaussianPeak::OneTailStepGaussianPeak(), GamR::TK::StepGaussianPeak::StepGaussianPeak(), GamR::TK::TwoTailGaussianPeak::TwoTailGaussianPeak(), and GamR::TK::TwoTailStepGaussianPeak::TwoTailStepGaussianPeak().
FPeak() [2/2]
GamR::TK::FPeak::FPeak (double Low, double High, PeakType Type) inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 140 of file Peak.hh.
References fHigh, fLow, and fPeakType.
Gate() [1/7]
GamR::TK::Gate::Gate () inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 38 of file Gate.hh.
Referenced by Gate(), GetCounts(), GetCountsError(), GetIntegral(), GetIntegral(), GetIntegralError(), NormBackSub(), and PassDetector().
Gate() [2/7]
GamR::TK::Gate::Gate (const char * name)
#include <src/lib/toolkit/Gate.hh>
Definition at line 48 of file Gate.cc.
Gate() [3/7]
GamR::TK::Gate::Gate (const char * name, const char * title)
#include <src/lib/toolkit/Gate.hh>
Definition at line 53 of file Gate.cc.
Gate() [4/7]
GamR::TK::Gate::Gate (const char * name, const char * title, TVirtualPad * canvas, Option_t * opt = "")
#include <src/lib/toolkit/Gate.hh>
Definition at line 64 of file Gate.cc.
References SetGate().
Gate() [5/7]
GamR::TK::Gate::Gate (const char * name, TVirtualPad * canvas, Option_t * opt = "")
#include <src/lib/toolkit/Gate.hh>
Definition at line 58 of file Gate.cc.
References SetGate().
Gate() [6/7]
GamR::TK::Gate::Gate (double l, double h) inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 49 of file Gate.hh.
References Gate(), and Valid().
Gate() [7/7]
GamR::TK::Gate::Gate (TVirtualPad * canvas, Option_t * opt = "")
#include <src/lib/toolkit/Gate.hh>
Definition at line 70 of file Gate.cc.
References SetGate().
GateMap() [1/3]
GamR::TK::GateMap::GateMap () inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 141 of file Gate.hh.
GateMap() [2/3]
GamR::TK::GateMap::GateMap (const char * name) inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 142 of file Gate.hh.
GateMap() [3/3]
GamR::TK::GateMap::GateMap (const char * name, const char * title) inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 143 of file Gate.hh.
GaussianPeak() [1/2]
GamR::TK::GaussianPeak::GaussianPeak () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 158 of file Peak.hh.
GaussianPeak() [2/2]
GamR::TK::GaussianPeak::GaussianPeak (double Low, double High)
#include <src/lib/toolkit/Peak.hh>
Definition at line 692 of file Peak.cc.
References GamR::TK::FPeak::FPeak(), GamR::TK::FPeak::fPeakFunc, and GamR::TK::Gaussian.
LFit()
GamR::TK::BPeak::LFit::LFit (TH1D * background) inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 89 of file Peak.hh.
OneTailGaussianPeak() [1/2]
GamR::TK::OneTailGaussianPeak::OneTailGaussianPeak ()
#include <src/lib/toolkit/Peak.hh>
Definition at line 931 of file Peak.cc.
OneTailGaussianPeak() [2/2]
GamR::TK::OneTailGaussianPeak::OneTailGaussianPeak (double Low, double High)
#include <src/lib/toolkit/Peak.hh>
Definition at line 710 of file Peak.cc.
References GamR::TK::FPeak::FPeak(), GamR::TK::FPeak::fPeakFunc, and GamR::TK::OneTailGaussian.
OneTailStepGaussianPeak() [1/2]
GamR::TK::OneTailStepGaussianPeak::OneTailStepGaussianPeak () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 269 of file Peak.hh.
OneTailStepGaussianPeak() [2/2]
GamR::TK::OneTailStepGaussianPeak::OneTailStepGaussianPeak (double Low, double High)
#include <src/lib/toolkit/Peak.hh>
Definition at line 739 of file Peak.cc.
References GamR::TK::FPeak::FPeak(), GamR::TK::FPeak::fPeakFunc, and GamR::TK::OneTailStepGaussian.
StepGaussianPeak() [1/2]
GamR::TK::StepGaussianPeak::StepGaussianPeak () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 193 of file Peak.hh.
StepGaussianPeak() [2/2]
GamR::TK::StepGaussianPeak::StepGaussianPeak (double Low, double High)
#include <src/lib/toolkit/Peak.hh>
Definition at line 700 of file Peak.cc.
References GamR::TK::FPeak::FPeak(), GamR::TK::FPeak::fPeakFunc, and GamR::TK::StepGaussian.
TwoTailGaussianPeak() [1/2]
GamR::TK::TwoTailGaussianPeak::TwoTailGaussianPeak () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 308 of file Peak.hh.
TwoTailGaussianPeak() [2/2]
GamR::TK::TwoTailGaussianPeak::TwoTailGaussianPeak (double Low, double High)
#include <src/lib/toolkit/Peak.hh>
Definition at line 779 of file Peak.cc.
References GamR::TK::FPeak::FPeak(), GamR::TK::FPeak::fPeakFunc, and GamR::TK::TwoTailGaussian.
TwoTailStepGaussianPeak() [1/2]
GamR::TK::TwoTailStepGaussianPeak::TwoTailStepGaussianPeak () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 342 of file Peak.hh.
TwoTailStepGaussianPeak() [2/2]
GamR::TK::TwoTailStepGaussianPeak::TwoTailStepGaussianPeak (double Low, double High)
#include <src/lib/toolkit/Peak.hh>
Definition at line 813 of file Peak.cc.
References GamR::TK::FPeak::FPeak(), GamR::TK::FPeak::fPeakFunc, and GamR::TK::TwoTailStepGaussian.
~BPeak()
GamR::TK::BPeak::~BPeak ()
#include <src/lib/toolkit/Peak.hh>
Definition at line 15 of file Peak.cc.
Referenced by Delete().
~FPeak()
virtual GamR::TK::FPeak::~FPeak () inline virtual
#include <src/lib/toolkit/Peak.hh>
Definition at line 141 of file Peak.hh.
~Gate()
GamR::TK::Gate::~Gate () inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 55 of file Gate.hh.
~GaussianPeak()
GamR::TK::GaussianPeak::~GaussianPeak () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 160 of file Peak.hh.
~OneTailGaussianPeak()
GamR::TK::OneTailGaussianPeak::~OneTailGaussianPeak ()
#include <src/lib/toolkit/Peak.hh>
Definition at line 932 of file Peak.cc.
~OneTailStepGaussianPeak()
GamR::TK::OneTailStepGaussianPeak::~OneTailStepGaussianPeak () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 271 of file Peak.hh.
~StepGaussianPeak()
GamR::TK::StepGaussianPeak::~StepGaussianPeak () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 195 of file Peak.hh.
~TwoTailGaussianPeak()
GamR::TK::TwoTailGaussianPeak::~TwoTailGaussianPeak () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 310 of file Peak.hh.
~TwoTailStepGaussianPeak()
GamR::TK::TwoTailStepGaussianPeak::~TwoTailStepGaussianPeak () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 344 of file Peak.hh.
ApplyX() [1/2]
TH1D * GamR::TK::Gate::ApplyX (TH2 * hist) const
#include <src/lib/toolkit/Gate.hh>
Applies the gate to a TH2 histogram in the X direction, projecting onto the Y-axis. Appends "_gy" to the input histogram name for the name of the output histogram.
Parameters
hist Input histogram
Returns
Y-Projection from between the gate bounds
Definition at line 252 of file Gate.cc.
Referenced by GamR::Spect::BackgroundSubtractX(), GamR::Spect::GateX(), GamR::Spect::GateX(), GamR::AngDist::RatioFunction(), and GamR::TK::BPeak::Set().
ApplyX() [2/2]
TH1D * GamR::TK::Gate::ApplyX (TH2 * hist, const char * name) const
#include <src/lib/toolkit/Gate.hh>
Applies the gate to a TH2 histogram in the X direction, projecting onto the Y-axis.
Parameters
hist Input histogram
name Name of the returned histogram
Returns
Y-Projection from between the gate bounds
Definition at line 278 of file Gate.cc.
ApplyY() [1/2]
TH1D * GamR::TK::Gate::ApplyY (TH2 * hist) const
#include <src/lib/toolkit/Gate.hh>
Applies the gate to a TH2 histogram in the Y direction, projecting onto the X-axis. Appends "_gx" to the input histogram name for the name of the output histogram.
Parameters
hist Input histogram
Returns
X-Projection from between the gate bounds
Definition at line 202 of file Gate.cc.
Referenced by GamR::Spect::BackgroundSubtractY(), GamR::Spect::GateY(), and GamR::Spect::GateY().
ApplyY() [2/2]
TH1D * GamR::TK::Gate::ApplyY (TH2 * hist, const char * name) const
#include <src/lib/toolkit/Gate.hh>
Applies the gate to a TH2 histogram in the Y direction, projecting onto the X-axis.
Parameters
hist Input histogram
name Name of the returned histogram
Returns
X-Projection from between the gate bounds
Definition at line 228 of file Gate.cc.
Browse() [1/2]
void GamR::TK::Gate::Browse (TBrowser * b)
#include <src/lib/toolkit/Gate.hh>
Definition at line 748 of file Gate.cc.
References ls().
Browse() [2/2]
void GamR::TK::GateMap::Browse (TBrowser * b)
#include <src/lib/toolkit/Gate.hh>
Definition at line 877 of file Gate.cc.
References ls().
ClassDef()
GamR::TK::BPeak::ClassDef (BPeak , 1)
#include <src/lib/toolkit/Peak.hh>
References BPeak().
ClickBPeak()
BPeak * GamR::TK::ClickBPeak (TCanvas * canvas)
#include <src/lib/toolkit/Peak.cc>
Definition at line 870 of file Peak.cc.
References GamR::Utils::GetHist1D(), and GamR::TK::BPeak::Print().
Referenced by cbp().
Delete()
void GamR::TK::BPeak::Delete (Option_t * option) inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 119 of file Peak.hh.
References ~BPeak().
DistancetoPrimitive()
Int_t GamR::TK::Gate::DistancetoPrimitive (Int_t px, Int_t py)
#include <src/lib/toolkit/Gate.hh>
Definition at line 842 of file Gate.cc.
References px(), and py().
ExecuteEvent()
void GamR::TK::Gate::ExecuteEvent (Int_t event, Int_t px, Int_t py)
#include <src/lib/toolkit/Gate.hh>
Definition at line 850 of file Gate.cc.
References px(), and py().
FitBPeak()
BPeak * GamR::TK::FitBPeak (TCanvas * canvas, Option_t * foption, Option_t * option)
#include <src/lib/toolkit/Peak.cc>
Definition at line 859 of file Peak.cc.
References GamR::Utils::GetHist1D(), and GamR::TK::BPeak::Print().
Referenced by bp().
GetAmp() [1/8]
double GamR::TK::BPeak::GetAmp () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 100 of file Peak.hh.
Referenced by Print().
GetAmp() [2/8]
double GamR::TK::GaussianPeak::GetAmp () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 166 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetAmp() [3/8]
double GamR::TK::OneTailGaussianPeak::GetAmp () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 241 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetAmp() [4/8]
double GamR::TK::OneTailStepGaussianPeak::GetAmp () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 274 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetAmp() [5/8]
virtual double GamR::TK::Peak::GetAmp () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::BPeak, GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 40 of file Peak.hh.
GetAmp() [6/8]
double GamR::TK::StepGaussianPeak::GetAmp () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 201 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetAmp() [7/8]
double GamR::TK::TwoTailGaussianPeak::GetAmp () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 313 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetAmp() [8/8]
double GamR::TK::TwoTailStepGaussianPeak::GetAmp () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 347 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetAmpError() [1/8]
double GamR::TK::BPeak::GetAmpError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 101 of file Peak.hh.
Referenced by Print().
GetAmpError() [2/8]
double GamR::TK::GaussianPeak::GetAmpError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 167 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetAmpError() [3/8]
double GamR::TK::OneTailGaussianPeak::GetAmpError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 242 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetAmpError() [4/8]
double GamR::TK::OneTailStepGaussianPeak::GetAmpError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 275 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetAmpError() [5/8]
virtual double GamR::TK::Peak::GetAmpError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::BPeak, GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 41 of file Peak.hh.
GetAmpError() [6/8]
double GamR::TK::StepGaussianPeak::GetAmpError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 202 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetAmpError() [7/8]
double GamR::TK::TwoTailGaussianPeak::GetAmpError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 314 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetAmpError() [8/8]
double GamR::TK::TwoTailStepGaussianPeak::GetAmpError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 348 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetArea() [1/8]
double GamR::TK::BPeak::GetArea () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 96 of file Peak.hh.
Referenced by Print().
GetArea() [2/8]
double GamR::TK::GaussianPeak::GetArea () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 161 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetArea() [3/8]
double GamR::TK::OneTailGaussianPeak::GetArea () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 239 of file Peak.hh.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, and GamR::TK::FPeak::fPeakFunc.
Referenced by GamR::TK::OneTailStepGaussianPeak::GetArea().
GetArea() [4/8]
double GamR::TK::OneTailStepGaussianPeak::GetArea () virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 753 of file Peak.cc.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, GamR::TK::OneTailGaussianPeak::GetArea(), and GamR::TK::FPeak::GetFunc().
GetArea() [5/8]
virtual double GamR::TK::Peak::GetArea () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::BPeak, GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 38 of file Peak.hh.
GetArea() [6/8]
double GamR::TK::StepGaussianPeak::GetArea () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 196 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetArea() [7/8]
double GamR::TK::TwoTailGaussianPeak::GetArea () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 311 of file Peak.hh.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, and GamR::TK::FPeak::fPeakFunc.
Referenced by GamR::TK::TwoTailStepGaussianPeak::GetArea().
GetArea() [8/8]
double GamR::TK::TwoTailStepGaussianPeak::GetArea () virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 833 of file Peak.cc.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, GamR::TK::TwoTailGaussianPeak::GetArea(), and GamR::TK::FPeak::GetFunc().
GetAreaError() [1/8]
double GamR::TK::BPeak::GetAreaError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 97 of file Peak.hh.
Referenced by Print().
GetAreaError() [2/8]
double GamR::TK::GaussianPeak::GetAreaError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 163 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetAreaError() [3/8]
double GamR::TK::OneTailGaussianPeak::GetAreaError () virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 723 of file Peak.cc.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, and GamR::TK::FPeak::fPeakFunc.
Referenced by GamR::TK::OneTailStepGaussianPeak::GetAreaError().
GetAreaError() [4/8]
double GamR::TK::OneTailStepGaussianPeak::GetAreaError () virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 766 of file Peak.cc.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, GamR::TK::OneTailGaussianPeak::GetAreaError(), and GamR::TK::FPeak::GetFunc().
GetAreaError() [5/8]
virtual double GamR::TK::Peak::GetAreaError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::BPeak, GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 39 of file Peak.hh.
GetAreaError() [6/8]
double GamR::TK::StepGaussianPeak::GetAreaError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 198 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetAreaError() [7/8]
double GamR::TK::TwoTailGaussianPeak::GetAreaError () virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 797 of file Peak.cc.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, and GamR::TK::FPeak::fPeakFunc.
Referenced by GamR::TK::TwoTailStepGaussianPeak::GetAreaError().
GetAreaError() [8/8]
double GamR::TK::TwoTailStepGaussianPeak::GetAreaError () virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 846 of file Peak.cc.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, GamR::TK::TwoTailGaussianPeak::GetAreaError(), and GamR::TK::FPeak::GetFunc().
GetBinHigh()
int GamR::TK::Gate::GetBinHigh (TH1 * hist) const inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 75 of file Gate.hh.
Referenced by GetIntegral(), GetIntegral(), GetIntegralError(), and GetTrueWidth().
GetBinLow()
int GamR::TK::Gate::GetBinLow (TH1 * hist) const inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 74 of file Gate.hh.
Referenced by GetIntegral(), GetIntegral(), GetIntegralError(), and GetTrueWidth().
GetBinWidth()
int GamR::TK::Gate::GetBinWidth (TH1 * hist) const inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 76 of file Gate.hh.
Referenced by GamR::Spect::BackgroundSubtractX(), GamR::Spect::BackgroundSubtractY(), GetCounts(), GetCounts(), GetCountsError(), GetCountsError(), GetIntegral(), GetIntegralError(), GamR::AngDist::RatioFunction(), and GamR::TK::BPeak::Set().
GetCent() [1/8]
double GamR::TK::BPeak::GetCent () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 102 of file Peak.hh.
Referenced by Print(), and SetStep().
GetCent() [2/8]
double GamR::TK::GaussianPeak::GetCent () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 168 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetCent() [3/8]
double GamR::TK::OneTailGaussianPeak::GetCent () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 243 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetCent() [4/8]
double GamR::TK::OneTailStepGaussianPeak::GetCent () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 276 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetCent() [5/8]
virtual double GamR::TK::Peak::GetCent () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::BPeak, GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 42 of file Peak.hh.
GetCent() [6/8]
double GamR::TK::StepGaussianPeak::GetCent () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 203 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetCent() [7/8]
double GamR::TK::TwoTailGaussianPeak::GetCent () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 315 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetCent() [8/8]
double GamR::TK::TwoTailStepGaussianPeak::GetCent () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 349 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetCentError() [1/8]
double GamR::TK::BPeak::GetCentError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 103 of file Peak.hh.
Referenced by Print(), and SetStep().
GetCentError() [2/8]
double GamR::TK::GaussianPeak::GetCentError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 169 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetCentError() [3/8]
double GamR::TK::OneTailGaussianPeak::GetCentError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 244 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetCentError() [4/8]
double GamR::TK::OneTailStepGaussianPeak::GetCentError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 277 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetCentError() [5/8]
virtual double GamR::TK::Peak::GetCentError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::BPeak, GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 43 of file Peak.hh.
GetCentError() [6/8]
double GamR::TK::StepGaussianPeak::GetCentError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 204 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetCentError() [7/8]
double GamR::TK::TwoTailGaussianPeak::GetCentError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 316 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetCentError() [8/8]
double GamR::TK::TwoTailStepGaussianPeak::GetCentError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 350 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetClick()
void GamR::TK::Gate::GetClick (Int_t , Int_t , Int_t , TObject * selected)
#include <src/lib/toolkit/Gate.hh>
GetCounts() [1/4]
double GamR::TK::BPeak::GetCounts () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 98 of file Peak.hh.
Referenced by Print().
GetCounts() [2/4]
double GamR::TK::Gate::GetCounts (TH1 * hist) const
#include <src/lib/toolkit/Gate.hh>
Finds the total counts within the gate bounds (inclusive)
Parameters
hist 1D histogram to act on
Returns
The total counts falling between the bounds of the gate
Definition at line 529 of file Gate.cc.
Referenced by GamR::Spect::Counts(), GetCounts(), and GetCounts().
GetCounts() [3/4]
double GamR::TK::Gate::GetCounts (TH1 * hist, Gate background) const
#include <src/lib/toolkit/Gate.hh>
Finds the difference between the counts contained by the gate bounds and the background gate bounds (scaled appropriately)
Parameters
hist 1D histogram to act on
background background Gate
Returns
The total peak counts
Definition at line 550 of file Gate.cc.
References Gate(), GetBinWidth(), and GetCounts().
GetCounts() [4/4]
double GamR::TK::Gate::GetCounts (TH1 * hist, std::vector< Gate > background) const
#include <src/lib/toolkit/Gate.hh>
Definition at line 559 of file Gate.cc.
References GetBinWidth(), and GetCounts().
GetCountsError() [1/4]
double GamR::TK::BPeak::GetCountsError () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 99 of file Peak.hh.
Referenced by Print().
GetCountsError() [2/4]
double GamR::TK::Gate::GetCountsError (TH1 * hist) const
#include <src/lib/toolkit/Gate.hh>
Finds the error in the counts within the gate bounds (inclusive). Sums the errors of the histogram channels in quadrature.
Parameters
hist 1D histogram to act on
Returns
The total error in the counts falling between the bounds of the gate
Definition at line 630 of file Gate.cc.
Referenced by GamR::Spect::Counts(), GetCountsError(), and GetCountsError().
GetCountsError() [3/4]
double GamR::TK::Gate::GetCountsError (TH1 * hist, Gate background) const
#include <src/lib/toolkit/Gate.hh>
Definition at line 644 of file Gate.cc.
References Gate(), GetBinWidth(), and GetCountsError().
GetCountsError() [4/4]
double GamR::TK::Gate::GetCountsError (TH1 * hist, std::vector< Gate > background) const
#include <src/lib/toolkit/Gate.hh>
Definition at line 653 of file Gate.cc.
References GetBinWidth(), and GetCountsError().
GetFunc()
TF1 * GamR::TK::FPeak::GetFunc () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 143 of file Peak.hh.
References fPeakFunc.
Referenced by GamR::TK::OneTailStepGaussianPeak::GetArea(), GamR::TK::TwoTailStepGaussianPeak::GetArea(), GamR::TK::OneTailStepGaussianPeak::GetAreaError(), and GamR::TK::TwoTailStepGaussianPeak::GetAreaError().
GetGaussFunc() [1/7]
virtual TF1 * GamR::TK::FPeak::GetGaussFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 147 of file Peak.hh.
GetGaussFunc() [2/7]
TF1 * GamR::TK::GaussianPeak::GetGaussFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 183 of file Peak.hh.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, and GamR::TK::FPeak::fPeakFunc.
GetGaussFunc() [3/7]
TF1 * GamR::TK::OneTailGaussianPeak::GetGaussFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 258 of file Peak.hh.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, and GamR::TK::FPeak::fPeakFunc.
GetGaussFunc() [4/7]
TF1 * GamR::TK::OneTailStepGaussianPeak::GetGaussFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 297 of file Peak.hh.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, and GamR::TK::FPeak::fPeakFunc.
GetGaussFunc() [5/7]
TF1 * GamR::TK::StepGaussianPeak::GetGaussFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 225 of file Peak.hh.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, and GamR::TK::FPeak::fPeakFunc.
GetGaussFunc() [6/7]
TF1 * GamR::TK::TwoTailGaussianPeak::GetGaussFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 330 of file Peak.hh.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, and GamR::TK::FPeak::fPeakFunc.
GetGaussFunc() [7/7]
TF1 * GamR::TK::TwoTailStepGaussianPeak::GetGaussFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 370 of file Peak.hh.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, and GamR::TK::FPeak::fPeakFunc.
GetHigh()
double GamR::TK::Gate::GetHigh () const inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 72 of file Gate.hh.
Referenced by GamR::Spect::CountsBS(), GamR::Spect::CountsBS(), GetIntegralError(), GamR::Spect::IntegralBS(), ls(), GamR::TK::operator<<(), GamR::TK::BPeak::Set(), GamR::TK::BPeak::SetCont(), and GamR::TK::BPeak::SetPoint().
GetIntegral() [1/4]
double GamR::TK::Gate::GetIntegral (TH1 * hist) const
#include <src/lib/toolkit/Gate.hh>
Finds the total area within the gate bounds (inclusive)
Parameters
hist 1D histogram to act on
Returns
The total histogram area falling between the bounds of the gate
Definition at line 300 of file Gate.cc.
Referenced by GetIntegral(), GamR::Spect::Integral(), Norm(), and NormBackSub().
GetIntegral() [2/4]
double GamR::TK::Gate::GetIntegral (TH1 * hist, Gate background) const
#include <src/lib/toolkit/Gate.hh>
Finds the difference between the areas contained by the gate bounds and the background gate bounds (scaled appropriately)
Parameters
hist 1D histogram to act on
background background Gates
Returns
The total peak area
Definition at line 371 of file Gate.cc.
References Gate(), GetBinWidth(), and GetIntegral().
GetIntegral() [3/4]
double GamR::TK::Gate::GetIntegral (TH1 * hist, Gate backLow, Gate backHigh) const
#include <src/lib/toolkit/Gate.hh>
Definition at line 380 of file Gate.cc.
References Gate(), GetBinHigh(), and GetBinLow().
GetIntegral() [4/4]
double GamR::TK::Gate::GetIntegral (TH1 * hist, std::vector< Gate > background) const
#include <src/lib/toolkit/Gate.hh>
Definition at line 314 of file Gate.cc.
References GetBinHigh(), and GetBinLow().
GetIntegralError() [1/3]
double GamR::TK::Gate::GetIntegralError (TH1 * hist) const
#include <src/lib/toolkit/Gate.hh>
Finds the error in the area within the gate bounds (inclusive). Sums the errors of the histogram channels in quadrature.
Parameters
hist 1D histogram to act on
Returns
The total error in the area falling between the bounds of the gate
Definition at line 445 of file Gate.cc.
Referenced by GetIntegralError(), and GamR::Spect::Integral().
GetIntegralError() [2/3]
double GamR::TK::Gate::GetIntegralError (TH1 * hist, Gate background) const
#include <src/lib/toolkit/Gate.hh>
Definition at line 459 of file Gate.cc.
References Gate(), GetBinWidth(), and GetIntegralError().
GetIntegralError() [3/3]
double GamR::TK::Gate::GetIntegralError (TH1 * hist, std::vector< Gate > background) const
#include <src/lib/toolkit/Gate.hh>
Definition at line 468 of file Gate.cc.
References GetBinHigh(), GetBinLow(), GetHigh(), and GetLow().
GetLow()
double GamR::TK::Gate::GetLow () const inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 71 of file Gate.hh.
Referenced by GamR::Spect::CountsBS(), GamR::Spect::CountsBS(), GetIntegralError(), GamR::Spect::IntegralBS(), ls(), GamR::TK::operator<<(), GamR::TK::BPeak::Set(), GamR::TK::BPeak::SetCont(), and GamR::TK::BPeak::SetPoint().
GetPeakType()
PeakType GamR::TK::FPeak::GetPeakType () inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 144 of file Peak.hh.
References fPeakType.
GetStepFunc() [1/7]
virtual TF1 * GamR::TK::FPeak::GetStepFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 146 of file Peak.hh.
GetStepFunc() [2/7]
TF1 * GamR::TK::GaussianPeak::GetStepFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 182 of file Peak.hh.
GetStepFunc() [3/7]
TF1 * GamR::TK::OneTailGaussianPeak::GetStepFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 257 of file Peak.hh.
GetStepFunc() [4/7]
TF1 * GamR::TK::OneTailStepGaussianPeak::GetStepFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 290 of file Peak.hh.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, and GamR::TK::FPeak::fPeakFunc.
GetStepFunc() [5/7]
TF1 * GamR::TK::StepGaussianPeak::GetStepFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 217 of file Peak.hh.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, and GamR::TK::FPeak::fPeakFunc.
GetStepFunc() [6/7]
TF1 * GamR::TK::TwoTailGaussianPeak::GetStepFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 329 of file Peak.hh.
GetStepFunc() [7/7]
TF1 * GamR::TK::TwoTailStepGaussianPeak::GetStepFunc () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 363 of file Peak.hh.
References GamR::TK::FPeak::fHigh, GamR::TK::FPeak::fLow, and GamR::TK::FPeak::fPeakFunc.
GetTrueWidth()
double GamR::TK::Gate::GetTrueWidth (TH1 * hist) const inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 77 of file Gate.hh.
References GetBinHigh(), and GetBinLow().
GetWidth() [1/9]
double GamR::TK::BPeak::GetWidth () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 104 of file Peak.hh.
Referenced by Print(), and SetStep().
GetWidth() [2/9]
double GamR::TK::Gate::GetWidth () const inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 73 of file Gate.hh.
Referenced by SetScale().
GetWidth() [3/9]
double GamR::TK::GaussianPeak::GetWidth () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 170 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetWidth() [4/9]
double GamR::TK::OneTailGaussianPeak::GetWidth () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 245 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetWidth() [5/9]
double GamR::TK::OneTailStepGaussianPeak::GetWidth () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 278 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetWidth() [6/9]
virtual double GamR::TK::Peak::GetWidth () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::BPeak, GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 44 of file Peak.hh.
GetWidth() [7/9]
double GamR::TK::StepGaussianPeak::GetWidth () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 205 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetWidth() [8/9]
double GamR::TK::TwoTailGaussianPeak::GetWidth () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 317 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetWidth() [9/9]
double GamR::TK::TwoTailStepGaussianPeak::GetWidth () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 351 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetWidthError() [1/8]
double GamR::TK::BPeak::GetWidthError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 105 of file Peak.hh.
Referenced by Print(), and SetStep().
GetWidthError() [2/8]
double GamR::TK::GaussianPeak::GetWidthError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 171 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetWidthError() [3/8]
double GamR::TK::OneTailGaussianPeak::GetWidthError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 246 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetWidthError() [4/8]
double GamR::TK::OneTailStepGaussianPeak::GetWidthError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 279 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetWidthError() [5/8]
virtual double GamR::TK::Peak::GetWidthError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::BPeak, GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 45 of file Peak.hh.
GetWidthError() [6/8]
double GamR::TK::StepGaussianPeak::GetWidthError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 206 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetWidthError() [7/8]
double GamR::TK::TwoTailGaussianPeak::GetWidthError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 318 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
GetWidthError() [8/8]
double GamR::TK::TwoTailStepGaussianPeak::GetWidthError () inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 352 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
IsFolder() [1/2]
Bool_t GamR::TK::Gate::IsFolder () const inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 112 of file Gate.hh.
IsFolder() [2/2]
Bool_t GamR::TK::GateMap::IsFolder () const inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 145 of file Gate.hh.
ls() [1/2]
void GamR::TK::Gate::ls (Option_t * option = "") const
#include <src/lib/toolkit/Gate.hh>
Definition at line 870 of file Gate.cc.
References GetHigh(), and GetLow().
ls() [2/2]
void GamR::TK::GateMap::ls (Option_t * option = "") const
#include <src/lib/toolkit/Gate.hh>
Definition at line 894 of file Gate.cc.
Norm()
void GamR::TK::Gate::Norm (TH1 * hist, TH1 * ref)
#include <src/lib/toolkit/Gate.hh>
Definition at line 720 of file Gate.cc.
References GetIntegral().
Referenced by GamR::Spect::Norm(), and GamR::Spect::NormSpectra().
NormBackSub()
void GamR::TK::Gate::NormBackSub (TH1 * hist, TH1 * ref, Gate background)
#include <src/lib/toolkit/Gate.hh>
Definition at line 725 of file Gate.cc.
References Gate(), and GetIntegral().
Referenced by GamR::Spect::NormBackSub(), and GamR::Spect::NormSpectraBackSub().
operator()()
double GamR::TK::BPeak::LFit::operator() (double * x, double * p) inline
#include <src/lib/toolkit/Peak.hh>
Definition at line 90 of file Peak.hh.
operator<<()
std::ostream & GamR::TK::operator<< (std::ostream & os, Gate const & g)
#include <src/lib/toolkit/Gate.cc>
Definition at line 903 of file Gate.cc.
References GamR::TK::Gate::GetHigh(), GamR::TK::Gate::GetLow(), and os().
operator[]()
Gate & GamR::TK::GateMap::operator[] (std::string key) inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 144 of file Gate.hh.
Paint()
void GamR::TK::Gate::Paint (Option_t * option = "same")
#include <src/lib/toolkit/Gate.hh>
Definition at line 755 of file Gate.cc.
References GamR::Utils::GetHist1D().
Pass() [1/2]
Bool_t GamR::TK::Gate::Pass (double x) inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 93 of file Gate.hh.
Pass() [2/2]
Bool_t GamR::TK::Gate::Pass (double x) const inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 97 of file Gate.hh.
PassAny()
Bool_t GamR::TK::GateMap::PassAny (double x) const inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 148 of file Gate.hh.
PassDetector()
template<size_t Meas, class TDetector> Bool_t GamR::TK::Gate::PassDetector (TDetector det, Bool_t calibrated = kTRUE, Int_t id = -1)
#include <src/lib/toolkit/Gate.hh>
References Gate(), px(), and py().
Print()
void GamR::TK::BPeak::Print ()
#include <src/lib/toolkit/Peak.hh>
Definition at line 672 of file Peak.cc.
References GetAmp(), GetAmpError(), GetArea(), GetAreaError(), GetCent(), GetCentError(), GetCounts(), GetCountsError(), GetWidth(), GetWidthError(), and GamR::Utils::wrresult().
Referenced by GamR::TK::ClickBPeak(), and GamR::TK::FitBPeak().
Set() [1/5]
void GamR::TK::BPeak::Set (TH1 * hist, double x1, double y1, double x2, double y2)
#include <src/lib/toolkit/Peak.hh>
Definition at line 96 of file Peak.cc.
Set() [2/5]
void GamR::TK::BPeak::Set (TH1 * hist, GamR::TK::Gate peak, GamR::TK::Gate background, Option_t * foption = "", Option_t * option = "sl")
#include <src/lib/toolkit/Peak.hh>
Definition at line 548 of file Peak.cc.
Set() [3/5]
void GamR::TK::BPeak::Set (TH1 * hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background, Option_t * foption = "", Option_t * option = "sl")
#include <src/lib/toolkit/Peak.hh>
Definition at line 122 of file Peak.cc.
References SetCont(), SetPoint(), and SetStep().
Set() [4/5]
void GamR::TK::BPeak::Set (TH1 * hist, Option_t * foption = "", Option_t * option = "sl")
#include <src/lib/toolkit/Peak.hh>
Definition at line 554 of file Peak.cc.
References GamR::TK::Gate::SetGate().
Set() [5/5]
void GamR::TK::BPeak::Set (TH2 * hist, Option_t * foption = "", Option_t * option = "sl")
#include <src/lib/toolkit/Peak.hh>
Definition at line 569 of file Peak.cc.
References GamR::TK::Gate::ApplyX(), GamR::TK::Gate::GetBinWidth(), GamR::TK::Gate::GetHigh(), GamR::TK::Gate::GetLow(), and GamR::TK::Gate::SetGate().
SetAmp() [1/7]
void GamR::TK::GaussianPeak::SetAmp (double amp) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 175 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetAmp() [2/7]
void GamR::TK::OneTailGaussianPeak::SetAmp (double amp) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 250 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetAmp() [3/7]
void GamR::TK::OneTailStepGaussianPeak::SetAmp (double amp) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 283 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetAmp() [4/7]
virtual void GamR::TK::Peak::SetAmp (double amp) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 47 of file Peak.hh.
SetAmp() [5/7]
void GamR::TK::StepGaussianPeak::SetAmp (double amp) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 210 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetAmp() [6/7]
void GamR::TK::TwoTailGaussianPeak::SetAmp (double amp) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 322 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetAmp() [7/7]
void GamR::TK::TwoTailStepGaussianPeak::SetAmp (double amp) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 356 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetAmpError() [1/7]
void GamR::TK::GaussianPeak::SetAmpError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 176 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetAmpError() [2/7]
void GamR::TK::OneTailGaussianPeak::SetAmpError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 251 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetAmpError() [3/7]
void GamR::TK::OneTailStepGaussianPeak::SetAmpError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 284 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetAmpError() [4/7]
virtual void GamR::TK::Peak::SetAmpError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 48 of file Peak.hh.
SetAmpError() [5/7]
void GamR::TK::StepGaussianPeak::SetAmpError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 211 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetAmpError() [6/7]
void GamR::TK::TwoTailGaussianPeak::SetAmpError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 323 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetAmpError() [7/7]
void GamR::TK::TwoTailStepGaussianPeak::SetAmpError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 357 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetCent() [1/7]
void GamR::TK::GaussianPeak::SetCent (double cent) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 177 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetCent() [2/7]
void GamR::TK::OneTailGaussianPeak::SetCent (double cent) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 252 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetCent() [3/7]
void GamR::TK::OneTailStepGaussianPeak::SetCent (double cent) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 285 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetCent() [4/7]
virtual void GamR::TK::Peak::SetCent (double cent) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 49 of file Peak.hh.
SetCent() [5/7]
void GamR::TK::StepGaussianPeak::SetCent (double cent) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 212 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetCent() [6/7]
void GamR::TK::TwoTailGaussianPeak::SetCent (double cent) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 324 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetCent() [7/7]
void GamR::TK::TwoTailStepGaussianPeak::SetCent (double cent) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 358 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetCentError() [1/7]
void GamR::TK::GaussianPeak::SetCentError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 178 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetCentError() [2/7]
void GamR::TK::OneTailGaussianPeak::SetCentError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 253 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetCentError() [3/7]
void GamR::TK::OneTailStepGaussianPeak::SetCentError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 286 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetCentError() [4/7]
virtual void GamR::TK::Peak::SetCentError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 50 of file Peak.hh.
SetCentError() [5/7]
void GamR::TK::StepGaussianPeak::SetCentError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 213 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetCentError() [6/7]
void GamR::TK::TwoTailGaussianPeak::SetCentError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 325 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetCentError() [7/7]
void GamR::TK::TwoTailStepGaussianPeak::SetCentError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 359 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetCont()
void GamR::TK::BPeak::SetCont (TH1 * hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background, Option_t * foption = "", Option_t * option = "")
#include <src/lib/toolkit/Peak.hh>
Definition at line 146 of file Peak.cc.
References GamR::TK::Gate::GetHigh(), and GamR::TK::Gate::GetLow().
Referenced by Set().
SetGate() [1/3]
int GamR::TK::Gate::SetGate ()
#include <src/lib/toolkit/Gate.hh>
Definition at line 76 of file Gate.cc.
References SetGate().
Referenced by Gate(), Gate(), Gate(), GamR::Nucleus::Transition::AddBackground(), GamR::Nucleus::Transition::AddBackground(), GamR::Spect::BackgroundSubtractX(), GamR::Spect::BackgroundSubtractX(), GamR::Spect::BackgroundSubtractY(), GamR::Spect::BackgroundSubtractY(), GamR::Spect::Counts(), GamR::Spect::Integral(), GamR::Spect::NormSpectra(), GamR::Spect::NormSpectraBackSub(), GamR::TK::BPeak::Set(), GamR::TK::BPeak::Set(), GamR::Nucleus::Transition::SetBackground(), GamR::Nucleus::Transition::SetBackground(), and SetGate().
SetGate() [2/3]
void GamR::TK::Gate::SetGate (double l, double h) inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 60 of file Gate.hh.
References Valid().
SetGate() [3/3]
int GamR::TK::Gate::SetGate (TVirtualPad * canvas, Option_t * opt = "")
#include <src/lib/toolkit/Gate.hh>
Set gate bounds by mouse click.
Parameters
canvas Pointer to a canvas cointaining some coordinate system. Not tested for anything other than a single histogram.
Returns
Return value < 0 means a failure of some kind, otherwise the gate values have been set successfully
Definition at line 86 of file Gate.cc.
References Valid().
SetHigh() [1/2]
void GamR::TK::Gate::SetHigh (double h) inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 68 of file Gate.hh.
References Valid().
SetHigh() [2/2]
void GamR::TK::Gate::SetHigh (std::string h) inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 69 of file Gate.hh.
References Valid().
SetLow() [1/2]
void GamR::TK::Gate::SetLow (double l) inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 66 of file Gate.hh.
References Valid().
SetLow() [2/2]
void GamR::TK::Gate::SetLow (std::string l) inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 67 of file Gate.hh.
References Valid().
SetParameters() [1/7]
virtual void GamR::TK::FPeak::SetParameters (std::vector< double > params) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 148 of file Peak.hh.
SetParameters() [2/7]
void GamR::TK::GaussianPeak::SetParameters (std::vector< double > params) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 173 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetParameters() [3/7]
void GamR::TK::OneTailGaussianPeak::SetParameters (std::vector< double > params) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 248 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetParameters() [4/7]
void GamR::TK::OneTailStepGaussianPeak::SetParameters (std::vector< double > params) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 281 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetParameters() [5/7]
void GamR::TK::StepGaussianPeak::SetParameters (std::vector< double > params) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 208 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetParameters() [6/7]
void GamR::TK::TwoTailGaussianPeak::SetParameters (std::vector< double > params) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 320 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetParameters() [7/7]
void GamR::TK::TwoTailStepGaussianPeak::SetParameters (std::vector< double > params) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 354 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetParErrors() [1/7]
virtual void GamR::TK::FPeak::SetParErrors (std::vector< double > errors) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 149 of file Peak.hh.
SetParErrors() [2/7]
void GamR::TK::GaussianPeak::SetParErrors (std::vector< double > errors) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 174 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetParErrors() [3/7]
void GamR::TK::OneTailGaussianPeak::SetParErrors (std::vector< double > errors) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 249 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetParErrors() [4/7]
void GamR::TK::OneTailStepGaussianPeak::SetParErrors (std::vector< double > errors) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 282 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetParErrors() [5/7]
void GamR::TK::StepGaussianPeak::SetParErrors (std::vector< double > errors) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 209 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetParErrors() [6/7]
void GamR::TK::TwoTailGaussianPeak::SetParErrors (std::vector< double > errors) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 321 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetParErrors() [7/7]
void GamR::TK::TwoTailStepGaussianPeak::SetParErrors (std::vector< double > errors) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::FPeak.
Definition at line 355 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetPoint()
void GamR::TK::BPeak::SetPoint (TH1 * hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background, Option_t * foption = "", Option_t * option = "")
#include <src/lib/toolkit/Peak.hh>
Definition at line 227 of file Peak.cc.
References GamR::TK::Gate::GetHigh(), and GamR::TK::Gate::GetLow().
Referenced by Set(), and SetStep().
SetScale()
void GamR::TK::Gate::SetScale (double s) inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 70 of file Gate.hh.
References GetWidth().
SetStep()
void GamR::TK::BPeak::SetStep (TH1 * hist, GamR::TK::Gate peak, std::vector< GamR::TK::Gate > background, Option_t * foption = "", Option_t * option = "")
#include <src/lib/toolkit/Peak.hh>
Definition at line 372 of file Peak.cc.
References GetCent(), GetCentError(), GetWidth(), GetWidthError(), and SetPoint().
Referenced by Set().
SetWidth() [1/7]
void GamR::TK::GaussianPeak::SetWidth (double width) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 179 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetWidth() [2/7]
void GamR::TK::OneTailGaussianPeak::SetWidth (double width) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 254 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetWidth() [3/7]
void GamR::TK::OneTailStepGaussianPeak::SetWidth (double width) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 287 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetWidth() [4/7]
virtual void GamR::TK::Peak::SetWidth (double width) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 51 of file Peak.hh.
SetWidth() [5/7]
void GamR::TK::StepGaussianPeak::SetWidth (double width) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 214 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetWidth() [6/7]
void GamR::TK::TwoTailGaussianPeak::SetWidth (double width) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 326 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetWidth() [7/7]
void GamR::TK::TwoTailStepGaussianPeak::SetWidth (double width) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 360 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetWidthError() [1/7]
void GamR::TK::GaussianPeak::SetWidthError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 180 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetWidthError() [2/7]
void GamR::TK::OneTailGaussianPeak::SetWidthError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 255 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetWidthError() [3/7]
void GamR::TK::OneTailStepGaussianPeak::SetWidthError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 288 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetWidthError() [4/7]
virtual void GamR::TK::Peak::SetWidthError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented in GamR::TK::GaussianPeak, GamR::TK::OneTailGaussianPeak, GamR::TK::OneTailStepGaussianPeak, GamR::TK::StepGaussianPeak, GamR::TK::TwoTailGaussianPeak, and GamR::TK::TwoTailStepGaussianPeak.
Definition at line 52 of file Peak.hh.
SetWidthError() [5/7]
void GamR::TK::StepGaussianPeak::SetWidthError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 215 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetWidthError() [6/7]
void GamR::TK::TwoTailGaussianPeak::SetWidthError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 327 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
SetWidthError() [7/7]
void GamR::TK::TwoTailStepGaussianPeak::SetWidthError (double error) inline virtual
#include <src/lib/toolkit/Peak.hh>
Reimplemented from GamR::TK::Peak.
Definition at line 361 of file Peak.hh.
References GamR::TK::FPeak::fPeakFunc.
Valid()
Bool_t GamR::TK::Gate::Valid () inline
#include <src/lib/toolkit/Gate.hh>
Definition at line 115 of file Gate.hh.
Referenced by Gate(), SetGate(), SetGate(), SetHigh(), SetHigh(), SetLow(), and SetLow().
Variable Documentation
fHigh
double GamR::TK::FPeak::fHigh protected
Definition at line 133 of file Peak.hh.
Referenced by FPeak(), GamR::TK::OneTailGaussianPeak::GetArea(), GamR::TK::OneTailStepGaussianPeak::GetArea(), GamR::TK::TwoTailGaussianPeak::GetArea(), GamR::TK::TwoTailStepGaussianPeak::GetArea(), GamR::TK::OneTailGaussianPeak::GetAreaError(), GamR::TK::OneTailStepGaussianPeak::GetAreaError(), GamR::TK::TwoTailGaussianPeak::GetAreaError(), GamR::TK::TwoTailStepGaussianPeak::GetAreaError(), GamR::TK::GaussianPeak::GetGaussFunc(), GamR::TK::OneTailGaussianPeak::GetGaussFunc(), GamR::TK::OneTailStepGaussianPeak::GetGaussFunc(), GamR::TK::StepGaussianPeak::GetGaussFunc(), GamR::TK::TwoTailGaussianPeak::GetGaussFunc(), GamR::TK::TwoTailStepGaussianPeak::GetGaussFunc(), GamR::TK::OneTailStepGaussianPeak::GetStepFunc(), GamR::TK::StepGaussianPeak::GetStepFunc(), and GamR::TK::TwoTailStepGaussianPeak::GetStepFunc().
fLow
double GamR::TK::FPeak::fLow protected
Definition at line 132 of file Peak.hh.
Referenced by FPeak(), GamR::TK::OneTailGaussianPeak::GetArea(), GamR::TK::OneTailStepGaussianPeak::GetArea(), GamR::TK::TwoTailGaussianPeak::GetArea(), GamR::TK::TwoTailStepGaussianPeak::GetArea(), GamR::TK::OneTailGaussianPeak::GetAreaError(), GamR::TK::OneTailStepGaussianPeak::GetAreaError(), GamR::TK::TwoTailGaussianPeak::GetAreaError(), GamR::TK::TwoTailStepGaussianPeak::GetAreaError(), GamR::TK::GaussianPeak::GetGaussFunc(), GamR::TK::OneTailGaussianPeak::GetGaussFunc(), GamR::TK::OneTailStepGaussianPeak::GetGaussFunc(), GamR::TK::StepGaussianPeak::GetGaussFunc(), GamR::TK::TwoTailGaussianPeak::GetGaussFunc(), GamR::TK::TwoTailStepGaussianPeak::GetGaussFunc(), GamR::TK::OneTailStepGaussianPeak::GetStepFunc(), GamR::TK::StepGaussianPeak::GetStepFunc(), and GamR::TK::TwoTailStepGaussianPeak::GetStepFunc().
fPeakFunc
TF1* GamR::TK::FPeak::fPeakFunc protected
Definition at line 131 of file Peak.hh.
Referenced by GamR::TK::GaussianPeak::GaussianPeak(), GamR::TK::OneTailGaussianPeak::OneTailGaussianPeak(), GamR::TK::OneTailStepGaussianPeak::OneTailStepGaussianPeak(), GamR::TK::StepGaussianPeak::StepGaussianPeak(), GamR::TK::TwoTailGaussianPeak::TwoTailGaussianPeak(), GamR::TK::TwoTailStepGaussianPeak::TwoTailStepGaussianPeak(), GamR::TK::GaussianPeak::GetAmp(), GamR::TK::OneTailGaussianPeak::GetAmp(), GamR::TK::OneTailStepGaussianPeak::GetAmp(), GamR::TK::StepGaussianPeak::GetAmp(), GamR::TK::TwoTailGaussianPeak::GetAmp(), GamR::TK::TwoTailStepGaussianPeak::GetAmp(), GamR::TK::GaussianPeak::GetAmpError(), GamR::TK::OneTailGaussianPeak::GetAmpError(), GamR::TK::OneTailStepGaussianPeak::GetAmpError(), GamR::TK::StepGaussianPeak::GetAmpError(), GamR::TK::TwoTailGaussianPeak::GetAmpError(), GamR::TK::TwoTailStepGaussianPeak::GetAmpError(), GamR::TK::GaussianPeak::GetArea(), GamR::TK::OneTailGaussianPeak::GetArea(), GamR::TK::StepGaussianPeak::GetArea(), GamR::TK::TwoTailGaussianPeak::GetArea(), GamR::TK::GaussianPeak::GetAreaError(), GamR::TK::OneTailGaussianPeak::GetAreaError(), GamR::TK::StepGaussianPeak::GetAreaError(), GamR::TK::TwoTailGaussianPeak::GetAreaError(), GamR::TK::GaussianPeak::GetCent(), GamR::TK::OneTailGaussianPeak::GetCent(), GamR::TK::OneTailStepGaussianPeak::GetCent(), GamR::TK::StepGaussianPeak::GetCent(), GamR::TK::TwoTailGaussianPeak::GetCent(), GamR::TK::TwoTailStepGaussianPeak::GetCent(), GamR::TK::GaussianPeak::GetCentError(), GamR::TK::OneTailGaussianPeak::GetCentError(), GamR::TK::OneTailStepGaussianPeak::GetCentError(), GamR::TK::StepGaussianPeak::GetCentError(), GamR::TK::TwoTailGaussianPeak::GetCentError(), GamR::TK::TwoTailStepGaussianPeak::GetCentError(), GetFunc(), GamR::TK::GaussianPeak::GetGaussFunc(), GamR::TK::OneTailGaussianPeak::GetGaussFunc(), GamR::TK::OneTailStepGaussianPeak::GetGaussFunc(), GamR::TK::StepGaussianPeak::GetGaussFunc(), GamR::TK::TwoTailGaussianPeak::GetGaussFunc(), GamR::TK::TwoTailStepGaussianPeak::GetGaussFunc(), GamR::TK::OneTailStepGaussianPeak::GetStepFunc(), GamR::TK::StepGaussianPeak::GetStepFunc(), GamR::TK::TwoTailStepGaussianPeak::GetStepFunc(), GamR::TK::GaussianPeak::GetWidth(), GamR::TK::OneTailGaussianPeak::GetWidth(), GamR::TK::OneTailStepGaussianPeak::GetWidth(), GamR::TK::StepGaussianPeak::GetWidth(), GamR::TK::TwoTailGaussianPeak::GetWidth(), GamR::TK::TwoTailStepGaussianPeak::GetWidth(), GamR::TK::GaussianPeak::GetWidthError(), GamR::TK::OneTailGaussianPeak::GetWidthError(), GamR::TK::OneTailStepGaussianPeak::GetWidthError(), GamR::TK::StepGaussianPeak::GetWidthError(), GamR::TK::TwoTailGaussianPeak::GetWidthError(), GamR::TK::TwoTailStepGaussianPeak::GetWidthError(), GamR::TK::GaussianPeak::SetAmp(), GamR::TK::OneTailGaussianPeak::SetAmp(), GamR::TK::OneTailStepGaussianPeak::SetAmp(), GamR::TK::StepGaussianPeak::SetAmp(), GamR::TK::TwoTailGaussianPeak::SetAmp(), GamR::TK::TwoTailStepGaussianPeak::SetAmp(), GamR::TK::GaussianPeak::SetAmpError(), GamR::TK::OneTailGaussianPeak::SetAmpError(), GamR::TK::OneTailStepGaussianPeak::SetAmpError(), GamR::TK::StepGaussianPeak::SetAmpError(), GamR::TK::TwoTailGaussianPeak::SetAmpError(), GamR::TK::TwoTailStepGaussianPeak::SetAmpError(), GamR::TK::GaussianPeak::SetCent(), GamR::TK::OneTailGaussianPeak::SetCent(), GamR::TK::OneTailStepGaussianPeak::SetCent(), GamR::TK::StepGaussianPeak::SetCent(), GamR::TK::TwoTailGaussianPeak::SetCent(), GamR::TK::TwoTailStepGaussianPeak::SetCent(), GamR::TK::GaussianPeak::SetCentError(), GamR::TK::OneTailGaussianPeak::SetCentError(), GamR::TK::OneTailStepGaussianPeak::SetCentError(), GamR::TK::StepGaussianPeak::SetCentError(), GamR::TK::TwoTailGaussianPeak::SetCentError(), GamR::TK::TwoTailStepGaussianPeak::SetCentError(), GamR::TK::GaussianPeak::SetParameters(), GamR::TK::OneTailGaussianPeak::SetParameters(), GamR::TK::OneTailStepGaussianPeak::SetParameters(), GamR::TK::StepGaussianPeak::SetParameters(), GamR::TK::TwoTailGaussianPeak::SetParameters(), GamR::TK::TwoTailStepGaussianPeak::SetParameters(), GamR::TK::GaussianPeak::SetParErrors(), GamR::TK::OneTailGaussianPeak::SetParErrors(), GamR::TK::OneTailStepGaussianPeak::SetParErrors(), GamR::TK::StepGaussianPeak::SetParErrors(), GamR::TK::TwoTailGaussianPeak::SetParErrors(), GamR::TK::TwoTailStepGaussianPeak::SetParErrors(), GamR::TK::GaussianPeak::SetWidth(), GamR::TK::OneTailGaussianPeak::SetWidth(), GamR::TK::OneTailStepGaussianPeak::SetWidth(), GamR::TK::StepGaussianPeak::SetWidth(), GamR::TK::TwoTailGaussianPeak::SetWidth(), GamR::TK::TwoTailStepGaussianPeak::SetWidth(), GamR::TK::GaussianPeak::SetWidthError(), GamR::TK::OneTailGaussianPeak::SetWidthError(), GamR::TK::OneTailStepGaussianPeak::SetWidthError(), GamR::TK::StepGaussianPeak::SetWidthError(), GamR::TK::TwoTailGaussianPeak::SetWidthError(), and GamR::TK::TwoTailStepGaussianPeak::SetWidthError().
fPeakType
PeakType GamR::TK::FPeak::fPeakType protected
Definition at line 134 of file Peak.hh.
Referenced by FPeak(), and GetPeakType().