GamR: GamR::Spect::BackSub2D Class Reference
GamR::Spect::BackSub2D Class Reference
#include <BackSub.hh>
Public Member Functions
int SetPeak (GamR::TK::Gate x, GamR::TK::Gate y)
int SetPeak (double x1, double y1, double x2, double y2)
int AddBackX (GamR::TK::Gate x)
int AddBackY (GamR::TK::Gate y)
int AddBackX (double x1, double x2)
int AddBackY (double y1, double y2)
int AddBackDiag (GamR::TK::Gate x, GamR::TK::Gate y)
int AddBackDiag (double x1, double y1, double x2, double y2)
int AddBackBack (GamR::TK::Gate x, GamR::TK::Gate y)
int AddBackBack (double x1, double y1, double x2, double y2)
BackSub2D (TH2D *hist)
int SetPeak (TCanvas *canvas)
int AddBackX (TCanvas *canvas)
int AddBackY (TCanvas *canvas)
int AddBackBack (TCanvas *canvas)
int AddBackDiag (TCanvas *canvas)
TH2D * Subtract (TH2D *hist)
double GetPeakArea ()
double GetPeakAreaError ()
double GetPeakCounts ()
double GetPeakCountsError ()
Public Attributes
GamR::TK::Gate fPeakX
GamR::TK::Gate fPeakY
std::vector< GamR::TK::Gate > fBackY
std::vector< GamR::TK::Gate > fBackX
std::vector< GamR::TK::Gate > fBackDiagX
std::vector< GamR::TK::Gate > fBackDiagY
std::vector< GamR::TK::Gate > fBackBackX
std::vector< GamR::TK::Gate > fBackBackY
TH1D * y_sub
TH1D * x_sub
TH2D * unsubtracted
TH2D * subtracted
Detailed Description
Definition at line 13 of file BackSub.hh.
Constructor & Destructor Documentation
BackSub2D()
GamR::Spect::BackSub2D::BackSub2D (TH2D * hist)
Definition at line 622 of file BackSub.cc.
References AddBackBack(), AddBackDiag(), AddBackX(), AddBackY(), GetPeakCounts(), GetPeakCountsError(), SetPeak(), and Subtract().
Member Function Documentation
AddBackBack() [1/3]
int GamR::Spect::BackSub2D::AddBackBack (double x1, double y1, double x2, double y2) inline
Definition at line 85 of file BackSub.hh.
References AddBackBack().
AddBackBack() [2/3]
int GamR::Spect::BackSub2D::AddBackBack (GamR::TK::Gate x, GamR::TK::Gate y) inline
Definition at line 79 of file BackSub.hh.
References fBackBackX, and fBackBackY.
Referenced by BackSub2D(), and AddBackBack().
AddBackBack() [3/3]
int GamR::Spect::BackSub2D::AddBackBack (TCanvas * canvas)
Definition at line 341 of file BackSub.cc.
References fBackBackX, and fBackBackY.
AddBackDiag() [1/3]
int GamR::Spect::BackSub2D::AddBackDiag (double x1, double y1, double x2, double y2) inline
Definition at line 73 of file BackSub.hh.
References AddBackDiag().
AddBackDiag() [2/3]
int GamR::Spect::BackSub2D::AddBackDiag (GamR::TK::Gate x, GamR::TK::Gate y) inline
Definition at line 67 of file BackSub.hh.
References fBackDiagX, and fBackDiagY.
Referenced by BackSub2D(), and AddBackDiag().
AddBackDiag() [3/3]
int GamR::Spect::BackSub2D::AddBackDiag (TCanvas * canvas)
Definition at line 258 of file BackSub.cc.
References fBackDiagX, and fBackDiagY.
AddBackX() [1/3]
int GamR::Spect::BackSub2D::AddBackX (double x1, double x2) inline
Definition at line 57 of file BackSub.hh.
References AddBackX().
AddBackX() [2/3]
int GamR::Spect::BackSub2D::AddBackX (GamR::TK::Gate x) inline
Definition at line 47 of file BackSub.hh.
References fBackX.
Referenced by BackSub2D(), and AddBackX().
AddBackX() [3/3]
int GamR::Spect::BackSub2D::AddBackX (TCanvas * canvas)
Definition at line 93 of file BackSub.cc.
References fBackX, fPeakY, GamR::TK::Gate::GetHigh(), and GamR::TK::Gate::GetLow().
AddBackY() [1/3]
int GamR::Spect::BackSub2D::AddBackY (double y1, double y2) inline
Definition at line 62 of file BackSub.hh.
References AddBackY().
AddBackY() [2/3]
int GamR::Spect::BackSub2D::AddBackY (GamR::TK::Gate y) inline
Definition at line 52 of file BackSub.hh.
References fBackY.
Referenced by BackSub2D(), and AddBackY().
AddBackY() [3/3]
int GamR::Spect::BackSub2D::AddBackY (TCanvas * canvas)
Definition at line 175 of file BackSub.cc.
References fBackY, fPeakX, GamR::TK::Gate::GetHigh(), and GamR::TK::Gate::GetLow().
GetPeakArea()
double GamR::Spect::BackSub2D::GetPeakArea ()
GetPeakAreaError()
double GamR::Spect::BackSub2D::GetPeakAreaError ()
GetPeakCounts()
double GamR::Spect::BackSub2D::GetPeakCounts ()
Definition at line 602 of file BackSub.cc.
References subtracted.
Referenced by BackSub2D().
GetPeakCountsError()
double GamR::Spect::BackSub2D::GetPeakCountsError ()
Definition at line 612 of file BackSub.cc.
References subtracted.
Referenced by BackSub2D().
SetPeak() [1/3]
int GamR::Spect::BackSub2D::SetPeak (double x1, double y1, double x2, double y2) inline
Definition at line 41 of file BackSub.hh.
References SetPeak().
SetPeak() [2/3]
int GamR::Spect::BackSub2D::SetPeak (GamR::TK::Gate x, GamR::TK::Gate y) inline
Definition at line 35 of file BackSub.hh.
References fPeakX, and fPeakY.
Referenced by BackSub2D(), and SetPeak().
SetPeak() [3/3]
int GamR::Spect::BackSub2D::SetPeak (TCanvas * canvas)
Definition at line 10 of file BackSub.cc.
References fPeakX, and fPeakY.
Subtract()
TH2D * GamR::Spect::BackSub2D::Subtract (TH2D * hist)
Definition at line 422 of file BackSub.cc.
References fBackBackX, fBackBackY, fBackDiagX, fBackDiagY, fBackX, fBackY, fPeakX, fPeakY, GamR::TK::Gate::GetHigh(), GamR::TK::Gate::GetLow(), subtracted, unsubtracted, x_sub, and y_sub.
Referenced by BackSub2D().
Member Data Documentation
fBackBackX
std::vector<GamR::TK::Gate > GamR::Spect::BackSub2D::fBackBackX
Definition at line 26 of file BackSub.hh.
Referenced by AddBackBack(), and Subtract().
fBackBackY
std::vector<GamR::TK::Gate > GamR::Spect::BackSub2D::fBackBackY
Definition at line 27 of file BackSub.hh.
Referenced by AddBackBack(), and Subtract().
fBackDiagX
std::vector<GamR::TK::Gate > GamR::Spect::BackSub2D::fBackDiagX
Definition at line 22 of file BackSub.hh.
Referenced by AddBackDiag(), and Subtract().
fBackDiagY
std::vector<GamR::TK::Gate > GamR::Spect::BackSub2D::fBackDiagY
Definition at line 23 of file BackSub.hh.
Referenced by AddBackDiag(), and Subtract().
fBackX
std::vector<GamR::TK::Gate > GamR::Spect::BackSub2D::fBackX
Definition at line 19 of file BackSub.hh.
Referenced by AddBackX(), and Subtract().
fBackY
std::vector<GamR::TK::Gate > GamR::Spect::BackSub2D::fBackY
Definition at line 18 of file BackSub.hh.
Referenced by AddBackY(), and Subtract().
fPeakX
GamR::TK::Gate GamR::Spect::BackSub2D::fPeakX
Definition at line 15 of file BackSub.hh.
Referenced by AddBackY(), SetPeak(), and Subtract().
fPeakY
GamR::TK::Gate GamR::Spect::BackSub2D::fPeakY
Definition at line 16 of file BackSub.hh.
Referenced by AddBackX(), SetPeak(), and Subtract().
subtracted
TH2D* GamR::Spect::BackSub2D::subtracted
Definition at line 33 of file BackSub.hh.
Referenced by GetPeakCounts(), GetPeakCountsError(), and Subtract().
unsubtracted
TH2D* GamR::Spect::BackSub2D::unsubtracted
Definition at line 32 of file BackSub.hh.
Referenced by Subtract().
x_sub
TH1D* GamR::Spect::BackSub2D::x_sub
Definition at line 30 of file BackSub.hh.
Referenced by Subtract().
y_sub
TH1D* GamR::Spect::BackSub2D::y_sub
Definition at line 29 of file BackSub.hh.
Referenced by Subtract().
The documentation for this class was generated from the following files:
src/lib/spect/BackSub.hh
src/lib/spect/BackSub.cc