GamR: GamR::Nucleus::LevelSchemeDraw::Transition Class Reference
GamR::Nucleus::LevelSchemeDraw::Transition Class Reference
#include <LevelSchemeDraw.hh>
Public Member Functions
Transition ()
Transition (Scheme *scheme, State *initial, State *final, double width, double start, double stop, double labelpos, EColor color)
~Transition ()
void SetStartStop (double start, double stop)
void Paint (Option_t *option="")
Int_t DistancetoPrimitive (Int_t px, Int_t py)
void ExecuteEvent (Int_t event, Int_t px, Int_t py)
void Draw (Option_t *option="")
double GetX1 ()
double GetX2 ()
double GetY1 ()
double GetY2 ()
double GetPerpTheta ()
double GetLength ()
double GetWidth ()
double GetWidthX ()
double GetWidthY ()
double GetHeadWidth ()
double GetHeadWidthX ()
double GetHeadWidthY ()
double GetHeadLength ()
void PaintArrow ()
Public Attributes
Scheme * fScheme
State * fInitial
State * fFinal
Double_t fStart
Double_t fStop
Double_t fWidth
Double_t fLabelPos
TText * fLabel = NULL
TBox * fLabelBox = NULL
double textsize = 0.05
Detailed Description
Definition at line 70 of file LevelSchemeDraw.hh.
Constructor & Destructor Documentation
Transition() [1/2]
GamR::Nucleus::LevelSchemeDraw::Transition::Transition () inline
Definition at line 83 of file LevelSchemeDraw.hh.
References fFinal, fInitial, fLabel, fLabelBox, fLabelPos, fStart, and fStop.
Transition() [2/2]
GamR::Nucleus::LevelSchemeDraw::Transition::Transition (Scheme * scheme, State * initial, State * final, double width, double start, double stop, double labelpos, EColor color) inline
Definition at line 84 of file LevelSchemeDraw.hh.
References fFinal, fInitial, fLabel, fLabelBox, fLabelPos, fScheme, fStart, fStop, and fWidth.
~Transition()
GamR::Nucleus::LevelSchemeDraw::Transition::~Transition () inline
Definition at line 94 of file LevelSchemeDraw.hh.
Member Function Documentation
DistancetoPrimitive()
Int_t GamR::Nucleus::LevelSchemeDraw::Transition::DistancetoPrimitive (Int_t px, Int_t py)
Definition at line 314 of file LevelSchemeDraw.cc.
References GetX1(), GetX2(), GetY1(), GetY2(), px(), and py().
Referenced by ExecuteEvent().
Draw()
void GamR::Nucleus::LevelSchemeDraw::Transition::Draw (Option_t * option = "") inline
Definition at line 99 of file LevelSchemeDraw.hh.
ExecuteEvent()
void GamR::Nucleus::LevelSchemeDraw::Transition::ExecuteEvent (Int_t event, Int_t px, Int_t py)
Definition at line 334 of file LevelSchemeDraw.cc.
References DistancetoPrimitive(), fFinal, fInitial, fStart, fStop, GetX1(), GetX2(), GetY1(), GetY2(), px(), and py().
GetHeadLength()
double GamR::Nucleus::LevelSchemeDraw::Transition::GetHeadLength ()
Definition at line 214 of file LevelSchemeDraw.cc.
References GetHeadWidth(), and GetLength().
Referenced by PaintArrow().
GetHeadWidth()
double GamR::Nucleus::LevelSchemeDraw::Transition::GetHeadWidth ()
Definition at line 200 of file LevelSchemeDraw.cc.
References GetWidth().
Referenced by GetHeadLength(), GetHeadWidthX(), and GetHeadWidthY().
GetHeadWidthX()
double GamR::Nucleus::LevelSchemeDraw::Transition::GetHeadWidthX ()
Definition at line 202 of file LevelSchemeDraw.cc.
References GetHeadWidth(), and GetPerpTheta().
Referenced by PaintArrow().
GetHeadWidthY()
double GamR::Nucleus::LevelSchemeDraw::Transition::GetHeadWidthY ()
Definition at line 208 of file LevelSchemeDraw.cc.
References GetHeadWidth(), and GetPerpTheta().
Referenced by PaintArrow().
GetLength()
double GamR::Nucleus::LevelSchemeDraw::Transition::GetLength ()
Definition at line 132 of file LevelSchemeDraw.cc.
References GetX1(), GetX2(), GetY1(), and GetY2().
Referenced by GetHeadLength().
GetPerpTheta()
double GamR::Nucleus::LevelSchemeDraw::Transition::GetPerpTheta ()
Definition at line 155 of file LevelSchemeDraw.cc.
References GetX1(), GetX2(), GetY1(), and GetY2().
Referenced by GetHeadWidthX(), GetHeadWidthY(), GetWidth(), GetWidthX(), and GetWidthY().
GetWidth()
double GamR::Nucleus::LevelSchemeDraw::Transition::GetWidth ()
Definition at line 181 of file LevelSchemeDraw.cc.
References fScheme, fWidth, and GetPerpTheta().
Referenced by GetHeadWidth(), GetWidthX(), GetWidthY(), and PaintArrow().
GetWidthX()
double GamR::Nucleus::LevelSchemeDraw::Transition::GetWidthX ()
Definition at line 188 of file LevelSchemeDraw.cc.
References GetPerpTheta(), and GetWidth().
Referenced by PaintArrow().
GetWidthY()
double GamR::Nucleus::LevelSchemeDraw::Transition::GetWidthY ()
Definition at line 194 of file LevelSchemeDraw.cc.
References GetPerpTheta(), and GetWidth().
Referenced by PaintArrow().
GetX1()
double GamR::Nucleus::LevelSchemeDraw::Transition::GetX1 ()
Definition at line 216 of file LevelSchemeDraw.cc.
References fInitial, and fStart.
Referenced by DistancetoPrimitive(), ExecuteEvent(), GetLength(), GetPerpTheta(), and Paint().
GetX2()
double GamR::Nucleus::LevelSchemeDraw::Transition::GetX2 ()
Definition at line 218 of file LevelSchemeDraw.cc.
References fFinal, and fStop.
Referenced by DistancetoPrimitive(), ExecuteEvent(), GetLength(), GetPerpTheta(), and Paint().
GetY1()
double GamR::Nucleus::LevelSchemeDraw::Transition::GetY1 ()
Definition at line 220 of file LevelSchemeDraw.cc.
References fInitial.
Referenced by DistancetoPrimitive(), ExecuteEvent(), GetLength(), GetPerpTheta(), and Paint().
GetY2()
double GamR::Nucleus::LevelSchemeDraw::Transition::GetY2 ()
Definition at line 222 of file LevelSchemeDraw.cc.
References fFinal.
Referenced by DistancetoPrimitive(), ExecuteEvent(), GetLength(), GetPerpTheta(), and Paint().
Paint()
void GamR::Nucleus::LevelSchemeDraw::Transition::Paint (Option_t * option = "")
Definition at line 282 of file LevelSchemeDraw.cc.
References fLabel, fLabelBox, fLabelPos, fWidth, GetX1(), GetX2(), GetY1(), GetY2(), PaintArrow(), and textsize.
PaintArrow()
void GamR::Nucleus::LevelSchemeDraw::Transition::PaintArrow ()
Definition at line 224 of file LevelSchemeDraw.cc.
References fFinal, fInitial, fStart, fStop, GetHeadLength(), GetHeadWidthX(), GetHeadWidthY(), GetWidth(), GetWidthX(), and GetWidthY().
Referenced by Paint().
SetStartStop()
void GamR::Nucleus::LevelSchemeDraw::Transition::SetStartStop (double start, double stop) inline
Definition at line 95 of file LevelSchemeDraw.hh.
References fStart, and fStop.
Member Data Documentation
fFinal
State* GamR::Nucleus::LevelSchemeDraw::Transition::fFinal
Definition at line 74 of file LevelSchemeDraw.hh.
Referenced by Transition(), Transition(), ExecuteEvent(), GetX2(), GetY2(), and PaintArrow().
fInitial
State* GamR::Nucleus::LevelSchemeDraw::Transition::fInitial
Definition at line 73 of file LevelSchemeDraw.hh.
Referenced by Transition(), Transition(), ExecuteEvent(), GetX1(), GetY1(), and PaintArrow().
fLabel
TText* GamR::Nucleus::LevelSchemeDraw::Transition::fLabel = NULL
Definition at line 80 of file LevelSchemeDraw.hh.
Referenced by Transition(), Transition(), and Paint().
fLabelBox
TBox* GamR::Nucleus::LevelSchemeDraw::Transition::fLabelBox = NULL
Definition at line 81 of file LevelSchemeDraw.hh.
Referenced by Transition(), Transition(), and Paint().
fLabelPos
Double_t GamR::Nucleus::LevelSchemeDraw::Transition::fLabelPos
Definition at line 79 of file LevelSchemeDraw.hh.
Referenced by Transition(), Transition(), and Paint().
fScheme
Scheme* GamR::Nucleus::LevelSchemeDraw::Transition::fScheme
Definition at line 72 of file LevelSchemeDraw.hh.
Referenced by Transition(), and GetWidth().
fStart
Double_t GamR::Nucleus::LevelSchemeDraw::Transition::fStart
Definition at line 76 of file LevelSchemeDraw.hh.
Referenced by Transition(), Transition(), ExecuteEvent(), GetX1(), PaintArrow(), and SetStartStop().
fStop
Double_t GamR::Nucleus::LevelSchemeDraw::Transition::fStop
Definition at line 77 of file LevelSchemeDraw.hh.
Referenced by Transition(), Transition(), ExecuteEvent(), GetX2(), PaintArrow(), and SetStartStop().
fWidth
Double_t GamR::Nucleus::LevelSchemeDraw::Transition::fWidth
Definition at line 78 of file LevelSchemeDraw.hh.
Referenced by Transition(), GetWidth(), and Paint().
textsize
double GamR::Nucleus::LevelSchemeDraw::Transition::textsize = 0.05
Definition at line 82 of file LevelSchemeDraw.hh.
Referenced by GamR::Nucleus::LevelSchemeDraw::Scheme::AddTransition(), and Paint().
The documentation for this class was generated from the following files:
src/lib/nucleus/LevelSchemeDraw.hh
src/lib/nucleus/LevelSchemeDraw.cc