GamR: GamR::AngDist Namespace Reference
GamR::AngDist Namespace Reference
AngDist
Classes
class AngCorr
class AngCorrFit
class DoubleGaussianDistr
class GaussianDistr
class PopulationParameter
class SolidAttenuation
class SpinPrec
class StatTensor
Functions
double Fk (double k, double jf, double lambda, double lambdaPrime, double ji)
double Fgen (double k, double k2, double k1, double jf, double lambda, double lambdaPrime, double ji)
double Ak (double k, double ji, double lambda, double lambdaPrime, double jf, double delta)
double Agen (double k, double k1, double k2, double jf, double lambda, double lambdaPrime, double ji, double delta)
double W (double theta, double ji, double lambda, double lambdaPrime, double jf, double delta, StatTensor *rho, SolidAttenuation *Qk, double kmax)
std::function< std::complex< double >(double, double, double, double, double) > TransFrame (std::complex< double >(&Gk)(double, double, double, double, double), double alpha, double beta, double gamma)
std::vector< double > W (std::vector< double > theta, double ji, double lambda, double lambdaPrime, double jf, double delta, StatTensor *rho, SolidAttenuation *Qk, double kmax)
double GetTauG (double E)
TH1D * RatioFunction (TH1 *h1, TH1 *h2)
TH1D * RatioFunction (TH1 *h1, TH1 *h2, const char *name)
TH1D * RatioFunction (TH2 *h1, TH2 *h2, GamR::TK::Gate peak, GamR::TK::Gate background)
TH1D * RatioFunction (TH2 *h1, TH2 *h2, GamR::TK::Gate peak, GamR::TK::Gate background, const char *name)
TH1D * RatioFunction (TH2 *h1, TH2 *h2, GamR::Nucleus::Transition peak)
TH1D * RatioFunction (TH2 *h1, TH2 *h2, GamR::Nucleus::Transition peak, const char *name)
TH1D * AutoCorrelation (TH1 *h1, double start, double stop)
TH1D * AutoCorrelation (TH1 *h1)
TH1D * AutoCorrelation (TH1 *h1, const char *name)
TH1D * AutoCorrelation (TH1 *h1, double start, double stop, const char *name)
double djmm (double j, double m, double mprime, double beta)
std::complex< double > BigD (double j, double m, double mprime, double alpha, double beta, double gamma)
Detailed Description
Library of tools for all things angular distribution/correlation. Functions to calculate various coefficents, make R(t) functions, double-ratios, etc. etc.
Function Documentation
Agen()
double GamR::AngDist::Agen (double k, double k1, double k2, double jf, double lambda, double lambdaPrime, double ji, double delta)
Generalised Ak coefficients - Equation 5 of AES NIM A 485(2002)753
Definition at line 76 of file AngDist.cc.
References Fgen().
Referenced by GamR::AngDist::StatTensor::ObservedProp(), and GamR::AngDist::StatTensor::UnobservedProp().
Ak()
double GamR::AngDist::Ak (double k, double ji, double lambda, double lambdaPrime, double jf, double delta)
Ak function - Equation 2.44 (Morinaga and Yamazaki), with the statistical tensor removed for consistency with other literature
Definition at line 66 of file AngDist.cc.
References Fk().
Referenced by GamR::AngDist::AngCorr::Ak(), GamR::AngDist::StatTensor::W(), W(), and W().
AutoCorrelation() [1/4]
TH1D * GamR::AngDist::AutoCorrelation (TH1 * h1)
Definition at line 210 of file TDPAD.cc.
References AutoCorrelation().
AutoCorrelation() [2/4]
TH1D * GamR::AngDist::AutoCorrelation (TH1 * h1, const char * name)
Definition at line 215 of file TDPAD.cc.
References AutoCorrelation().
AutoCorrelation() [3/4]
TH1D * GamR::AngDist::AutoCorrelation (TH1 * h1, double start, double stop)
Forms an autocorrelation function of the given histogram between start and stop values. Useful for confirming frequencies that are present in R(t) function data. See https://en.wikipedia.org/wiki/Autocorrelation.
Parameters
h1 Input histogram
start Beginning of section to be correlated
start End of section to be correlated
Definition at line 142 of file TDPAD.cc.
Referenced by AutoCorrelation(), AutoCorrelation(), and AutoCorrelation().
AutoCorrelation() [4/4]
TH1D * GamR::AngDist::AutoCorrelation (TH1 * h1, double start, double stop, const char * name)
Definition at line 223 of file TDPAD.cc.
References AutoCorrelation().
BigD()
std::complex< double > GamR::AngDist::BigD (double j, double m, double mprime, double alpha, double beta, double gamma)
Definition at line 66 of file WignerD.cc.
References djmm().
Referenced by GamR::AngDist::StatTensor::ObservedProp(), TransFrame(), and GamR::AngDist::StatTensor::W().
djmm()
double GamR::AngDist::djmm (double j, double m, double mprime, double beta)
Definition at line 14 of file WignerD.cc.
References GamR::Utils::Fac10().
Referenced by BigD().
Fgen()
double GamR::AngDist::Fgen (double k, double k2, double k1, double jf, double lambda, double lambdaPrime, double ji)
Generalised Fk coefficients - see Equation 12.163 in Hamilton
Parameters
k lambda
k2 lambda_1
k1 lambda_0
jf I1
ji I0
lambda L
lambdaPrime L'
Definition at line 52 of file AngDist.cc.
Referenced by Agen().
Fk()
double GamR::AngDist::Fk (double k, double jf, double lambda, double lambdaPrime, double ji)
Fk coefficients - see Equation 2.42, or 12.168 in Hamilton
Definition at line 32 of file AngDist.cc.
Referenced by Ak(), and GamR::AngDist::AngCorr::Ak().
GetTauG()
double GamR::AngDist::GetTauG (double E)
Definition at line 77 of file SolidAttenuation.cc.
Referenced by GamR::AngDist::SolidAttenuation::SolidAttenuation().
RatioFunction() [1/6]
TH1D * GamR::AngDist::RatioFunction (TH1 * h1, TH1 * h2)
Basic ratio function: creates and returns a TH1D formed by (h1-h2)/(h1+h2). Errors are also calculated correctly. Assumes that h1 and h2 have the same number of bins and axis parameters.
Parameters
h1 First input histogram (i.e., a TAC or time difference spectrum)
h2 Second input histogram
Returns
R(t) function formed from h1 and h2.
Definition at line 37 of file TDPAD.cc.
Referenced by RatioFunction(), RatioFunction(), RatioFunction(), and RatioFunction().
RatioFunction() [2/6]
TH1D * GamR::AngDist::RatioFunction (TH1 * h1, TH1 * h2, const char * name)
Definition at line 60 of file TDPAD.cc.
References RatioFunction().
RatioFunction() [3/6]
TH1D * GamR::AngDist::RatioFunction (TH2 * h1, TH2 * h2, GamR::Nucleus::Transition peak)
Definition at line 123 of file TDPAD.cc.
References GamR::Nucleus::Transition::GetGate(), GamR::Nucleus::Transition::GetGateBG(), and RatioFunction().
RatioFunction() [4/6]
TH1D * GamR::AngDist::RatioFunction (TH2 * h1, TH2 * h2, GamR::Nucleus::Transition peak, const char * name)
Definition at line 128 of file TDPAD.cc.
References GamR::Nucleus::Transition::GetGate(), GamR::Nucleus::Transition::GetGateBG(), and RatioFunction().
RatioFunction() [5/6]
TH1D * GamR::AngDist::RatioFunction (TH2 * h1, TH2 * h2, GamR::TK::Gate peak, GamR::TK::Gate background)
Definition at line 67 of file TDPAD.cc.
References GamR::TK::Gate::ApplyX(), and GamR::TK::Gate::GetBinWidth().
RatioFunction() [6/6]
TH1D * GamR::AngDist::RatioFunction (TH2 * h1, TH2 * h2, GamR::TK::Gate peak, GamR::TK::Gate background, const char * name)
Definition at line 117 of file TDPAD.cc.
References RatioFunction().
TransFrame()
std::function< std::complex< double >(double, double, double, double, double) > GamR::AngDist::TransFrame (std::complex< double >(&)(double, double, double, double, double) Gk, double alpha, double beta, double gamma)
Equation 14 from AES NIM A 485(2002)753 - transforming a Gk coefficient from one frame to another using Wigner D matrices
Parameters
Gk Gk Function in initial frame
alpha Euler angle alpha
beta Euler angle beta
gamma Euler angle gamma
Definition at line 127 of file AngDist.cc.
References BigD().
W() [1/2]
double GamR::AngDist::W (double theta, double ji, double lambda, double lambdaPrime, double jf, double delta, StatTensor * rho, SolidAttenuation * Qk, double kmax)
Equation 2.43 from Morinaga and Yamazaki
This assumes a "nice" geometry where the detectors are in a plane parallel to the beam direction producing the alignment. It will be much faster than the equivalent function found as a member of the StatTensor class, but also much less general.
Parameters
theta Angle between the detector and the beam direction (radians)
ji Initial spin
lambda Multipolarity 1 of the transition
lambdaPrime Multipolarity 2 of the transition
jf Final spin
delta Mixing ratio for multipolarities
rho Statistical tensor specifying the initial state
Qk Solid attenuation coefficients for the detector
kmax Maximum k to be calculated, default =4
Returns
W(theta) - angular distribution value at given theta value
Definition at line 102 of file AngDist.cc.
References Ak(), GamR::AngDist::SolidAttenuation::Get(), and GamR::AngDist::StatTensor::GetBk().
Referenced by W().
W() [2/2]
std::vector< double > GamR::AngDist::W (std::vector< double > theta, double ji, double lambda, double lambdaPrime, double jf, double delta, StatTensor * rho, SolidAttenuation * Qk, double kmax)
Equation 2.43 from Morinaga and Yamazaki
This assumes a "nice" geometry where the detectors are in a plane parallel to the beam direction producing the alignment. It will be much faster than the equivalent function found as a member of the StatTensor class, but also much less general.
Parameters
theta Vector of angles between the detector and the beam direction (radians)
ji Initial spin
lambda Multipolarity 1 of the transition
lambdaPrime Multipolarity 2 of the transition
jf Final spin
delta Mixing ratio for multipolarities
rho Statistical tensor specifying the initial state
Qk Solid attenuation coefficients for the detector
kmax Maximum k to be calculated, default =4
Returns
A vector of W(theta) values corresponding to the input theta vector
Definition at line 176 of file AngDist.cc.
References Ak(), GamR::AngDist::SolidAttenuation::Get(), GamR::AngDist::StatTensor::GetBk(), and W().