GamR: ORNL
ORNL
Namespaces
namespace GamR::ORNL
Classes
class GamR::ORNL::BananaGate
Functions
GamR::ORNL::BananaGate::BananaGate ()
GamR::ORNL::BananaGate::BananaGate (const char *name, int n=0)
GamR::ORNL::BananaGate::BananaGate (const TCutG &cutg, TH2 &hist, int iBID, int iHID, const char *fileName)
GamR::ORNL::BananaGate::~BananaGate ()
void GamR::ORNL::BananaGate::SetFileName (const char *fileName)
void GamR::ORNL::BananaGate::SetIH (int iIH)
void GamR::ORNL::BananaGate::SetIB (int iIB)
void GamR::ORNL::BananaGate::SetDG (int iDG)
void GamR::ORNL::BananaGate::SetNP (int iNP)
void GamR::ORNL::BananaGate::SetIPX (int iIPX)
void GamR::ORNL::BananaGate::SetIPY (int iIPY)
void GamR::ORNL::BananaGate::SetLXD (int iLXD)
void GamR::ORNL::BananaGate::SetLXG (int iLXG)
void GamR::ORNL::BananaGate::SetLYD (int iLYD)
void GamR::ORNL::BananaGate::SetLYG (int iLYG)
void GamR::ORNL::BananaGate::SetNUPM (int iNUPM)
void GamR::ORNL::BananaGate::SetIAUX (int iIAUX)
void GamR::ORNL::BananaGate::SetJAUX (int iJAUX)
void GamR::ORNL::BananaGate::SetFileName (std::string fileName)
int GamR::ORNL::BananaGate::GetIH ()
int GamR::ORNL::BananaGate::GetIB ()
int GamR::ORNL::BananaGate::GetDG ()
int GamR::ORNL::BananaGate::GetNP ()
int GamR::ORNL::BananaGate::GetIPX ()
int GamR::ORNL::BananaGate::GetIPY ()
int GamR::ORNL::BananaGate::GetLXD ()
int GamR::ORNL::BananaGate::GetLXG ()
int GamR::ORNL::BananaGate::GetLYD ()
int GamR::ORNL::BananaGate::GetLYG ()
int GamR::ORNL::BananaGate::GetNUPM ()
int GamR::ORNL::BananaGate::GetIAUX ()
int GamR::ORNL::BananaGate::GetJAUX ()
TCutG GamR::ORNL::BananaGate::GetTCutG ()
std::string GamR::ORNL::BananaGate::GetFileName ()
std::string GamR::ORNL::BananaGate::WriteBan ()
BananaGate * GamR::ORNL::readBanana (const char *cBanFileName, int iID)
void GamR::ORNL::readAllBananas (const char *cBanFileName)
void GamR::ORNL::writeBananas (const char *cBanFileName, std::vector< BananaGate > vBananas)
void GamR::ORNL::writeAllBananas (const char *cBanFileName)
Detailed Description
Function Documentation
BananaGate() [1/3]
GamR::ORNL::BananaGate::BananaGate ()
#include <src/lib/ornl/OakRidge.hh>
Definition at line 27 of file OakRidge.cc.
BananaGate() [2/3]
GamR::ORNL::BananaGate::BananaGate (const char * name, int n = 0)
#include <src/lib/ornl/OakRidge.hh>
Definition at line 63 of file OakRidge.cc.
BananaGate() [3/3]
GamR::ORNL::BananaGate::BananaGate (const TCutG & cutg, TH2 & hist, int iBID, int iHID, const char * fileName)
#include <src/lib/ornl/OakRidge.hh>
Definition at line 81 of file OakRidge.cc.
~BananaGate()
GamR::ORNL::BananaGate::~BananaGate ()
#include <src/lib/ornl/OakRidge.hh>
Definition at line 45 of file OakRidge.cc.
GetDG()
int GamR::ORNL::BananaGate::GetDG () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 61 of file OakRidge.hh.
GetFileName()
std::string GamR::ORNL::BananaGate::GetFileName () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 73 of file OakRidge.hh.
GetIAUX()
int GamR::ORNL::BananaGate::GetIAUX () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 70 of file OakRidge.hh.
GetIB()
int GamR::ORNL::BananaGate::GetIB () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 60 of file OakRidge.hh.
GetIH()
int GamR::ORNL::BananaGate::GetIH () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 59 of file OakRidge.hh.
GetIPX()
int GamR::ORNL::BananaGate::GetIPX () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 63 of file OakRidge.hh.
GetIPY()
int GamR::ORNL::BananaGate::GetIPY () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 64 of file OakRidge.hh.
GetJAUX()
int GamR::ORNL::BananaGate::GetJAUX () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 71 of file OakRidge.hh.
GetLXD()
int GamR::ORNL::BananaGate::GetLXD () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 65 of file OakRidge.hh.
GetLXG()
int GamR::ORNL::BananaGate::GetLXG () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 66 of file OakRidge.hh.
GetLYD()
int GamR::ORNL::BananaGate::GetLYD () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 67 of file OakRidge.hh.
GetLYG()
int GamR::ORNL::BananaGate::GetLYG () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 68 of file OakRidge.hh.
GetNP()
int GamR::ORNL::BananaGate::GetNP () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 62 of file OakRidge.hh.
GetNUPM()
int GamR::ORNL::BananaGate::GetNUPM () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 69 of file OakRidge.hh.
GetTCutG()
TCutG GamR::ORNL::BananaGate::GetTCutG () inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 72 of file OakRidge.hh.
readAllBananas()
void GamR::ORNL::readAllBananas (const char * cBanFileName)
#include <src/lib/ornl/OakRidge.cc>
Reads all Banana Gates from a specified *.ban file and writes them to the current directory.
Parameters
cBanFileName Input *.ban file name
Definition at line 430 of file OakRidge.cc.
References readBanana(), and ss().
Referenced by main().
readBanana()
BananaGate * GamR::ORNL::readBanana (const char * cBanFileName, int iID)
#include <src/lib/ornl/OakRidge.cc>
Creates a BananaGate object from a *.ban file
Parameters
cBanFileName Name of input *.ban file
iID ID of the desired banana gate in the *.ban file
Returns
The created BananaGate object
Definition at line 293 of file OakRidge.cc.
References GamR::ORNL::BananaGate::SetDG(), GamR::ORNL::BananaGate::SetFileName(), GamR::ORNL::BananaGate::SetIAUX(), GamR::ORNL::BananaGate::SetIB(), GamR::ORNL::BananaGate::SetIH(), GamR::ORNL::BananaGate::SetIPX(), GamR::ORNL::BananaGate::SetIPY(), GamR::ORNL::BananaGate::SetJAUX(), GamR::ORNL::BananaGate::SetLXD(), GamR::ORNL::BananaGate::SetLXG(), GamR::ORNL::BananaGate::SetLYD(), GamR::ORNL::BananaGate::SetLYG(), GamR::ORNL::BananaGate::SetNP(), GamR::ORNL::BananaGate::SetNUPM(), and ss().
Referenced by readAllBananas().
SetDG()
void GamR::ORNL::BananaGate::SetDG (int iDG) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 47 of file OakRidge.hh.
Referenced by GamR::ORNL::readBanana().
SetFileName() [1/2]
void GamR::ORNL::BananaGate::SetFileName (const char * fileName)
#include <src/lib/ornl/OakRidge.hh>
Definition at line 99 of file OakRidge.cc.
Referenced by GamR::ORNL::readBanana().
SetFileName() [2/2]
void GamR::ORNL::BananaGate::SetFileName (std::string fileName) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 58 of file OakRidge.hh.
SetIAUX()
void GamR::ORNL::BananaGate::SetIAUX (int iIAUX) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 56 of file OakRidge.hh.
Referenced by GamR::ORNL::readBanana().
SetIB()
void GamR::ORNL::BananaGate::SetIB (int iIB) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 46 of file OakRidge.hh.
Referenced by GamR::ORNL::readBanana().
SetIH()
void GamR::ORNL::BananaGate::SetIH (int iIH) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 45 of file OakRidge.hh.
Referenced by GamR::ORNL::readBanana().
SetIPX()
void GamR::ORNL::BananaGate::SetIPX (int iIPX) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 49 of file OakRidge.hh.
Referenced by GamR::ORNL::readBanana().
SetIPY()
void GamR::ORNL::BananaGate::SetIPY (int iIPY) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 50 of file OakRidge.hh.
Referenced by GamR::ORNL::readBanana().
SetJAUX()
void GamR::ORNL::BananaGate::SetJAUX (int iJAUX) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 57 of file OakRidge.hh.
Referenced by GamR::ORNL::readBanana().
SetLXD()
void GamR::ORNL::BananaGate::SetLXD (int iLXD) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 51 of file OakRidge.hh.
Referenced by GamR::ORNL::readBanana().
SetLXG()
void GamR::ORNL::BananaGate::SetLXG (int iLXG) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 52 of file OakRidge.hh.
Referenced by GamR::ORNL::readBanana().
SetLYD()
void GamR::ORNL::BananaGate::SetLYD (int iLYD) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 53 of file OakRidge.hh.
Referenced by GamR::ORNL::readBanana().
SetLYG()
void GamR::ORNL::BananaGate::SetLYG (int iLYG) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 54 of file OakRidge.hh.
Referenced by GamR::ORNL::readBanana().
SetNP()
void GamR::ORNL::BananaGate::SetNP (int iNP) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 48 of file OakRidge.hh.
Referenced by GamR::ORNL::readBanana().
SetNUPM()
void GamR::ORNL::BananaGate::SetNUPM (int iNUPM) inline
#include <src/lib/ornl/OakRidge.hh>
Definition at line 55 of file OakRidge.hh.
Referenced by GamR::ORNL::readBanana().
writeAllBananas()
void GamR::ORNL::writeAllBananas (const char * cBanFileName)
#include <src/lib/ornl/OakRidge.cc>
Iterates through all BananaGate objects in current directory, puts them into a vector, and writes to a *.ban file
Parameters
cBanFileName Output *.ban file name
Definition at line 499 of file OakRidge.cc.
References writeBananas().
Referenced by main().
WriteBan()
std::string GamR::ORNL::BananaGate::WriteBan ()
#include <src/lib/ornl/OakRidge.hh>
Definition at line 104 of file OakRidge.cc.
writeBananas()
void GamR::ORNL::writeBananas (const char * cBanFileName, std::vector< BananaGate > vBananas)
#include <src/lib/ornl/OakRidge.cc>
Takes a vector of BananaGates and writes the corresponding *.ban file
Parameters
cBanFileName output *.ban file name
vBananas vector of BananaGate objects
Definition at line 462 of file OakRidge.cc.
Referenced by writeAllBananas().