GamR: GamR::Nucleus::LevelSchemeFitter::State Class Reference
GamR::Nucleus::LevelSchemeFitter::State Class Reference
#include <LevelSchemeFitter.hh>
Public Member Functions
State ()
State (std::string name, double energy, EColor color=kBlack)
~State ()
Int_t DistancetoPrimitive (Int_t px, Int_t py)
void ExecuteEvent (Int_t event, Int_t px, Int_t py)
void Paint (Option_t *option="")
bool operator< (const State &rhs) const
bool operator== (const State &rhs) const
ClassDef (State, 1)
Public Attributes
int index
Double_t fEnergy
Double_t fUncertainty
Double_t fDrawPos
Double_t fLabelPos
TText * fLabel = NULL
Detailed Description
Definition at line 13 of file LevelSchemeFitter.hh.
Constructor & Destructor Documentation
State() [1/2]
GamR::Nucleus::LevelSchemeFitter::State::State () inline
Definition at line 21 of file LevelSchemeFitter.hh.
References fDrawPos, fEnergy, fLabel, fLabelPos, and fUncertainty.
Referenced by ClassDef(), operator<(), and operator==().
State() [2/2]
GamR::Nucleus::LevelSchemeFitter::State::State (std::string name, double energy, EColor color = kBlack) inline
Definition at line 22 of file LevelSchemeFitter.hh.
References fDrawPos, fEnergy, fLabel, fLabelPos, and fUncertainty.
~State()
GamR::Nucleus::LevelSchemeFitter::State::~State () inline
Definition at line 23 of file LevelSchemeFitter.hh.
Member Function Documentation
ClassDef()
GamR::Nucleus::LevelSchemeFitter::State::ClassDef (State , 1)
References State().
DistancetoPrimitive()
Int_t GamR::Nucleus::LevelSchemeFitter::State::DistancetoPrimitive (Int_t px, Int_t py)
Definition at line 58 of file LevelSchemeFitter.cc.
References fDrawPos, fLabelPos, px(), and py().
Referenced by ExecuteEvent().
ExecuteEvent()
void GamR::Nucleus::LevelSchemeFitter::State::ExecuteEvent (Int_t event, Int_t px, Int_t py)
Definition at line 82 of file LevelSchemeFitter.cc.
References DistancetoPrimitive(), px(), and py().
operator<()
bool GamR::Nucleus::LevelSchemeFitter::State::operator< (const State & rhs) const inline
Definition at line 27 of file LevelSchemeFitter.hh.
References State(), and fEnergy.
operator==()
bool GamR::Nucleus::LevelSchemeFitter::State::operator== (const State & rhs) const inline
Definition at line 28 of file LevelSchemeFitter.hh.
References State(), and fEnergy.
Paint()
void GamR::Nucleus::LevelSchemeFitter::State::Paint (Option_t * option = "")
Definition at line 25 of file LevelSchemeFitter.cc.
References fDrawPos, fEnergy, fLabel, fLabelPos, fUncertainty, and GamR::Utils::wrresult().
Member Data Documentation
fDrawPos
Double_t GamR::Nucleus::LevelSchemeFitter::State::fDrawPos
Definition at line 18 of file LevelSchemeFitter.hh.
Referenced by State(), State(), DistancetoPrimitive(), GamR::Nucleus::LevelSchemeFitter::Scheme::Paint(), and Paint().
fEnergy
Double_t GamR::Nucleus::LevelSchemeFitter::State::fEnergy
Definition at line 16 of file LevelSchemeFitter.hh.
Referenced by State(), State(), GamR::Nucleus::LevelSchemeFitter::Scheme::Fit(), operator<(), operator==(), GamR::Nucleus::LevelSchemeFitter::Scheme::Paint(), and Paint().
fLabel
TText* GamR::Nucleus::LevelSchemeFitter::State::fLabel = NULL
Definition at line 20 of file LevelSchemeFitter.hh.
Referenced by State(), State(), and Paint().
fLabelPos
Double_t GamR::Nucleus::LevelSchemeFitter::State::fLabelPos
Definition at line 19 of file LevelSchemeFitter.hh.
Referenced by State(), State(), DistancetoPrimitive(), GamR::Nucleus::LevelSchemeFitter::Scheme::Paint(), and Paint().
fUncertainty
Double_t GamR::Nucleus::LevelSchemeFitter::State::fUncertainty
Definition at line 17 of file LevelSchemeFitter.hh.
Referenced by State(), State(), GamR::Nucleus::LevelSchemeFitter::Scheme::Fit(), and Paint().
index
int GamR::Nucleus::LevelSchemeFitter::State::index
Definition at line 15 of file LevelSchemeFitter.hh.
Referenced by GamR::Nucleus::LevelSchemeFitter::Scheme::Paint().
The documentation for this class was generated from the following files:
src/lib/nucleus/LevelSchemeFitter.hh
src/lib/nucleus/LevelSchemeFitter.cc