GamR: GamR::AngDist::SpinPrec Class Reference
GamR::AngDist::SpinPrec Class Reference
#include <TDPAD.hh>
Public Member Functions
SpinPrec (double g, double a, double thet, double b, double ts, bool td)
double GetOmega ()
double SetTheta (double ang)
double SetG (double g)
double SetB (double b)
double SetAmp (double a)
double SetTStart (double ts)
bool SetTDir (bool dir)
double GetG ()
double GetAmp ()
double GetB ()
double GetTheta ()
double GetTStart ()
bool GetTDir ()
TF1 * GetFunc ()
Detailed Description
Spin precession class. Wrapper for an R(t) TF1, but taking relevant parameters such as g factor, magnetic field strength, and detector angle.
The SpinPrec class. Construct with
GamR::AngDist::SpinPrec prec(gfac, amp, theta, B, timestart, timedir);
and get the relevant TF1 (to fit) with
prec.GetFunc();
Only the g factor and amplitude will be free parameters in the fit. Use setting functions to change the parameters and/or starting guesses. Note that GetFunc() returns a clone of the TF1 stored in the class - this way the parameters can only be editted through the appropriate setters.
Definition at line 33 of file TDPAD.hh.
Constructor & Destructor Documentation
SpinPrec()
GamR::AngDist::SpinPrec::SpinPrec (double g, double a, double thet, double b, double ts, bool td)
Constructor for SpinPrec object.
Parameters
g g factor
a amplitude of R(t)
thet angle of detector (in degrees)
b magnetic field strenth in Tesla
ts value of x-axis at the start time
td direction of positive time (kTRUE for forwards, kFALSE for backwards)
Definition at line 243 of file TDPAD.cc.
References SetAmp(), SetB(), SetG(), SetTDir(), SetTheta(), and SetTStart().
Member Function Documentation
GetAmp()
double GamR::AngDist::SpinPrec::GetAmp () inline
Definition at line 89 of file TDPAD.hh.
GetB()
double GamR::AngDist::SpinPrec::GetB () inline
Definition at line 90 of file TDPAD.hh.
GetFunc()
TF1 * GamR::AngDist::SpinPrec::GetFunc ()
Definition at line 257 of file TDPAD.cc.
GetG()
double GamR::AngDist::SpinPrec::GetG () inline
Definition at line 88 of file TDPAD.hh.
GetOmega()
double GamR::AngDist::SpinPrec::GetOmega () inline
Definition at line 47 of file TDPAD.hh.
GetTDir()
bool GamR::AngDist::SpinPrec::GetTDir () inline
Definition at line 93 of file TDPAD.hh.
GetTheta()
double GamR::AngDist::SpinPrec::GetTheta () inline
Definition at line 91 of file TDPAD.hh.
GetTStart()
double GamR::AngDist::SpinPrec::GetTStart () inline
Definition at line 92 of file TDPAD.hh.
SetAmp()
double GamR::AngDist::SpinPrec::SetAmp (double a) inline
Definition at line 66 of file TDPAD.hh.
Referenced by SpinPrec().
SetB()
double GamR::AngDist::SpinPrec::SetB (double b) inline
Definition at line 60 of file TDPAD.hh.
Referenced by SpinPrec().
SetG()
double GamR::AngDist::SpinPrec::SetG (double g) inline
Definition at line 54 of file TDPAD.hh.
Referenced by SpinPrec().
SetTDir()
bool GamR::AngDist::SpinPrec::SetTDir (bool dir) inline
Definition at line 78 of file TDPAD.hh.
Referenced by SpinPrec().
SetTheta()
double GamR::AngDist::SpinPrec::SetTheta (double ang) inline
Definition at line 48 of file TDPAD.hh.
Referenced by SpinPrec().
SetTStart()
double GamR::AngDist::SpinPrec::SetTStart (double ts) inline
Definition at line 72 of file TDPAD.hh.
Referenced by SpinPrec().
The documentation for this class was generated from the following files:
src/lib/angdist/TDPAD.hh
src/lib/angdist/TDPAD.cc