GamR: GamR::Coulex::CoulexCalculation Class Reference
GamR::Coulex::CoulexCalculation Class Reference
#include <CoulexCalculation.hh>
Public Member Functions
void SetBeam (int Z, float A, float energy)
void SetBeam (std::string isotope, float energy)
void SetTarget (int Z, float A, float density, float thickness)
void SetTarget (std::string isotope, float density, float thickness)
void SetDetected (Species detected)
void SetExcited (Species excited)
void SetParticleDet (float width, float height, float z, float r)
void SetInterests (int loi, int toi)
int ReadFromFile (std::string file_name="Wtheta.ans")
void SaveToFile (std::string file_name="Wtheta.ans")
void SetBeam ()
void SetTarget ()
void SetDetected ()
void SetExcited ()
void SetLevelScheme ()
void SetInterests ()
void SetParticleDet ()
void ExperimentalSetup ()
void Print ()
GamR::AngDist::StatTensor * CalcTensor ()
Public Attributes
Nucleus fBeam
Target fTarget
Species fDetected = Species::kNone
Species fExcited = Species::kNone
float fBeamEnergy
LevelScheme fLevelScheme
ParticleDetector fParticleDetector
int fLevelOfInterest
int fTransitionOfInterest
Detailed Description
Definition at line 154 of file CoulexCalculation.hh.
Member Function Documentation
CalcTensor()
GamR::AngDist::StatTensor * GamR::Coulex::CoulexCalculation::CalcTensor ()
Calculates the statistical tensor for the state of interest following Coulex Excitation
Returns
statistical tensor of state of interest
Definition at line 939 of file CoulexCalculation.cc.
References GamR::Coulex::Nucleus::A, GamR::Coulex::Target::density, GamR::Coulex::Eldat, GamR::Coulex::ELoss(), fBeam, fBeamEnergy, fDetected, fExcited, GamR::Coulex::ParticleDetector::fHeight, fLevelOfInterest, GamR::Coulex::LevelScheme::fLevels, fLevelScheme, fParticleDetector, fTarget, GamR::Coulex::ParticleDetector::fWidth, GamR::Coulex::LevelScheme::GetETransitions(), GamR::Coulex::LevelScheme::GetLevels(), GamR::Coulex::LevelScheme::GetMTransitions(), GamR::Coulex::Target::isotope, GamR::Coulex::kProjectile, GamR::Coulex::kTarget, GamR::Coulex::loadSCOEF(), GamR::Coulex::SCOEFloaded, GamR::AngDist::StatTensor::Set(), GamR::Coulex::setupcoulex(), GamR::Utils::Simps(), GamR::Coulex::Target::thickness, and GamR::Coulex::Nucleus::Z.
Referenced by GamR::Coulex::DoCoulex().
ExperimentalSetup()
void GamR::Coulex::CoulexCalculation::ExperimentalSetup ()
Set all information through interactive CLI interface. Defaults are existing data
Definition at line 890 of file CoulexCalculation.cc.
References SetBeam(), SetDetected(), SetExcited(), SetInterests(), SetLevelScheme(), SetParticleDet(), and SetTarget().
Referenced by GamR::Coulex::DoCoulex(), and GamR::Coulex::ExperimentalSetup().
Print()
void GamR::Coulex::CoulexCalculation::Print ()
Print experiment summary
Definition at line 903 of file CoulexCalculation.cc.
References GamR::Coulex::Nucleus::A, ANSI_COLOR_BLUE, ANSI_COLOR_RESET, GamR::Coulex::Target::density, fBeam, fBeamEnergy, fDetected, fExcited, fLevelOfInterest, fLevelScheme, fParticleDetector, fTarget, fTransitionOfInterest, GamR::TK::GetElement(), GamR::Coulex::Target::isotope, GamR::Coulex::kTarget, GamR::Coulex::ParticleDetector::Print(), GamR::Coulex::LevelScheme::Print(), GamR::Coulex::Target::thickness, and GamR::Coulex::Nucleus::Z.
Referenced by GamR::Coulex::DoCoulex(), and GamR::Coulex::ExperimentalSetup().
ReadFromFile()
int GamR::Coulex::CoulexCalculation::ReadFromFile (std::string file_name = "Wtheta.ans")
Read experimental information from a text "*.ans" file
Parameters
file_name File to read
Returns
<0 means an error, 0 is success
Definition at line 570 of file CoulexCalculation.cc.
References GamR::Coulex::Nucleus::A, GamR::Coulex::LevelScheme::AddLevel(), GamR::Coulex::LevelScheme::AddTransition(), GamR::Utils::catcherr(), GamR::Coulex::Target::density, GamR::Coulex::Eldat, fBeam, fBeamEnergy, fDetected, GamR::Coulex::ParticleDetector::fDistanceR, GamR::Coulex::ParticleDetector::fDistanceZ, fExcited, GamR::Coulex::ParticleDetector::fHeight, fLevelOfInterest, fLevelScheme, fParticleDetector, fTarget, fTransitionOfInterest, GamR::Coulex::LevelScheme::fTransitions, GamR::Coulex::ParticleDetector::fWidth, GamR::Utils::getline(), GamR::TK::GetZA(), GamR::Coulex::Target::isotope, GamR::Coulex::kProjectile, GamR::Coulex::kTarget, GamR::Coulex::loadSCOEF(), GamR::Coulex::SCOEFloaded, GamR::Coulex::LevelScheme::SetIndices(), GamR::Coulex::Target::thickness, and GamR::Coulex::Nucleus::Z.
Referenced by GamR::Coulex::DoCoulex(), and GamR::Coulex::ExperimentalSetup().
SaveToFile()
void GamR::Coulex::CoulexCalculation::SaveToFile (std::string file_name = "Wtheta.ans")
Save experimental details to a "*.ans" text file
Parameters
file_name File name to save to. Existing file will be overwritten
Definition at line 849 of file CoulexCalculation.cc.
References GamR::Coulex::Nucleus::A, GamR::Coulex::Target::density, fBeam, fBeamEnergy, fDetected, GamR::Coulex::ParticleDetector::fDistanceR, GamR::Coulex::ParticleDetector::fDistanceZ, GamR::Coulex::Level::fEnergy, fExcited, GamR::Coulex::Transition::fFinal, GamR::Coulex::ParticleDetector::fHeight, GamR::Coulex::Level::fIndex, GamR::Coulex::Transition::fInitial, fLevelOfInterest, fLevelScheme, GamR::Coulex::Transition::fMult, fParticleDetector, fTarget, fTransitionOfInterest, GamR::Coulex::LevelScheme::fTransitions, GamR::Coulex::ParticleDetector::fWidth, GamR::Coulex::Transition::GetBUp(), GamR::TK::GetElement(), GamR::Coulex::LevelScheme::GetLevelByIndex(), GamR::Coulex::LevelScheme::GetNLevels(), GamR::Coulex::LevelScheme::GetNTransitions(), GamR::Coulex::Target::isotope, GamR::Coulex::kTarget, GamR::Coulex::Level::PrintSP(), GamR::Coulex::LevelScheme::SetIndices(), GamR::Coulex::Target::thickness, and GamR::Coulex::Nucleus::Z.
Referenced by GamR::Coulex::DoCoulex(), and GamR::Coulex::ExperimentalSetup().
SetBeam() [1/3]
void GamR::Coulex::CoulexCalculation::SetBeam ()
Set the beam details through an interactive CLI
Definition at line 308 of file CoulexCalculation.cc.
References GamR::Coulex::Nucleus::A, GamR::Coulex::Eldat, fBeam, fBeamEnergy, GamR::TK::GetElement(), GamR::Utils::GetInput(), GamR::Utils::getline(), GamR::TK::GetZA(), GamR::Coulex::loadSCOEF(), GamR::Coulex::SCOEFloaded, and GamR::Coulex::Nucleus::Z.
Referenced by ExperimentalSetup().
SetBeam() [2/3]
void GamR::Coulex::CoulexCalculation::SetBeam (int Z, float A, float energy) inline
Definition at line 166 of file CoulexCalculation.hh.
References GamR::Coulex::Nucleus::A, fBeam, fBeamEnergy, and GamR::Coulex::Nucleus::Z.
SetBeam() [3/3]
void GamR::Coulex::CoulexCalculation::SetBeam (std::string isotope, float energy) inline
Definition at line 167 of file CoulexCalculation.hh.
References GamR::TK::GetZA(), and SetBeam().
Referenced by SetBeam().
SetDetected() [1/2]
void GamR::Coulex::CoulexCalculation::SetDetected ()
Set the details about which species is detected through an interactive CLI interface
Definition at line 375 of file CoulexCalculation.cc.
References fDetected, GamR::Utils::getline(), GamR::Coulex::kProjectile, and GamR::Coulex::kTarget.
Referenced by ExperimentalSetup().
SetDetected() [2/2]
void GamR::Coulex::CoulexCalculation::SetDetected (Species detected) inline
Definition at line 171 of file CoulexCalculation.hh.
References fDetected.
SetExcited() [1/2]
void GamR::Coulex::CoulexCalculation::SetExcited ()
Set the details about which species is excited through an interactive CLI interface
Definition at line 399 of file CoulexCalculation.cc.
References fExcited, GamR::Utils::getline(), GamR::Coulex::kProjectile, and GamR::Coulex::kTarget.
Referenced by ExperimentalSetup().
SetExcited() [2/2]
void GamR::Coulex::CoulexCalculation::SetExcited (Species excited) inline
Definition at line 172 of file CoulexCalculation.hh.
References fExcited.
SetInterests() [1/2]
void GamR::Coulex::CoulexCalculation::SetInterests ()
Set level and transition of interest through an interactive CLI interface
Definition at line 533 of file CoulexCalculation.cc.
References fLevelOfInterest, fTransitionOfInterest, and GamR::Utils::GetInput().
Referenced by ExperimentalSetup().
SetInterests() [2/2]
void GamR::Coulex::CoulexCalculation::SetInterests (int loi, int toi) inline
Definition at line 175 of file CoulexCalculation.hh.
References fLevelOfInterest, and fTransitionOfInterest.
SetLevelScheme()
void GamR::Coulex::CoulexCalculation::SetLevelScheme ()
Set the level scheme through an interactive CLI interface
Definition at line 423 of file CoulexCalculation.cc.
References GamR::Coulex::LevelScheme::AddLevel(), GamR::Coulex::LevelScheme::AddTransition(), GamR::Coulex::Level::fEnergy, GamR::Coulex::Transition::fFinal, GamR::Coulex::Level::fIndex, GamR::Coulex::Transition::fInitial, fLevelScheme, GamR::Coulex::Transition::fMult, GamR::Coulex::Level::fName, GamR::Coulex::Level::fParity, GamR::Coulex::Level::fSpin, GamR::Coulex::LevelScheme::fTransitions, GamR::Coulex::Transition::GetBUp(), GamR::Utils::GetInput(), GamR::Coulex::LevelScheme::GetLevelByIndex(), GamR::Utils::getline(), GamR::Coulex::LevelScheme::GetNLevels(), GamR::Coulex::LevelScheme::GetNTransitions(), GamR::Coulex::LevelScheme::PrintLevels(), GamR::Coulex::Transition::SetBUp(), and sp().
Referenced by ExperimentalSetup().
SetParticleDet() [1/2]
void GamR::Coulex::CoulexCalculation::SetParticleDet ()
Definition at line 545 of file CoulexCalculation.cc.
References GamR::Coulex::DrawSetup(), GamR::Coulex::ParticleDetector::fDistanceR, GamR::Coulex::ParticleDetector::fDistanceZ, GamR::Coulex::ParticleDetector::fHeight, fParticleDetector, GamR::Coulex::ParticleDetector::fWidth, and GamR::Utils::GetInput().
Referenced by ExperimentalSetup().
SetParticleDet() [2/2]
void GamR::Coulex::CoulexCalculation::SetParticleDet (float width, float height, float z, float r) inline
Definition at line 173 of file CoulexCalculation.hh.
References GamR::Coulex::ParticleDetector::fDistanceR, GamR::Coulex::ParticleDetector::fDistanceZ, GamR::Coulex::ParticleDetector::fHeight, fParticleDetector, and GamR::Coulex::ParticleDetector::fWidth.
SetTarget() [1/3]
void GamR::Coulex::CoulexCalculation::SetTarget ()
Set the target details through an interactive CLI
Definition at line 340 of file CoulexCalculation.cc.
References GamR::Coulex::Nucleus::A, GamR::Coulex::Target::density, GamR::Coulex::Eldat, fTarget, GamR::TK::GetElement(), GamR::Utils::GetInput(), GamR::Utils::getline(), GamR::TK::GetZA(), GamR::Coulex::Target::isotope, GamR::Coulex::loadSCOEF(), GamR::Coulex::SCOEFloaded, GamR::Coulex::Target::thickness, and GamR::Coulex::Nucleus::Z.
Referenced by ExperimentalSetup().
SetTarget() [2/3]
void GamR::Coulex::CoulexCalculation::SetTarget (int Z, float A, float density, float thickness) inline
Definition at line 169 of file CoulexCalculation.hh.
References GamR::Coulex::Nucleus::A, GamR::Coulex::Target::density, fTarget, GamR::Coulex::Target::isotope, GamR::Coulex::Target::thickness, and GamR::Coulex::Nucleus::Z.
SetTarget() [3/3]
void GamR::Coulex::CoulexCalculation::SetTarget (std::string isotope, float density, float thickness) inline
Definition at line 170 of file CoulexCalculation.hh.
References GamR::TK::GetZA(), and SetTarget().
Referenced by SetTarget().
Member Data Documentation
fBeam
Nucleus GamR::Coulex::CoulexCalculation::fBeam
Definition at line 156 of file CoulexCalculation.hh.
Referenced by CalcTensor(), Print(), ReadFromFile(), SaveToFile(), and SetBeam().
fBeamEnergy
float GamR::Coulex::CoulexCalculation::fBeamEnergy
Definition at line 160 of file CoulexCalculation.hh.
Referenced by CalcTensor(), Print(), ReadFromFile(), SaveToFile(), and SetBeam().
fDetected
Species GamR::Coulex::CoulexCalculation::fDetected = Species::kNone
Definition at line 158 of file CoulexCalculation.hh.
Referenced by CalcTensor(), Print(), ReadFromFile(), SaveToFile(), and SetDetected().
fExcited
Species GamR::Coulex::CoulexCalculation::fExcited = Species::kNone
Definition at line 159 of file CoulexCalculation.hh.
Referenced by CalcTensor(), Print(), ReadFromFile(), SaveToFile(), and SetExcited().
fLevelOfInterest
int GamR::Coulex::CoulexCalculation::fLevelOfInterest
Definition at line 163 of file CoulexCalculation.hh.
Referenced by CalcTensor(), Print(), ReadFromFile(), SaveToFile(), and SetInterests().
fLevelScheme
LevelScheme GamR::Coulex::CoulexCalculation::fLevelScheme
Definition at line 161 of file CoulexCalculation.hh.
Referenced by CalcTensor(), Print(), ReadFromFile(), SaveToFile(), and SetLevelScheme().
fParticleDetector
ParticleDetector GamR::Coulex::CoulexCalculation::fParticleDetector
Definition at line 162 of file CoulexCalculation.hh.
Referenced by CalcTensor(), Print(), ReadFromFile(), SaveToFile(), and SetParticleDet().
fTarget
Target GamR::Coulex::CoulexCalculation::fTarget
Definition at line 157 of file CoulexCalculation.hh.
Referenced by CalcTensor(), Print(), ReadFromFile(), SaveToFile(), and SetTarget().
fTransitionOfInterest
int GamR::Coulex::CoulexCalculation::fTransitionOfInterest
Definition at line 164 of file CoulexCalculation.hh.
Referenced by Print(), ReadFromFile(), SaveToFile(), and SetInterests().
The documentation for this class was generated from the following files:
src/lib/coulex/CoulexCalculation.hh
src/lib/coulex/CoulexCalculation.cc