GamR: GamR::AngDist::AngCorrFit Class Reference
GamR::AngDist::AngCorrFit Class Reference
#include <AngCorr.hh>
Public Member Functions
void SetData (std::vector< double > angs, std::vector< TH2D * > hists, GamR::Nucleus::Transition peak1, GamR::Nucleus::Transition peak2, TH1D *angNorm)
void SetSpins (std::vector< double > s1s, std::vector< double > s2s, std::vector< double > s3s)
void SetQk (GamR::AngDist::SolidAttenuation *Q)
AngCorrFit (std::vector< double > angs, std::vector< TH2D * > hists, GamR::Nucleus::Transition peak1, GamR::Nucleus::Transition peak2, TH1D *angNorm, const char *name, const char *title)
AngCorrFit (std::vector< double > angs, std::vector< TH2D * > hists, GamR::Nucleus::Transition peak1, GamR::Nucleus::Transition peak2, TH1D *angNorm)
void FixDel1 (double delta)
void FixDel2 (double delta)
int GetNPoints ()
int GetNCombs ()
void ErasePoint (double ang)
double Average ()
TGraphErrors * GetGraph ()
TGraphErrors * GetDispGraph (double start, double interval)
void Fit ()
TMultiGraph * GetChiGraph ()
void DrawChiGraph (TCanvas *c1, double ylow, double yhigh)
void DrawAngCorr (TCanvas *c1, double start, double interval)
void PrintDelta1 (int i)
void PrintDelta2 (int i)
void Save (std::string filename, double start, double interval)
void SaveChiGraph (std::string filename)
ClassDef (AngCorrFit, 1)
Public Attributes
std::vector< Color_t > fColors
std::vector< double > spin1s
std::vector< double > spin2s
std::vector< double > spin3s
std::vector< double > fAngles
std::vector< double > fIntensities
std::vector< double > fErrors
std::vector< AngCorr * > fCorrs
std::vector< TF1 * > fCorrFuncs
std::vector< TGraph * > fChiGraphs
std::vector< double > fDelta1
std::vector< double > fDelta2
std::vector< std::pair< double, double > > fDelta1Err
std::vector< std::pair< double, double > > fDelta2Err
std::vector< double > fChiSquared
std::vector< double > fixDelta
std::vector< int > fDel
GamR::AngDist::SolidAttenuation * Qk
Detailed Description
Definition at line 76 of file AngCorr.hh.
Constructor & Destructor Documentation
AngCorrFit() [1/2]
GamR::AngDist::AngCorrFit::AngCorrFit (std::vector< double > angs, std::vector< TH2D * > hists, GamR::Nucleus::Transition peak1, GamR::Nucleus::Transition peak2, TH1D * angNorm, const char * name, const char * title)
Definition at line 122 of file AngCorr.cc.
References Qk, and SetData().
AngCorrFit() [2/2]
GamR::AngDist::AngCorrFit::AngCorrFit (std::vector< double > angs, std::vector< TH2D * > hists, GamR::Nucleus::Transition peak1, GamR::Nucleus::Transition peak2, TH1D * angNorm)
Definition at line 115 of file AngCorr.cc.
References Qk, and SetData().
Member Function Documentation
Average()
double GamR::AngDist::AngCorrFit::Average ()
Definition at line 140 of file AngCorr.cc.
References fIntensities, and GetNPoints().
Referenced by Fit().
ClassDef()
GamR::AngDist::AngCorrFit::ClassDef (AngCorrFit , 1)
DrawAngCorr()
void GamR::AngDist::AngCorrFit::DrawAngCorr (TCanvas * c1, double start, double interval)
Definition at line 398 of file AngCorr.cc.
References fCorrFuncs, fCorrs, GetDispGraph(), and GetNCombs().
DrawChiGraph()
void GamR::AngDist::AngCorrFit::DrawChiGraph (TCanvas * c1, double ylow, double yhigh)
Definition at line 370 of file AngCorr.cc.
References fChiGraphs, fCorrs, GetChiGraph(), and GetNCombs().
ErasePoint()
void GamR::AngDist::AngCorrFit::ErasePoint (double ang)
Definition at line 129 of file AngCorr.cc.
References fAngles, fErrors, fIntensities, and GetNPoints().
Fit()
void GamR::AngDist::AngCorrFit::Fit ()
Definition at line 207 of file AngCorr.cc.
References Average(), fChiGraphs, fChiSquared, fColors, fCorrFuncs, fCorrs, fDel, fDelta1, fDelta1Err, fDelta2, fDelta2Err, fixDelta, GetGraph(), ig(), GamR::AngDist::AngCorr::Mixed(), GamR::AngDist::AngCorr::Mixed1(), GamR::AngDist::AngCorr::Mixed2(), Qk, spin1s, spin2s, and spin3s.
FixDel1()
void GamR::AngDist::AngCorrFit::FixDel1 (double delta) inline
Definition at line 114 of file AngCorr.hh.
References fDel, and fixDelta.
FixDel2()
void GamR::AngDist::AngCorrFit::FixDel2 (double delta) inline
Definition at line 115 of file AngCorr.hh.
References fDel, and fixDelta.
GetChiGraph()
TMultiGraph * GamR::AngDist::AngCorrFit::GetChiGraph ()
Definition at line 360 of file AngCorr.cc.
References fChiGraphs, and GetNCombs().
Referenced by DrawChiGraph().
GetDispGraph()
TGraphErrors * GamR::AngDist::AngCorrFit::GetDispGraph (double start, double interval)
Definition at line 160 of file AngCorr.cc.
References fAngles, fErrors, fIntensities, and GetNPoints().
Referenced by DrawAngCorr(), and Save().
GetGraph()
TGraphErrors * GamR::AngDist::AngCorrFit::GetGraph ()
Definition at line 149 of file AngCorr.cc.
References fAngles, fErrors, fIntensities, and GetNPoints().
Referenced by Fit().
GetNCombs()
int GamR::AngDist::AngCorrFit::GetNCombs () inline
Definition at line 118 of file AngCorr.hh.
References fCorrs.
Referenced by DrawAngCorr(), DrawChiGraph(), GetChiGraph(), and Save().
GetNPoints()
int GamR::AngDist::AngCorrFit::GetNPoints () inline
Definition at line 117 of file AngCorr.hh.
References fAngles.
Referenced by Average(), ErasePoint(), GetDispGraph(), and GetGraph().
PrintDelta1()
void GamR::AngDist::AngCorrFit::PrintDelta1 (int i) inline
Definition at line 129 of file AngCorr.hh.
References fDelta1, and fDelta1Err.
PrintDelta2()
void GamR::AngDist::AngCorrFit::PrintDelta2 (int i) inline
Definition at line 130 of file AngCorr.hh.
References fDelta2, and fDelta2Err.
Save()
void GamR::AngDist::AngCorrFit::Save (std::string filename, double start, double interval)
Definition at line 414 of file AngCorr.cc.
References fCorrFuncs, GetDispGraph(), and GetNCombs().
SaveChiGraph()
void GamR::AngDist::AngCorrFit::SaveChiGraph (std::string filename)
Definition at line 435 of file AngCorr.cc.
References fChiGraphs.
SetData()
void GamR::AngDist::AngCorrFit::SetData (std::vector< double > angs, std::vector< TH2D * > hists, GamR::Nucleus::Transition peak1, GamR::Nucleus::Transition peak2, TH1D * angNorm)
Definition at line 96 of file AngCorr.cc.
References GamR::Nucleus::Transition::Apply(), GamR::Nucleus::Transition::ApplyError(), GamR::Spect::BackgroundSubtractY(), fAngles, fColors, fDel, fErrors, fIntensities, and fixDelta.
Referenced by AngCorrFit().
SetQk()
void GamR::AngDist::AngCorrFit::SetQk (GamR::AngDist::SolidAttenuation * Q) inline
Definition at line 109 of file AngCorr.hh.
References Qk.
SetSpins()
void GamR::AngDist::AngCorrFit::SetSpins (std::vector< double > s1s, std::vector< double > s2s, std::vector< double > s3s) inline
Definition at line 108 of file AngCorr.hh.
References spin1s, spin2s, and spin3s.
Member Data Documentation
fAngles
std::vector<double> GamR::AngDist::AngCorrFit::fAngles
Definition at line 87 of file AngCorr.hh.
Referenced by ErasePoint(), GetDispGraph(), GetGraph(), GetNPoints(), and SetData().
fChiGraphs
std::vector<TGraph*> GamR::AngDist::AngCorrFit::fChiGraphs
Definition at line 93 of file AngCorr.hh.
Referenced by DrawChiGraph(), Fit(), GetChiGraph(), and SaveChiGraph().
fChiSquared
std::vector<double> GamR::AngDist::AngCorrFit::fChiSquared
Definition at line 99 of file AngCorr.hh.
Referenced by Fit().
fColors
std::vector<Color_t> GamR::AngDist::AngCorrFit::fColors
A wrapper for the AngCorr class to contain TGraphErrors to fit to as well
Definition at line 81 of file AngCorr.hh.
Referenced by Fit(), and SetData().
fCorrFuncs
std::vector<TF1*> GamR::AngDist::AngCorrFit::fCorrFuncs
Definition at line 92 of file AngCorr.hh.
Referenced by DrawAngCorr(), Fit(), and Save().
fCorrs
std::vector<AngCorr*> GamR::AngDist::AngCorrFit::fCorrs
Definition at line 91 of file AngCorr.hh.
Referenced by DrawAngCorr(), DrawChiGraph(), Fit(), and GetNCombs().
fDel
std::vector<int> GamR::AngDist::AngCorrFit::fDel
Definition at line 102 of file AngCorr.hh.
Referenced by Fit(), FixDel1(), FixDel2(), and SetData().
fDelta1
std::vector<double> GamR::AngDist::AngCorrFit::fDelta1
Definition at line 95 of file AngCorr.hh.
Referenced by Fit(), and PrintDelta1().
fDelta1Err
std::vector<std::pair<double,double> > GamR::AngDist::AngCorrFit::fDelta1Err
Definition at line 97 of file AngCorr.hh.
Referenced by Fit(), and PrintDelta1().
fDelta2
std::vector<double> GamR::AngDist::AngCorrFit::fDelta2
Definition at line 96 of file AngCorr.hh.
Referenced by Fit(), and PrintDelta2().
fDelta2Err
std::vector<std::pair<double,double> > GamR::AngDist::AngCorrFit::fDelta2Err
Definition at line 98 of file AngCorr.hh.
Referenced by Fit(), and PrintDelta2().
fErrors
std::vector<double> GamR::AngDist::AngCorrFit::fErrors
Definition at line 89 of file AngCorr.hh.
Referenced by ErasePoint(), GetDispGraph(), GetGraph(), and SetData().
fIntensities
std::vector<double> GamR::AngDist::AngCorrFit::fIntensities
Definition at line 88 of file AngCorr.hh.
Referenced by Average(), ErasePoint(), GetDispGraph(), GetGraph(), and SetData().
fixDelta
std::vector<double> GamR::AngDist::AngCorrFit::fixDelta
Definition at line 101 of file AngCorr.hh.
Referenced by Fit(), FixDel1(), FixDel2(), and SetData().
Qk
GamR::AngDist::SolidAttenuation* GamR::AngDist::AngCorrFit::Qk
Definition at line 104 of file AngCorr.hh.
Referenced by AngCorrFit(), Fit(), and SetQk().
spin1s
std::vector<double> GamR::AngDist::AngCorrFit::spin1s
Definition at line 83 of file AngCorr.hh.
Referenced by Fit(), and SetSpins().
spin2s
std::vector<double> GamR::AngDist::AngCorrFit::spin2s
Definition at line 84 of file AngCorr.hh.
Referenced by Fit(), and SetSpins().
spin3s
std::vector<double> GamR::AngDist::AngCorrFit::spin3s
Definition at line 85 of file AngCorr.hh.
Referenced by Fit(), and SetSpins().
The documentation for this class was generated from the following files:
src/lib/angdist/AngCorr.hh
src/lib/angdist/AngCorr.cc