GamR: GamR::Processor::TimeWalk Class Reference
GamR::Processor::TimeWalk Class Reference
#include <TimeWalk.hh>
Classes
class GlobalChiSquare
Public Member Functions
TimeWalk (std::vector< Int_t > ids)
TimeWalk Calibration Processor.
~TimeWalk ()
Int_t AddPeak (std::string dataset, GamR::Nucleus::Photon photon, Double_t time)
Add a calibration peak to be used to create a data point in the time walk curve.
void MakeGraphs (Int_t ntoys, Bool_t showmc=kTRUE)
Iterating through calibration peaks for each detector pair: calculate the time difference spectrum (with full background subtraction), monte-carlo the first order moment, correct for any early/delay shifts due to lifetimes, to create one data point on the graph.
void Draw (TCanvas *c, Bool_t fits=kFALSE, std::string saveas="")
Draws Time Walk graphs.
void Fit ()
Conducts a global \(\Chi^2 \) fit to solve for an absolute time calibration for each detector.
Detailed Description
Definition at line 21 of file TimeWalk.hh.
Constructor & Destructor Documentation
TimeWalk()
GamR::Processor::TimeWalk::TimeWalk (std::vector< Int_t > ids)
TimeWalk Calibration Processor.
Parameters
[in] ids Detector IDs.
Returns
TimeWalk
Definition at line 26 of file TimeWalk.cc.
Referenced by GamR::Processor::TimeWalk::GlobalChiSquare::GlobalChiSquare().
~TimeWalk()
GamR::Processor::TimeWalk::~TimeWalk ()
Definition at line 47 of file TimeWalk.cc.
Member Function Documentation
AddPeak()
Int_t GamR::Processor::TimeWalk::AddPeak (std::string dataset, GamR::Nucleus::Photon photon, Double_t time)
Add a calibration peak to be used to create a data point in the time walk curve.
Parameters
[in] dataset Filename of Data Set, expects output from GamR::Sort::Type::TimeWalkCal
[in] photon Calibration peak to measure time relative to reference photon.
[in] time Early/Delay time correction of this peak. Positive corrects for delayed transitions, negative for early.
Returns
int Error code: 0 successful, 1 error opening file, 2 can't find reference photon in data set.
Definition at line 188 of file TimeWalk.cc.
Draw()
void GamR::Processor::TimeWalk::Draw (TCanvas * c, Bool_t fits = kFALSE, std::string saveas = "")
Draws Time Walk graphs.
Parameters
[in] c Canvas to draw on.
[in] fits Draw fits behind graphs
[in] saveas (optional) save to file
Definition at line 83 of file TimeWalk.cc.
References ss().
Referenced by Fit(), and MakeGraphs().
Fit()
void GamR::Processor::TimeWalk::Fit ()
Conducts a global \(\Chi^2 \) fit to solve for an absolute time calibration for each detector.
Definition at line 389 of file TimeWalk.cc.
References Draw(), GamR::Processor::TimeWalk::GlobalChiSquare::minuit(), and ss().
MakeGraphs()
void GamR::Processor::TimeWalk::MakeGraphs (Int_t ntoys, Bool_t showmc = kTRUE)
Iterating through calibration peaks for each detector pair: calculate the time difference spectrum (with full background subtraction), monte-carlo the first order moment, correct for any early/delay shifts due to lifetimes, to create one data point on the graph.
Parameters
ntoys Number of toy experiments to conduct during the Monte-Carlo simulation.
showmc Shows visualisation of Monte Carlo simulation
Definition at line 211 of file TimeWalk.cc.
References bp(), Draw(), GamR::TK::MonteCarlo(), and ss().
The documentation for this class was generated from the following files:
src/lib/processor/TimeWalk.hh
src/lib/processor/TimeWalk.cc