GamR: GamR::Nucleus::LevelSchemeFitter::Transition Class Reference
GamR::Nucleus::LevelSchemeFitter::Transition Class Reference
#include <LevelSchemeFitter.hh>
Public Member Functions
Transition ()
Transition (State *initial, State *final, double energy, double uncertainty, EColor color)
~Transition ()
void Paint (Option_t *option="")
Int_t DistancetoPrimitive (Int_t px, Int_t py)
void ExecuteEvent (Int_t event, Int_t px, Int_t py)
void Draw (Option_t *option="")
bool operator< (const Transition &rhs) const
ClassDef (Transition, 1)
Public Attributes
State * fInitial
State * fFinal
Double_t fEnergy
Double_t fUncertainty
TText * fLabel = NULL
Detailed Description
Definition at line 31 of file LevelSchemeFitter.hh.
Constructor & Destructor Documentation
Transition() [1/2]
GamR::Nucleus::LevelSchemeFitter::Transition::Transition () inline
Definition at line 39 of file LevelSchemeFitter.hh.
References fLabel.
Transition() [2/2]
GamR::Nucleus::LevelSchemeFitter::Transition::Transition (State * initial, State * final, double energy, double uncertainty, EColor color) inline
Definition at line 40 of file LevelSchemeFitter.hh.
References fLabel.
~Transition()
GamR::Nucleus::LevelSchemeFitter::Transition::~Transition () inline
Definition at line 46 of file LevelSchemeFitter.hh.
Member Function Documentation
ClassDef()
GamR::Nucleus::LevelSchemeFitter::Transition::ClassDef (Transition , 1)
DistancetoPrimitive()
Int_t GamR::Nucleus::LevelSchemeFitter::Transition::DistancetoPrimitive (Int_t px, Int_t py)
Definition at line 118 of file LevelSchemeFitter.cc.
References px(), and py().
Referenced by ExecuteEvent().
Draw()
void GamR::Nucleus::LevelSchemeFitter::Transition::Draw (Option_t * option = "") inline
Definition at line 50 of file LevelSchemeFitter.hh.
ExecuteEvent()
void GamR::Nucleus::LevelSchemeFitter::Transition::ExecuteEvent (Int_t event, Int_t px, Int_t py)
Definition at line 141 of file LevelSchemeFitter.cc.
References DistancetoPrimitive(), px(), and py().
operator<()
bool GamR::Nucleus::LevelSchemeFitter::Transition::operator< (const Transition & rhs) const inline
Definition at line 52 of file LevelSchemeFitter.hh.
References fEnergy.
Paint()
void GamR::Nucleus::LevelSchemeFitter::Transition::Paint (Option_t * option = "")
Definition at line 101 of file LevelSchemeFitter.cc.
References fEnergy, fLabel, fUncertainty, and GamR::Utils::wrresult().
Member Data Documentation
fEnergy
Double_t GamR::Nucleus::LevelSchemeFitter::Transition::fEnergy
Definition at line 36 of file LevelSchemeFitter.hh.
Referenced by operator<(), and Paint().
fFinal
State* GamR::Nucleus::LevelSchemeFitter::Transition::fFinal
Definition at line 34 of file LevelSchemeFitter.hh.
fInitial
State* GamR::Nucleus::LevelSchemeFitter::Transition::fInitial
Definition at line 33 of file LevelSchemeFitter.hh.
fLabel
TText* GamR::Nucleus::LevelSchemeFitter::Transition::fLabel = NULL
Definition at line 38 of file LevelSchemeFitter.hh.
Referenced by Transition(), Transition(), and Paint().
fUncertainty
Double_t GamR::Nucleus::LevelSchemeFitter::Transition::fUncertainty
Definition at line 37 of file LevelSchemeFitter.hh.
Referenced by Paint().
The documentation for this class was generated from the following files:
src/lib/nucleus/LevelSchemeFitter.hh
src/lib/nucleus/LevelSchemeFitter.cc