GamR: src/bin/gamrcal/gamrcal.cc File Reference
gamrcal.cc File Reference
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <TApplication.h>
#include <TCanvas.h>
#include <TFile.h>
#include <TH1.h>
#include <TROOT.h>
#include <TSystem.h>
#include <TTree.h>
#include <args/args.hxx>
#include "Gain.hh"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 19 of file gamrcal.cc.
References GamR::TK::GainMatchEnergy(), help(), and ss().