GamR: GamR::Sort::Sorter Class Reference
GamR::Sort::Sorter Class Reference
#include <Sorter.hh>
Public Member Functions
Sorter (std::vector< std::string > fns, std::string out, Int_t compression=101)
~Sorter ()
Bool_t Done ()
void Tick ()
void SetXsize (ULong64_t bins, Long64_t low, Long64_t high)
void SetYsize (ULong64_t bins, Long64_t low, Long64_t high)
void SetZsize (ULong64_t bins, Long64_t low, Long64_t high)
std::shared_ptr< TH1D > GetSpectrum (std::string s)
std::shared_ptr< TH2D > GetMatrix (std::string s)
std::shared_ptr< TH3D > GetCube (std::string s)
template<class Sort >
void Process (std::vector< std::string > args)
template<class Sort >
void Process (Sort &sort)
void PrintStatus ()
void Halt ()
void Write (std::string folder="/")
void WriteObject (TObject *obj, const char *folder="/", const char *rename="", bool quiet=kFALSE)
void Clear ()
Detailed Description
Definition at line 28 of file Sorter.hh.
Constructor & Destructor Documentation
Sorter()
GamR::Sort::Sorter::Sorter (std::vector< std::string > fns, std::string out, Int_t compression = 101)
Definition at line 9 of file Sorter.cc.
~Sorter()
GamR::Sort::Sorter::~Sorter ()
Definition at line 29 of file Sorter.cc.
Member Function Documentation
Clear()
void GamR::Sort::Sorter::Clear ()
Definition at line 82 of file Sorter.cc.
Done()
Bool_t GamR::Sort::Sorter::Done ()
Definition at line 89 of file Sorter.cc.
Referenced by main(), GamR::Sort::Type::CoincidenceCubeDiff< DetX, DetY, X, Y, Z >::operator()(), GamR::Sort::Type::CoincidenceMatrix< DetX, DetY, X, Y >::operator()(), GamR::Sort::Type::CoincidenceMatrixPair< DetX, DetY, X, Y >::operator()(), GamR::Sort::Type::GatedTimeDifference< DetGate, S, DetTime, E, T >::operator()(), GamR::Sort::Type::Matrix::operator()(), GamR::Sort::Type::TimeDifference< Det, E, T >::operator()(), GamR::Sort::Type::TimeDifferencePairs< Det, E, T >::operator()(), and GamR::Sort::Type::TimeWalkCal< Det, E, T >::operator()().
GetCube()
std::shared_ptr< TH3D > GamR::Sort::Sorter::GetCube (std::string s)
Definition at line 183 of file Sorter.cc.
Referenced by GamR::Sort::Type::CoincidenceCubeDiff< DetX, DetY, X, Y, Z >::CoincidenceCubeDiff().
GetMatrix()
std::shared_ptr< TH2D > GamR::Sort::Sorter::GetMatrix (std::string s)
Definition at line 173 of file Sorter.cc.
Referenced by GamR::Sort::Type::CoincidenceMatrix< DetX, DetY, X, Y >::CoincidenceMatrix(), GamR::Sort::Type::CoincidenceMatrixPair< DetX, DetY, X, Y >::CoincidenceMatrixPair(), GamR::Sort::Type::GatedTimeDifference< DetGate, S, DetTime, E, T >::GatedTimeDifference(), GamR::Sort::Type::Matrix::Matrix(), GamR::Sort::Type::TimeDifference< Det, E, T >::TimeDifference(), GamR::Sort::Type::TimeDifferencePairs< Det, E, T >::TimeDifferencePairs(), and GamR::Sort::Type::TimeWalkCal< Det, E, T >::TimeWalkCal().
GetSpectrum()
std::shared_ptr< TH1D > GamR::Sort::Sorter::GetSpectrum (std::string s)
Definition at line 163 of file Sorter.cc.
Halt()
void GamR::Sort::Sorter::Halt ()
Definition at line 41 of file Sorter.cc.
Referenced by main().
PrintStatus()
void GamR::Sort::Sorter::PrintStatus ()
Definition at line 52 of file Sorter.cc.
Referenced by main().
Process() [1/2]
template<class Sort > void GamR::Sort::Sorter::Process (Sort & sort) inline
Definition at line 82 of file Sorter.hh.
Process() [2/2]
template<class Sort > void GamR::Sort::Sorter::Process (std::vector< std::string > args) inline
Definition at line 73 of file Sorter.hh.
Referenced by main().
SetXsize()
void GamR::Sort::Sorter::SetXsize (ULong64_t bins, Long64_t low, Long64_t high)
Definition at line 142 of file Sorter.cc.
Referenced by GamR::Sort::Type::CoincidenceMatrix< DetX, DetY, X, Y >::CoincidenceMatrix(), and main().
SetYsize()
void GamR::Sort::Sorter::SetYsize (ULong64_t bins, Long64_t low, Long64_t high)
Definition at line 149 of file Sorter.cc.
Referenced by GamR::Sort::Type::CoincidenceMatrix< DetX, DetY, X, Y >::CoincidenceMatrix(), and main().
SetZsize()
void GamR::Sort::Sorter::SetZsize (ULong64_t bins, Long64_t low, Long64_t high)
Definition at line 156 of file Sorter.cc.
Referenced by main().
Tick()
void GamR::Sort::Sorter::Tick ()
Definition at line 77 of file Sorter.cc.
Referenced by GamR::Sort::Type::CoincidenceCubeDiff< DetX, DetY, X, Y, Z >::operator()(), GamR::Sort::Type::CoincidenceMatrix< DetX, DetY, X, Y >::operator()(), GamR::Sort::Type::CoincidenceMatrixPair< DetX, DetY, X, Y >::operator()(), GamR::Sort::Type::GatedTimeDifference< DetGate, S, DetTime, E, T >::operator()(), GamR::Sort::Type::Matrix::operator()(), GamR::Sort::Type::TimeDifference< Det, E, T >::operator()(), GamR::Sort::Type::TimeDifferencePairs< Det, E, T >::operator()(), and GamR::Sort::Type::TimeWalkCal< Det, E, T >::operator()().
Write()
void GamR::Sort::Sorter::Write (std::string folder = "/")
Definition at line 93 of file Sorter.cc.
Referenced by main().
WriteObject()
void GamR::Sort::Sorter::WriteObject (TObject * obj, const char * folder = "/", const char * rename = "", bool quiet = kFALSE)
Definition at line 123 of file Sorter.cc.
Referenced by GamR::Sort::Type::GatedTimeDifference< DetGate, S, DetTime, E, T >::GatedTimeDifference(), GamR::Sort::Type::Matrix::Matrix(), GamR::Sort::Type::TimeDifference< Det, E, T >::TimeDifference(), GamR::Sort::Type::TimeDifferencePairs< Det, E, T >::TimeDifferencePairs(), and GamR::Sort::Type::TimeWalkCal< Det, E, T >::TimeWalkCal().
The documentation for this class was generated from the following files:
src/lib/sort/Sorter.hh
src/lib/sort/Sorter.cc